#!/usr/bin/env bats

# Tests for core/scripts/gen_enforcement_registry.sh (FR-199)
#
# The generator scans core/enforcement/*.md self-describing definitions and
# emits core/enforcement/INDEX.md. It hard-fails (non-zero exit) on any
# definition missing a required frontmatter field. Required fields:
#   obligation, mechanism, status, lives_in, summary
#
# Because the generator resolves its paths from its own location
# (SCRIPT_DIR/..), each test builds a throwaway `core/{scripts,enforcement}`
# tree under TEST_TEMP_DIR, copies the real generator into it, seeds fixture
# definitions, and runs the copied generator.

load test_helper

# The real generator under test.
GEN_SRC="$IGRIS_ROOT/core/scripts/gen_enforcement_registry.sh"

# Build a throwaway core/ tree with the generator installed at
# <root>/core/scripts/gen.sh and an empty <root>/core/enforcement/.
# Echoes the enforcement dir path.
setup_fixture_tree() {
  local root="$TEST_TEMP_DIR/fixture-$BATS_TEST_NUMBER"
  mkdir -p "$root/core/scripts" "$root/core/enforcement"
  cp "$GEN_SRC" "$root/core/scripts/gen.sh"
  chmod +x "$root/core/scripts/gen.sh"
  echo "$root"
}

# Write a complete, valid fixture definition.
# Usage: write_valid_def <enforcement_dir> <slug>
write_valid_def() {
  local dir="$1"
  local slug="$2"
  cat > "$dir/$slug.md" <<EOF
---
obligation: "Test obligation $slug"
mechanism: gate
status: shipped
lives_in: "core/test/$slug.sh"
summary: "A test summary for $slug."
---

# $slug
Body.
EOF
}

setup() {
  require_python3
}

@test "generator is executable and shellcheck-clean" {
  [ -x "$GEN_SRC" ]
  if command -v shellcheck &> /dev/null; then
    run shellcheck "$GEN_SRC"
    assert_success
  else
    skip "shellcheck not available"
  fi
}

@test "generator emits the expected INDEX table from fixtures" {
  local root
  root="$(setup_fixture_tree)"
  write_valid_def "$root/core/enforcement" "alpha"
  write_valid_def "$root/core/enforcement" "beta"

  run bash "$root/core/scripts/gen.sh"
  assert_success

  local index="$root/core/enforcement/INDEX.md"
  assert_file_exists "$index"
  # GENERATED banner present.
  assert_file_contains "$index" "GENERATED by core/scripts/gen_enforcement_registry.sh"
  assert_file_contains "$index" "DO NOT EDIT BY HAND"
  # Header row with all five columns.
  assert_file_contains "$index" "| obligation | mechanism | status | lives_in | summary |"
  # Both fixtures appear as rows.
  assert_file_contains "$index" "Test obligation alpha"
  assert_file_contains "$index" "Test obligation beta"
  assert_file_contains "$index" "core/test/alpha.sh"
  # INDEX.md is never scanned as a definition (no self-reference row).
  run grep -c "Test obligation" "$index"
  [ "$output" = "2" ]
}

@test "generator hard-fails on a definition missing a required field" {
  local root
  root="$(setup_fixture_tree)"
  write_valid_def "$root/core/enforcement" "good"
  # Bad definition: omit the required 'summary' field.
  cat > "$root/core/enforcement/bad.md" <<'EOF'
---
obligation: "Incomplete obligation"
mechanism: gate
status: shipped
lives_in: "core/test/bad.sh"
---

# bad
EOF

  run bash "$root/core/scripts/gen.sh"
  assert_failure
  assert_output_contains "incomplete frontmatter"
  assert_output_contains "bad: missing summary"
}

@test "generator hard-fails when each required field is the missing one" {
  local fields=(obligation mechanism status lives_in summary)
  for missing in "${fields[@]}"; do
    local root
    root="$(setup_fixture_tree)"
    # Write a definition with every field EXCEPT the one under test.
    {
      echo "---"
      [ "$missing" != "obligation" ] && echo 'obligation: "O"'
      [ "$missing" != "mechanism" ]  && echo 'mechanism: gate'
      [ "$missing" != "status" ]     && echo 'status: shipped'
      [ "$missing" != "lives_in" ]   && echo 'lives_in: "x.sh"'
      [ "$missing" != "summary" ]    && echo 'summary: "S."'
      echo "---"
    } > "$root/core/enforcement/probe.md"

    run bash "$root/core/scripts/gen.sh"
    [ "$status" -ne 0 ] || { echo "expected failure when '$missing' is absent" >&2; return 1; }
  done
}

@test "generator hard-fails when no definitions exist" {
  local root
  root="$(setup_fixture_tree)"
  # enforcement dir exists but is empty.
  run bash "$root/core/scripts/gen.sh"
  assert_failure
  assert_output_contains "no enforcement definitions found"
}

@test "drift check: committed INDEX.md reproduces byte-for-byte" {
  # Running the real generator against the committed core/enforcement/ must
  # reproduce the committed INDEX.md exactly — no stale index.
  local committed="$IGRIS_ROOT/core/enforcement/INDEX.md"
  assert_file_exists "$committed"

  local snapshot="$TEST_TEMP_DIR/INDEX.committed.snapshot"
  cp "$committed" "$snapshot"

  run bash "$GEN_SRC"
  assert_success

  run diff -q "$snapshot" "$committed"
  assert_success
}
