/**
 * Context Component Unit Tests
 *
 * FR-187 cutover: the legacy igris_tree.json + igris_os.md monolith are
 * retired. The roster-reading tools (igris_context_tree, igris_context_load)
 * are re-pointed onto the generated os/ INDEX (~/.igris/core/os/INDEX.md).
 *
 * Tests:
 * 1. parseIndexModules: roster-table parsing from the os/ INDEX markdown
 * 2. moduleFilePath / osIndexPath: module-name -> file resolution
 * 3. resolveContextPath: tilde and {project} placeholder expansion
 * 4. igris_context_tree handler: reads os/INDEX.md, error path
 * 5. igris_context_load handler: scope-based boot-module selection, errors, missing files
 * 6. Component metadata: name, version, tools count, events
 *
 * @module engine/components/context/__tests__/context.test
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { homedir } from 'node:os';
import { join } from 'node:path';

// ---------------------------------------------------------------------------
// Module mocks -- must be declared before imports that use them
// ---------------------------------------------------------------------------

// Mock node:fs
vi.mock('node:fs', async () => {
  const actual = await vi.importActual<typeof import('node:fs')>('node:fs');
  return {
    ...actual,
    existsSync: vi.fn(),
    readFileSync: vi.fn(),
  };
});

// Mock node:os to control homedir
vi.mock('node:os', async () => {
  const actual = await vi.importActual<typeof import('node:os')>('node:os');
  return {
    ...actual,
    homedir: vi.fn(() => '/mock-home'),
  };
});

// ---------------------------------------------------------------------------
// Import after mocks
// ---------------------------------------------------------------------------

import { existsSync, readFileSync } from 'node:fs';
import {
  parseIndexModules,
  moduleFilePath,
  osIndexPath,
  resolveContextPath,
  createContextComponent,
} from '../index.js';

// ---------------------------------------------------------------------------
// Test fixtures
// ---------------------------------------------------------------------------

// A representative os/ INDEX markdown (shape produced by gen_os_index.sh).
// Boot-tier orchestrator: conduct, delegation, SOUL. Boot-tier universal:
// standards. On-demand/reference rows must be ignored by the boot loader.
const SAMPLE_INDEX = `<!-- GENERATED by core/scripts/gen_os_index.sh — DO NOT EDIT BY HAND. -->

# Igris OS — Module Index

Some preamble prose describing the index.

| module | layer | tier | scope | summary | consult_when |
|---|---|---|---|---|---|
| conduct | conduct | boot | orchestrator | The orchestrator's operating contract. | — |
| delegation | capability | boot | orchestrator | How you delegate. | — |
| SOUL | identity | boot | orchestrator | The OS persona. | — |
| standards | conduct | boot | universal | Cross-actor baseline every actor follows. | — |
| knowledge-map | knowledge-map | on-demand | orchestrator | The map of where knowledge lives. | routing knowledge |
| self-maintenance | reference | on-demand | orchestrator | How to extend the OS. | extending the OS |

## Agent roster

| agent | role |
|---|---|
| forger | Code implementation specialist. |
| architect | Strategic implementation planner. |
`;

// Module file contents keyed by their resolved paths.
const CONDUCT_CONTENT = '# Conduct\n\nThe operating contract.\n';
const DELEGATION_CONTENT = '# Delegation\n\nHow you delegate.\n';
const SOUL_CONTENT = '# SOUL\n\nI am Igris.\n';
const STANDARDS_CONTENT = '# Standards\n\nCross-actor baseline.\n';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const INDEX_PATH = join('/mock-home', '.igris', 'core', 'os', 'INDEX.md');
const CONDUCT_PATH = join('/mock-home', '.igris', 'core', 'os', 'conduct.md');
const DELEGATION_PATH = join('/mock-home', '.igris', 'core', 'os', 'delegation.md');
const SOUL_PATH = join('/mock-home', '.igris', 'core', 'SOUL.md');
const STANDARDS_PATH = join('/mock-home', '.igris', 'core', 'os', 'standards.md');

// Seed the INDEX + all boot-tier module files. self-maintenance/knowledge-map
// are deliberately NOT seeded (on-demand tier — never selected by the loader).
function setupIndexMocks(): void {
  vi.mocked(existsSync).mockImplementation((p: unknown) => {
    return [INDEX_PATH, CONDUCT_PATH, DELEGATION_PATH, SOUL_PATH, STANDARDS_PATH].includes(String(p));
  });

  vi.mocked(readFileSync).mockImplementation((p: unknown, _encoding?: unknown) => {
    const pathStr = String(p);
    if (pathStr === INDEX_PATH) return SAMPLE_INDEX;
    if (pathStr === CONDUCT_PATH) return CONDUCT_CONTENT;
    if (pathStr === DELEGATION_PATH) return DELEGATION_CONTENT;
    if (pathStr === SOUL_PATH) return SOUL_CONTENT;
    if (pathStr === STANDARDS_PATH) return STANDARDS_CONTENT;
    throw new Error(`ENOENT: no such file: ${pathStr}`);
  });
}

function getContextLoadHandler(): (args: Record<string, unknown>) => { content: { type: string; text: string }[]; isError?: boolean } {
  const component = createContextComponent();
  const tools = component.tools();
  const loadTool = tools.find((t) => t.name === 'igris_context_load');
  if (!loadTool) throw new Error('igris_context_load tool not found');
  return loadTool.handler as (args: Record<string, unknown>) => { content: { type: string; text: string }[]; isError?: boolean };
}

function getContextTreeHandler(): (args: Record<string, unknown>) => { content: { type: string; text: string }[]; isError?: boolean } {
  const component = createContextComponent();
  const tools = component.tools();
  const treeTool = tools.find((t) => t.name === 'igris_context_tree');
  if (!treeTool) throw new Error('igris_context_tree tool not found');
  return treeTool.handler as (args: Record<string, unknown>) => { content: { type: string; text: string }[]; isError?: boolean };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('Context Component', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  // -------------------------------------------------------------------------
  // 1. parseIndexModules
  // -------------------------------------------------------------------------

  describe('parseIndexModules', () => {
    it('parses only the leading module roster (not the agent roster)', () => {
      const modules = parseIndexModules(SAMPLE_INDEX);
      const names = modules.map((m) => m.module);
      expect(names).toEqual([
        'conduct',
        'delegation',
        'SOUL',
        'standards',
        'knowledge-map',
        'self-maintenance',
      ]);
      // Agent-roster rows must NOT leak into the module list.
      expect(names).not.toContain('forger');
      expect(names).not.toContain('architect');
    });

    it('captures tier and scope per module', () => {
      const modules = parseIndexModules(SAMPLE_INDEX);
      const conduct = modules.find((m) => m.module === 'conduct');
      expect(conduct).toMatchObject({ tier: 'boot', scope: 'orchestrator' });
      const standards = modules.find((m) => m.module === 'standards');
      expect(standards).toMatchObject({ tier: 'boot', scope: 'universal' });
      const km = modules.find((m) => m.module === 'knowledge-map');
      expect(km).toMatchObject({ tier: 'on-demand', scope: 'orchestrator' });
    });

    it('returns empty array when there is no module table', () => {
      const noTable = '# Igris OS\n\nJust prose, no table here.\n';
      expect(parseIndexModules(noTable)).toEqual([]);
    });

    it('skips the markdown separator row', () => {
      const modules = parseIndexModules(SAMPLE_INDEX);
      expect(modules.every((m) => !/^-+$/.test(m.module))).toBe(true);
    });
  });

  // -------------------------------------------------------------------------
  // 2. moduleFilePath / osIndexPath
  // -------------------------------------------------------------------------

  describe('moduleFilePath', () => {
    it('resolves SOUL to core/SOUL.md (not core/os/)', () => {
      expect(moduleFilePath('SOUL')).toBe(`${homedir()}/.igris/core/SOUL.md`);
    });

    it('resolves a normal module to core/os/<name>.md', () => {
      expect(moduleFilePath('conduct')).toBe(`${homedir()}/.igris/core/os/conduct.md`);
    });

    it('resolves a hyphenated module name', () => {
      expect(moduleFilePath('knowledge-map')).toBe(`${homedir()}/.igris/core/os/knowledge-map.md`);
    });
  });

  describe('osIndexPath', () => {
    it('points at ~/.igris/core/os/INDEX.md', () => {
      expect(osIndexPath()).toBe(`${homedir()}/.igris/core/os/INDEX.md`);
    });
  });

  // -------------------------------------------------------------------------
  // 3. resolveContextPath
  // -------------------------------------------------------------------------

  describe('resolveContextPath', () => {
    it('replaces ~ with homedir', () => {
      const result = resolveContextPath('~/.igris/core/SOUL.md', 'test');
      expect(result).toBe(`${homedir()}/.igris/core/SOUL.md`);
    });

    it('replaces {project} with project slug', () => {
      const result = resolveContextPath('~/.igris/projects/{project}/context/file.md', 'my-app');
      expect(result).toBe(`${homedir()}/.igris/projects/my-app/context/file.md`);
    });

    it('replaces multiple {project} occurrences', () => {
      const result = resolveContextPath('{project}/a/{project}/b', 'slug');
      expect(result).toBe('slug/a/slug/b');
    });

    it('replaces {repo_root} with the registry repo path (FR-186)', () => {
      const result = resolveContextPath(
        '{repo_root}/MAINTAINING.md',
        'igris-ai',
        '/Users/m.elamin/StudioProjects/igris-ai'
      );
      expect(result).toBe('/Users/m.elamin/StudioProjects/igris-ai/MAINTAINING.md');
    });

    it('strips a trailing slash from {repo_root} before joining (FR-186)', () => {
      const result = resolveContextPath('{repo_root}/MAINTAINING.md', 'slug', '/repo/path/');
      expect(result).toBe('/repo/path/MAINTAINING.md');
    });

    it('leaves {repo_root} unresolved when no repoRoot is provided (FR-186)', () => {
      const result = resolveContextPath('{repo_root}/MAINTAINING.md', 'slug');
      expect(result).toBe('{repo_root}/MAINTAINING.md');
    });

    it('resolves {repo_root} alongside ~ and {project} in one path (FR-186)', () => {
      const result = resolveContextPath('{repo_root}/x/{project}/y', 'slug', '/repo');
      expect(result).toBe('/repo/x/slug/y');
    });

    it('handles paths without tilde', () => {
      const result = resolveContextPath('/absolute/path/file.md', 'test');
      expect(result).toBe('/absolute/path/file.md');
    });

    it('handles paths without {project}', () => {
      const result = resolveContextPath('~/.igris/core/SOUL.md', 'ignored');
      expect(result).toBe(`${homedir()}/.igris/core/SOUL.md`);
    });

    it('rejects project slugs containing ".."', () => {
      expect(() => resolveContextPath('~/.igris/projects/{project}/file.md', '../../etc'))
        .toThrow('Invalid project slug');
    });

    it('rejects project slugs containing "/"', () => {
      expect(() => resolveContextPath('~/.igris/projects/{project}/file.md', 'foo/bar'))
        .toThrow('Invalid project slug');
    });

    it('rejects project slugs containing "\\"', () => {
      expect(() => resolveContextPath('~/.igris/projects/{project}/file.md', 'foo\\bar'))
        .toThrow('Invalid project slug');
    });

    it('rejects project slugs with embedded traversal like "foo/../bar"', () => {
      expect(() => resolveContextPath('~/.igris/projects/{project}/file.md', 'foo/../bar'))
        .toThrow('Invalid project slug');
    });
  });

  // -------------------------------------------------------------------------
  // 4. igris_context_tree
  // -------------------------------------------------------------------------

  describe('igris_context_tree', () => {
    it('returns the os/ INDEX content', () => {
      setupIndexMocks();
      const handler = getContextTreeHandler();

      const result = handler({});
      expect(result.isError).toBeUndefined();
      expect(result.content[0].text).toBe(SAMPLE_INDEX);
      expect(result.content[0].text).toContain('# Igris OS — Module Index');
    });

    it('reads from ~/.igris/core/os/INDEX.md', () => {
      setupIndexMocks();
      const handler = getContextTreeHandler();
      handler({});
      expect(vi.mocked(readFileSync)).toHaveBeenCalledWith(INDEX_PATH, 'utf-8');
    });

    it('returns an error naming the os/ INDEX when the file is unreadable', () => {
      vi.mocked(readFileSync).mockImplementation(() => {
        throw new Error('ENOENT');
      });
      const handler = getContextTreeHandler();

      const result = handler({});
      expect(result.isError).toBe(true);
      expect(result.content[0].text).toContain('os/ INDEX');
      expect(result.content[0].text).toContain('~/.igris/core/os/INDEX.md');
    });
  });

  // -------------------------------------------------------------------------
  // 5. igris_context_load handler
  // -------------------------------------------------------------------------

  describe('igris_context_load', () => {
    it('a task actor loads orchestrator + universal boot modules', () => {
      setupIndexMocks();
      const handler = getContextLoadHandler();

      const result = handler({ actor: '/awaken', project: 'my-project' });
      expect(result.isError).toBeUndefined();

      const parsed = JSON.parse(result.content[0].text);
      expect(parsed.actor).toBe('/awaken');
      expect(parsed.actor_type).toBe('task');
      expect(parsed.project).toBe('my-project');

      const keys = parsed.files.map((f: { key: string }) => f.key).sort();
      // boot-tier: conduct, delegation, SOUL (orchestrator) + standards (universal)
      expect(keys).toEqual(['SOUL', 'conduct', 'delegation', 'standards']);
      expect(parsed.total_kb).toBeGreaterThan(0);
    });

    it('an agent actor loads ONLY universal boot modules', () => {
      setupIndexMocks();
      const handler = getContextLoadHandler();

      const result = handler({ actor: 'forger', project: 'my-project' });
      expect(result.isError).toBeUndefined();

      const parsed = JSON.parse(result.content[0].text);
      expect(parsed.actor).toBe('forger');
      expect(parsed.actor_type).toBe('agent');

      const keys = parsed.files.map((f: { key: string }) => f.key);
      // universal boot only — no orchestrator-scoped modules.
      expect(keys).toEqual(['standards']);
      expect(keys).not.toContain('conduct');
      expect(keys).not.toContain('SOUL');
    });

    it('does not load on-demand / reference tier modules', () => {
      setupIndexMocks();
      const handler = getContextLoadHandler();

      const result = handler({ actor: '/hunt', project: 'my-project' });
      const parsed = JSON.parse(result.content[0].text);
      const keys = parsed.files.map((f: { key: string }) => f.key);
      expect(keys).not.toContain('knowledge-map'); // on-demand
      expect(keys).not.toContain('self-maintenance'); // reference
    });

    it('resolves SOUL to core/SOUL.md, not core/os/', () => {
      setupIndexMocks();
      const handler = getContextLoadHandler();

      const result = handler({ actor: '/awaken', project: 'my-project' });
      const parsed = JSON.parse(result.content[0].text);
      const soulFile = parsed.files.find((f: { key: string }) => f.key === 'SOUL');
      expect(soulFile).toBeDefined();
      expect(soulFile.path).toBe(SOUL_PATH);
      expect(soulFile.content).toContain('I am Igris.');
    });

    it('gracefully reports a boot module whose file is missing', () => {
      // Index lists SOUL as boot/orchestrator but the SOUL file is absent.
      vi.mocked(existsSync).mockImplementation((p: unknown) => {
        const s = String(p);
        return [INDEX_PATH, CONDUCT_PATH, DELEGATION_PATH, STANDARDS_PATH].includes(s); // no SOUL
      });
      vi.mocked(readFileSync).mockImplementation((p: unknown) => {
        const s = String(p);
        if (s === INDEX_PATH) return SAMPLE_INDEX;
        if (s === CONDUCT_PATH) return CONDUCT_CONTENT;
        if (s === DELEGATION_PATH) return DELEGATION_CONTENT;
        if (s === STANDARDS_PATH) return STANDARDS_CONTENT;
        throw new Error(`ENOENT: no such file: ${s}`);
      });

      const handler = getContextLoadHandler();
      const result = handler({ actor: '/awaken', project: 'my-project' });
      expect(result.isError).toBeUndefined();

      const parsed = JSON.parse(result.content[0].text);
      expect(parsed.missing).toContain('SOUL');
      const keys = parsed.files.map((f: { key: string }) => f.key);
      expect(keys).not.toContain('SOUL');
      expect(keys).toContain('conduct');
    });

    it('returns an error when the os/ INDEX is missing', () => {
      vi.mocked(existsSync).mockReturnValue(false);
      const handler = getContextLoadHandler();

      const result = handler({ actor: '/hunt', project: 'my-project' });
      expect(result.isError).toBe(true);
      expect(result.content[0].text).toContain('os/ INDEX not found');
      expect(result.content[0].text).toContain('~/.igris/core/os/INDEX.md');
      // The retired monolith must NOT be referenced in the fallback.
      expect(result.content[0].text).not.toContain('igris_os.md');
      expect(result.content[0].text).not.toContain('igris_tree.json');
    });

    it('reports total_kb as a number', () => {
      setupIndexMocks();
      const handler = getContextLoadHandler();

      const result = handler({ actor: '/awaken', project: 'my-project' });
      const parsed = JSON.parse(result.content[0].text);
      expect(typeof parsed.total_kb).toBe('number');
      expect(parsed.total_kb).toBeGreaterThan(0);
    });

    it('includes resolved file paths in output (no tilde, no placeholders)', () => {
      setupIndexMocks();
      const handler = getContextLoadHandler();

      const result = handler({ actor: '/awaken', project: 'my-project' });
      const parsed = JSON.parse(result.content[0].text);

      for (const file of parsed.files) {
        expect(file.path).toBeDefined();
        expect(file.path).toContain('/mock-home/.igris/');
        expect(file.path).not.toContain('~');
        expect(file.path).not.toContain('{project}');
      }
    });

    it('each file entry has key, path, content, and size_bytes', () => {
      setupIndexMocks();
      const handler = getContextLoadHandler();

      const result = handler({ actor: '/awaken', project: 'my-project' });
      const parsed = JSON.parse(result.content[0].text);

      for (const file of parsed.files) {
        expect(file).toHaveProperty('key');
        expect(file).toHaveProperty('path');
        expect(file).toHaveProperty('content');
        expect(file).toHaveProperty('size_bytes');
        expect(typeof file.size_bytes).toBe('number');
      }
    });
  });

  // -------------------------------------------------------------------------
  // 6. Component metadata
  // -------------------------------------------------------------------------

  describe('component metadata', () => {
    it('component name is "context"', () => {
      const comp = createContextComponent();
      expect(comp.name).toBe('context');
    });

    it('component version is "1.0.0"', () => {
      const comp = createContextComponent();
      expect(comp.version).toBe('1.0.0');
    });

    it('tools() returns 4 tools', () => {
      const comp = createContextComponent();
      const tools = comp.tools();
      expect(tools).toHaveLength(4);
      const names = tools.map((t) => t.name);
      expect(names).toContain('igris_context_register');
      expect(names).toContain('igris_context_get');
      expect(names).toContain('igris_context_tree');
      expect(names).toContain('igris_context_load');
    });

    it('events() declares 1 emit (context.registered)', () => {
      const comp = createContextComponent();
      const { emits } = comp.events();
      expect(emits).toHaveLength(1);
      expect(emits[0].name).toBe('context.registered');
    });

    it('events() declares 0 listens', () => {
      const comp = createContextComponent();
      const { listens } = comp.events();
      expect(listens).toHaveLength(0);
    });

    it('schema() returns 1 migration', () => {
      const comp = createContextComponent();
      const migrations = comp.schema();
      expect(migrations).toHaveLength(1);
      expect(migrations[0].version).toBe(1);
    });

    it('depends on projects component', () => {
      const comp = createContextComponent();
      expect(comp.depends).toContain('projects');
    });
  });
});
