// GENERATED by brain-mcp-server/scripts/gen-brief-normalize-mirror.ts — DO NOT EDIT BY HAND.
// Re-run `npm run gen:brief-normalize-mirror` (in brain-mcp-server/) to refresh; edits here are overwritten.
//
// TD-338 — the CLI-side copy of the brief metadata normalizers. The CLI and
// brain-mcp-server are separate npm packages with ZERO cross-imports
// (coding_guidelines §13), so the CLI reads this committed copy. The brain-side
// parity test asserts it is byte-identical to a fresh regeneration, so any edit
// to the fold tables that is not regenerated fails CI.
//
// THE LOGIC HALF. Byte-parity cannot see a change to a function BODY here,
// because the bodies are authored in the builder rather than derived from the
// source. Three fixture tables close that, each computed by running the
// BRAIN's real code at generation time and replayed by the CLI-side test:
//   NORMALIZE_FIXTURES  — the three leaf normalizers
//   PREDICATE_FIXTURES  — the three isCanonical* predicates
//   SYNC_ROW_FIXTURES   — normalizeSyncRow, the function mergeRows calls
// Together they cover every authored function in this module, so a brain-side
// logic change that is not reproduced here fails on the CLI side.
//
// Source of truth: brain-mcp-server/src/tools/brief-normalize.ts

/** Canonical brief phases — the brief state-machine vocabulary. */
export const CANONICAL_PHASES: readonly string[] = [
  "INIT",
  "PLANNING",
  "APPROVAL",
  "BUILDING",
  "TESTING",
  "REVIEWING",
  "DOCUMENTING",
  "COMMITTING",
  "COMPLETE",
  "BLOCKED",
];

/** Canonical brief priorities. A genuinely unset priority is SQL NULL, NOT a member. */
export const CANONICAL_PRIORITIES: readonly string[] = [
  "P0-Critical",
  "P1-High",
  "P2-Medium",
  "P3-Low",
];

/** Canonical brief types (TD-328). */
export const CANONICAL_BRIEF_TYPES: readonly string[] = [
  "Feature",
  "Bug",
  "Migration",
  "Technical Debt",
  "Testing",
  "Process Improvement",
  "Documentation",
  "Acceptance",
  "Performance",
  "Architecture",
  "Dependency Update",
  "Refactor",
];

/** Priority alias fold map. Keys are lowercase + trimmed; lookup is `v.trim().toLowerCase()`. */
export const PRIORITY_ALIASES: Readonly<Record<string, string>> = {
  "p0": "P0-Critical",
  "p1": "P1-High",
  "p2": "P2-Medium",
  "p3": "P3-Low",
  "p0 - critical": "P0-Critical",
  "p1 - high": "P1-High",
  "p2 - medium": "P2-Medium",
  "p3 - low": "P3-Low",
  "p0-critical": "P0-Critical",
  "p1-high": "P1-High",
  "p2-medium": "P2-Medium",
  "p3-low": "P3-Low",
};

/** brief_type unconditional alias fold map. Keys are lowercase + trimmed. */
export const BRIEF_TYPE_ALIASES: Readonly<Record<string, string>> = {
  "tech debt": "Technical Debt",
  "td": "Technical Debt",
  "debt": "Technical Debt",
  "techdebt": "Technical Debt",
  "technicaldebt": "Technical Debt",
  "tech_debt": "Technical Debt",
  "tech-debt": "Technical Debt",
  "chore": "Technical Debt",
  "bug fix": "Bug",
  "bugfix": "Bug",
  "fr": "Feature",
  "feature request": "Feature",
  "featurerequest": "Feature",
  "enhancement": "Feature",
  "feature enhancement": "Feature",
  "refactoring": "Refactor",
  "architecturecleanup": "Architecture",
  "dependencyupdate": "Dependency Update",
  "doc": "Documentation",
  "test": "Testing",
  "process": "Process Improvement",
  "release": "Process Improvement",
};

/** Canonical brief_type lookup keyed by lowercase, for idempotent case-folding. */
const BRIEF_TYPE_CANONICAL: Readonly<Record<string, string>> = Object.fromEntries(
  CANONICAL_BRIEF_TYPES.map((t) => [t.toLowerCase(), t]),
);

/**
 * Stable normalizer id — the key `SYNC_NORMALIZED_FIELDS` dispatches on.
 * DERIVED from the values actually present in that map, so adding a
 * normalized field widens this union automatically.
 */
export type SyncNormalizerId = "brief_type" | "phase" | "priority";

/**
 * Which synced columns pass through a write-boundary normalizer on INGRESS,
 * per table. A table absent from this map is copied verbatim.
 */
export const SYNC_NORMALIZED_FIELDS: Readonly<
  Record<string, Readonly<Record<string, SyncNormalizerId>>>
> = {
  "brief_status": {
    "brief_type": "brief_type",
    "priority": "priority",
    "phase": "phase",
  },
};

/**
 * Normalize a brief_type to its canonical spelling. Known aliases fold, any
 * case variant of a canonical type folds to its canonical casing, unknown
 * values pass through UNCHANGED. null/undefined/empty -> null.
 */
export function normalizeBriefType(v: string | null | undefined): string | null {
  if (v === null || v === undefined) return null;
  const trimmed = v.trim();
  if (trimmed === '') return null;
  const key = trimmed.toLowerCase();
  return BRIEF_TYPE_ALIASES[key] ?? BRIEF_TYPE_CANONICAL[key] ?? v;
}

/** Is `v` a canonical brief_type? Case-insensitive, trim-tolerant. */
export function isCanonicalBriefType(v: string | null | undefined): boolean {
  if (v === null || v === undefined) return false;
  return BRIEF_TYPE_CANONICAL[v.trim().toLowerCase()] !== undefined;
}

/**
 * Normalize a brief phase to its canonical (uppercase) spelling. Known phases
 * fold; unknown values pass through UNCHANGED. null/undefined/empty -> null.
 */
export function normalizePhase(v: string | null | undefined): string | null {
  if (v === null || v === undefined) return null;
  const trimmed = v.trim();
  if (trimmed === '') return null;
  const upper = trimmed.toUpperCase();
  const match = CANONICAL_PHASES.find((p) => p === upper);
  return match ?? v;
}

/** Is `v` a canonical phase? Case-insensitive, trim-tolerant. */
export function isCanonicalPhase(v: string | null | undefined): boolean {
  if (v === null || v === undefined) return false;
  const upper = v.trim().toUpperCase();
  return CANONICAL_PHASES.some((p) => p === upper);
}

/**
 * Normalize a brief priority to its canonical `P{N}-{Word}` spelling. The
 * "unset" family (empty, whitespace-only, literal "Unset") maps to SQL NULL.
 * Known aliases fold; unknown non-empty values pass through unchanged.
 */
export function normalizePriority(v: string | null | undefined): string | null {
  if (v === null || v === undefined) return null;
  const trimmed = v.trim();
  if (trimmed === '' || trimmed.toLowerCase() === 'unset') return null;
  const folded = PRIORITY_ALIASES[trimmed.toLowerCase()];
  return folded ?? v;
}

/** Is `v` a canonical priority? NULL is *unset*, not an offender. */
export function isCanonicalPriority(v: string | null | undefined): boolean {
  if (v === null || v === undefined) return false;
  const trimmed = v.trim();
  return CANONICAL_PRIORITIES.some((p) => p === trimmed);
}

interface SyncNormalizerEntry {
  normalize(v: string | null | undefined): string | null;
  isCanonical(v: string | null | undefined): boolean;
}

/** DERIVED dispatch table — one row per normalizer id the map uses. */
const SYNC_NORMALIZERS: Record<SyncNormalizerId, SyncNormalizerEntry> = {
  brief_type: { normalize: normalizeBriefType, isCanonical: isCanonicalBriefType },
  phase: { normalize: normalizePhase, isCanonical: isCanonicalPhase },
  priority: { normalize: normalizePriority, isCanonical: isCanonicalPriority },
};

/** One field folded on ingress: what it arrived as, what was stored. */
export interface SyncFieldFold {
  field: string;
  from: string;
  to: string | null;
}

/** One field that arrived non-canonical and was stored AS-IS (never folded). */
export interface SyncFieldPassthrough {
  field: string;
  value: string;
}

/** The result of normalizing one inbound sync row. */
export interface SyncRowNormalizeResult {
  /** The row to store. The SAME object as the input when nothing folded. */
  row: Record<string, unknown>;
  folds: SyncFieldFold[];
  nonCanonical: SyncFieldPassthrough[];
}

const NO_FOLDS: SyncFieldFold[] = [];
const NO_PASSTHROUGHS: SyncFieldPassthrough[] = [];

/**
 * Fold an inbound replication row through the write-boundary normalizers.
 * FOLD-KNOWN / PASSTHROUGH-UNKNOWN / REPORT-BOTH. Never mutates `row`.
 */
export function normalizeSyncRow(
  table: string,
  row: Record<string, unknown>,
): SyncRowNormalizeResult {
  const fields = SYNC_NORMALIZED_FIELDS[table];
  if (!fields) return { row, folds: NO_FOLDS, nonCanonical: NO_PASSTHROUGHS };

  let out = row;
  let folds: SyncFieldFold[] | null = null;
  let nonCanonical: SyncFieldPassthrough[] | null = null;

  for (const field of Object.keys(fields)) {
    const raw = row[field];
    if (raw === undefined) continue;
    if (raw !== null && typeof raw !== 'string') continue;

    const entry = SYNC_NORMALIZERS[fields[field]];
    const next = entry.normalize(raw);

    if (next !== raw) {
      if (out === row) out = { ...row };
      out[field] = next;
      (folds ??= []).push({ field, from: raw as string, to: next });
    }

    if (next !== null && next.trim() !== '' && !entry.isCanonical(next)) {
      (nonCanonical ??= []).push({ field, value: next });
    }
  }

  return {
    row: out,
    folds: folds ?? NO_FOLDS,
    nonCanonical: nonCanonical ?? NO_PASSTHROUGHS,
  };
}

/** One replayable behavioural fixture: `normalizer(input) === expected`. */
export interface NormalizeFixture {
  normalizer: SyncNormalizerId;
  input: string;
  expected: string | null;
}

/**
 * Input -> output pairs computed by running the BRAIN's real normalizers at
 * generation time. The CLI-side test replays them through the functions above,
 * which is what makes this a behavioural mirror and not just a data copy.
 */
export const NORMALIZE_FIXTURES: readonly NormalizeFixture[] = [
  { normalizer: "priority", input: "P0-Critical", expected: "P0-Critical" },
  { normalizer: "brief_type", input: "P0-Critical", expected: "P0-Critical" },
  { normalizer: "phase", input: "P0-Critical", expected: "P0-Critical" },
  { normalizer: "priority", input: "P1-High", expected: "P1-High" },
  { normalizer: "brief_type", input: "P1-High", expected: "P1-High" },
  { normalizer: "phase", input: "P1-High", expected: "P1-High" },
  { normalizer: "priority", input: "P2-Medium", expected: "P2-Medium" },
  { normalizer: "brief_type", input: "P2-Medium", expected: "P2-Medium" },
  { normalizer: "phase", input: "P2-Medium", expected: "P2-Medium" },
  { normalizer: "priority", input: "P3-Low", expected: "P3-Low" },
  { normalizer: "brief_type", input: "P3-Low", expected: "P3-Low" },
  { normalizer: "phase", input: "P3-Low", expected: "P3-Low" },
  { normalizer: "priority", input: "INIT", expected: "INIT" },
  { normalizer: "brief_type", input: "INIT", expected: "INIT" },
  { normalizer: "phase", input: "INIT", expected: "INIT" },
  { normalizer: "priority", input: "PLANNING", expected: "PLANNING" },
  { normalizer: "brief_type", input: "PLANNING", expected: "PLANNING" },
  { normalizer: "phase", input: "PLANNING", expected: "PLANNING" },
  { normalizer: "priority", input: "APPROVAL", expected: "APPROVAL" },
  { normalizer: "brief_type", input: "APPROVAL", expected: "APPROVAL" },
  { normalizer: "phase", input: "APPROVAL", expected: "APPROVAL" },
  { normalizer: "priority", input: "BUILDING", expected: "BUILDING" },
  { normalizer: "brief_type", input: "BUILDING", expected: "BUILDING" },
  { normalizer: "phase", input: "BUILDING", expected: "BUILDING" },
  { normalizer: "priority", input: "TESTING", expected: "TESTING" },
  { normalizer: "brief_type", input: "TESTING", expected: "Testing" },
  { normalizer: "phase", input: "TESTING", expected: "TESTING" },
  { normalizer: "priority", input: "REVIEWING", expected: "REVIEWING" },
  { normalizer: "brief_type", input: "REVIEWING", expected: "REVIEWING" },
  { normalizer: "phase", input: "REVIEWING", expected: "REVIEWING" },
  { normalizer: "priority", input: "DOCUMENTING", expected: "DOCUMENTING" },
  { normalizer: "brief_type", input: "DOCUMENTING", expected: "DOCUMENTING" },
  { normalizer: "phase", input: "DOCUMENTING", expected: "DOCUMENTING" },
  { normalizer: "priority", input: "COMMITTING", expected: "COMMITTING" },
  { normalizer: "brief_type", input: "COMMITTING", expected: "COMMITTING" },
  { normalizer: "phase", input: "COMMITTING", expected: "COMMITTING" },
  { normalizer: "priority", input: "COMPLETE", expected: "COMPLETE" },
  { normalizer: "brief_type", input: "COMPLETE", expected: "COMPLETE" },
  { normalizer: "phase", input: "COMPLETE", expected: "COMPLETE" },
  { normalizer: "priority", input: "BLOCKED", expected: "BLOCKED" },
  { normalizer: "brief_type", input: "BLOCKED", expected: "BLOCKED" },
  { normalizer: "phase", input: "BLOCKED", expected: "BLOCKED" },
  { normalizer: "priority", input: "Feature", expected: "Feature" },
  { normalizer: "brief_type", input: "Feature", expected: "Feature" },
  { normalizer: "phase", input: "Feature", expected: "Feature" },
  { normalizer: "priority", input: "Bug", expected: "Bug" },
  { normalizer: "brief_type", input: "Bug", expected: "Bug" },
  { normalizer: "phase", input: "Bug", expected: "Bug" },
  { normalizer: "priority", input: "Migration", expected: "Migration" },
  { normalizer: "brief_type", input: "Migration", expected: "Migration" },
  { normalizer: "phase", input: "Migration", expected: "Migration" },
  { normalizer: "priority", input: "Technical Debt", expected: "Technical Debt" },
  { normalizer: "brief_type", input: "Technical Debt", expected: "Technical Debt" },
  { normalizer: "phase", input: "Technical Debt", expected: "Technical Debt" },
  { normalizer: "priority", input: "Testing", expected: "Testing" },
  { normalizer: "brief_type", input: "Testing", expected: "Testing" },
  { normalizer: "phase", input: "Testing", expected: "TESTING" },
  { normalizer: "priority", input: "Process Improvement", expected: "Process Improvement" },
  { normalizer: "brief_type", input: "Process Improvement", expected: "Process Improvement" },
  { normalizer: "phase", input: "Process Improvement", expected: "Process Improvement" },
  { normalizer: "priority", input: "Documentation", expected: "Documentation" },
  { normalizer: "brief_type", input: "Documentation", expected: "Documentation" },
  { normalizer: "phase", input: "Documentation", expected: "Documentation" },
  { normalizer: "priority", input: "Acceptance", expected: "Acceptance" },
  { normalizer: "brief_type", input: "Acceptance", expected: "Acceptance" },
  { normalizer: "phase", input: "Acceptance", expected: "Acceptance" },
  { normalizer: "priority", input: "Performance", expected: "Performance" },
  { normalizer: "brief_type", input: "Performance", expected: "Performance" },
  { normalizer: "phase", input: "Performance", expected: "Performance" },
  { normalizer: "priority", input: "Architecture", expected: "Architecture" },
  { normalizer: "brief_type", input: "Architecture", expected: "Architecture" },
  { normalizer: "phase", input: "Architecture", expected: "Architecture" },
  { normalizer: "priority", input: "Dependency Update", expected: "Dependency Update" },
  { normalizer: "brief_type", input: "Dependency Update", expected: "Dependency Update" },
  { normalizer: "phase", input: "Dependency Update", expected: "Dependency Update" },
  { normalizer: "priority", input: "Refactor", expected: "Refactor" },
  { normalizer: "brief_type", input: "Refactor", expected: "Refactor" },
  { normalizer: "phase", input: "Refactor", expected: "Refactor" },
  { normalizer: "priority", input: "p0", expected: "P0-Critical" },
  { normalizer: "brief_type", input: "p0", expected: "p0" },
  { normalizer: "phase", input: "p0", expected: "p0" },
  { normalizer: "priority", input: "p1", expected: "P1-High" },
  { normalizer: "brief_type", input: "p1", expected: "p1" },
  { normalizer: "phase", input: "p1", expected: "p1" },
  { normalizer: "priority", input: "p2", expected: "P2-Medium" },
  { normalizer: "brief_type", input: "p2", expected: "p2" },
  { normalizer: "phase", input: "p2", expected: "p2" },
  { normalizer: "priority", input: "p3", expected: "P3-Low" },
  { normalizer: "brief_type", input: "p3", expected: "p3" },
  { normalizer: "phase", input: "p3", expected: "p3" },
  { normalizer: "priority", input: "p0 - critical", expected: "P0-Critical" },
  { normalizer: "brief_type", input: "p0 - critical", expected: "p0 - critical" },
  { normalizer: "phase", input: "p0 - critical", expected: "p0 - critical" },
  { normalizer: "priority", input: "p1 - high", expected: "P1-High" },
  { normalizer: "brief_type", input: "p1 - high", expected: "p1 - high" },
  { normalizer: "phase", input: "p1 - high", expected: "p1 - high" },
  { normalizer: "priority", input: "p2 - medium", expected: "P2-Medium" },
  { normalizer: "brief_type", input: "p2 - medium", expected: "p2 - medium" },
  { normalizer: "phase", input: "p2 - medium", expected: "p2 - medium" },
  { normalizer: "priority", input: "p3 - low", expected: "P3-Low" },
  { normalizer: "brief_type", input: "p3 - low", expected: "p3 - low" },
  { normalizer: "phase", input: "p3 - low", expected: "p3 - low" },
  { normalizer: "priority", input: "p0-critical", expected: "P0-Critical" },
  { normalizer: "brief_type", input: "p0-critical", expected: "p0-critical" },
  { normalizer: "phase", input: "p0-critical", expected: "p0-critical" },
  { normalizer: "priority", input: "p1-high", expected: "P1-High" },
  { normalizer: "brief_type", input: "p1-high", expected: "p1-high" },
  { normalizer: "phase", input: "p1-high", expected: "p1-high" },
  { normalizer: "priority", input: "p2-medium", expected: "P2-Medium" },
  { normalizer: "brief_type", input: "p2-medium", expected: "p2-medium" },
  { normalizer: "phase", input: "p2-medium", expected: "p2-medium" },
  { normalizer: "priority", input: "p3-low", expected: "P3-Low" },
  { normalizer: "brief_type", input: "p3-low", expected: "p3-low" },
  { normalizer: "phase", input: "p3-low", expected: "p3-low" },
  { normalizer: "priority", input: "tech debt", expected: "tech debt" },
  { normalizer: "brief_type", input: "tech debt", expected: "Technical Debt" },
  { normalizer: "phase", input: "tech debt", expected: "tech debt" },
  { normalizer: "priority", input: "td", expected: "td" },
  { normalizer: "brief_type", input: "td", expected: "Technical Debt" },
  { normalizer: "phase", input: "td", expected: "td" },
  { normalizer: "priority", input: "debt", expected: "debt" },
  { normalizer: "brief_type", input: "debt", expected: "Technical Debt" },
  { normalizer: "phase", input: "debt", expected: "debt" },
  { normalizer: "priority", input: "techdebt", expected: "techdebt" },
  { normalizer: "brief_type", input: "techdebt", expected: "Technical Debt" },
  { normalizer: "phase", input: "techdebt", expected: "techdebt" },
  { normalizer: "priority", input: "technicaldebt", expected: "technicaldebt" },
  { normalizer: "brief_type", input: "technicaldebt", expected: "Technical Debt" },
  { normalizer: "phase", input: "technicaldebt", expected: "technicaldebt" },
  { normalizer: "priority", input: "tech_debt", expected: "tech_debt" },
  { normalizer: "brief_type", input: "tech_debt", expected: "Technical Debt" },
  { normalizer: "phase", input: "tech_debt", expected: "tech_debt" },
  { normalizer: "priority", input: "tech-debt", expected: "tech-debt" },
  { normalizer: "brief_type", input: "tech-debt", expected: "Technical Debt" },
  { normalizer: "phase", input: "tech-debt", expected: "tech-debt" },
  { normalizer: "priority", input: "chore", expected: "chore" },
  { normalizer: "brief_type", input: "chore", expected: "Technical Debt" },
  { normalizer: "phase", input: "chore", expected: "chore" },
  { normalizer: "priority", input: "bug fix", expected: "bug fix" },
  { normalizer: "brief_type", input: "bug fix", expected: "Bug" },
  { normalizer: "phase", input: "bug fix", expected: "bug fix" },
  { normalizer: "priority", input: "bugfix", expected: "bugfix" },
  { normalizer: "brief_type", input: "bugfix", expected: "Bug" },
  { normalizer: "phase", input: "bugfix", expected: "bugfix" },
  { normalizer: "priority", input: "fr", expected: "fr" },
  { normalizer: "brief_type", input: "fr", expected: "Feature" },
  { normalizer: "phase", input: "fr", expected: "fr" },
  { normalizer: "priority", input: "feature request", expected: "feature request" },
  { normalizer: "brief_type", input: "feature request", expected: "Feature" },
  { normalizer: "phase", input: "feature request", expected: "feature request" },
  { normalizer: "priority", input: "featurerequest", expected: "featurerequest" },
  { normalizer: "brief_type", input: "featurerequest", expected: "Feature" },
  { normalizer: "phase", input: "featurerequest", expected: "featurerequest" },
  { normalizer: "priority", input: "enhancement", expected: "enhancement" },
  { normalizer: "brief_type", input: "enhancement", expected: "Feature" },
  { normalizer: "phase", input: "enhancement", expected: "enhancement" },
  { normalizer: "priority", input: "feature enhancement", expected: "feature enhancement" },
  { normalizer: "brief_type", input: "feature enhancement", expected: "Feature" },
  { normalizer: "phase", input: "feature enhancement", expected: "feature enhancement" },
  { normalizer: "priority", input: "refactoring", expected: "refactoring" },
  { normalizer: "brief_type", input: "refactoring", expected: "Refactor" },
  { normalizer: "phase", input: "refactoring", expected: "refactoring" },
  { normalizer: "priority", input: "architecturecleanup", expected: "architecturecleanup" },
  { normalizer: "brief_type", input: "architecturecleanup", expected: "Architecture" },
  { normalizer: "phase", input: "architecturecleanup", expected: "architecturecleanup" },
  { normalizer: "priority", input: "dependencyupdate", expected: "dependencyupdate" },
  { normalizer: "brief_type", input: "dependencyupdate", expected: "Dependency Update" },
  { normalizer: "phase", input: "dependencyupdate", expected: "dependencyupdate" },
  { normalizer: "priority", input: "doc", expected: "doc" },
  { normalizer: "brief_type", input: "doc", expected: "Documentation" },
  { normalizer: "phase", input: "doc", expected: "doc" },
  { normalizer: "priority", input: "test", expected: "test" },
  { normalizer: "brief_type", input: "test", expected: "Testing" },
  { normalizer: "phase", input: "test", expected: "test" },
  { normalizer: "priority", input: "process", expected: "process" },
  { normalizer: "brief_type", input: "process", expected: "Process Improvement" },
  { normalizer: "phase", input: "process", expected: "process" },
  { normalizer: "priority", input: "release", expected: "release" },
  { normalizer: "brief_type", input: "release", expected: "Process Improvement" },
  { normalizer: "phase", input: "release", expected: "release" },
  { normalizer: "priority", input: "", expected: null },
  { normalizer: "brief_type", input: "", expected: null },
  { normalizer: "phase", input: "", expected: null },
  { normalizer: "priority", input: "   ", expected: null },
  { normalizer: "brief_type", input: "   ", expected: null },
  { normalizer: "phase", input: "   ", expected: null },
  { normalizer: "priority", input: "Unset", expected: null },
  { normalizer: "brief_type", input: "Unset", expected: "Unset" },
  { normalizer: "phase", input: "Unset", expected: "Unset" },
  { normalizer: "priority", input: "UNSET", expected: null },
  { normalizer: "brief_type", input: "UNSET", expected: "UNSET" },
  { normalizer: "phase", input: "UNSET", expected: "UNSET" },
  { normalizer: "priority", input: "P0", expected: "P0-Critical" },
  { normalizer: "brief_type", input: "P0", expected: "P0" },
  { normalizer: "phase", input: "P0", expected: "P0" },
  { normalizer: "priority", input: "P1", expected: "P1-High" },
  { normalizer: "brief_type", input: "P1", expected: "P1" },
  { normalizer: "phase", input: "P1", expected: "P1" },
  { normalizer: "priority", input: "P2", expected: "P2-Medium" },
  { normalizer: "brief_type", input: "P2", expected: "P2" },
  { normalizer: "phase", input: "P2", expected: "P2" },
  { normalizer: "priority", input: "P3", expected: "P3-Low" },
  { normalizer: "brief_type", input: "P3", expected: "P3" },
  { normalizer: "phase", input: "P3", expected: "P3" },
  { normalizer: "priority", input: " P1 ", expected: "P1-High" },
  { normalizer: "brief_type", input: " P1 ", expected: " P1 " },
  { normalizer: "phase", input: " P1 ", expected: " P1 " },
  { normalizer: "priority", input: "P1 - High", expected: "P1-High" },
  { normalizer: "brief_type", input: "P1 - High", expected: "P1 - High" },
  { normalizer: "phase", input: "P1 - High", expected: "P1 - High" },
  { normalizer: "priority", input: "P4-Trivial", expected: "P4-Trivial" },
  { normalizer: "brief_type", input: "P4-Trivial", expected: "P4-Trivial" },
  { normalizer: "phase", input: "P4-Trivial", expected: "P4-Trivial" },
  { normalizer: "priority", input: "Spike", expected: "Spike" },
  { normalizer: "brief_type", input: "Spike", expected: "Spike" },
  { normalizer: "phase", input: "Spike", expected: "Spike" },
  { normalizer: "priority", input: "Investigation", expected: "Investigation" },
  { normalizer: "brief_type", input: "Investigation", expected: "Investigation" },
  { normalizer: "phase", input: "Investigation", expected: "Investigation" },
  { normalizer: "priority", input: "Bug/Feature", expected: "Bug/Feature" },
  { normalizer: "brief_type", input: "Bug/Feature", expected: "Bug/Feature" },
  { normalizer: "phase", input: "Bug/Feature", expected: "Bug/Feature" },
  { normalizer: "priority", input: "Bug Fix / Compliance", expected: "Bug Fix / Compliance" },
  { normalizer: "brief_type", input: "Bug Fix / Compliance", expected: "Bug Fix / Compliance" },
  { normalizer: "phase", input: "Bug Fix / Compliance", expected: "Bug Fix / Compliance" },
  { normalizer: "priority", input: "building", expected: "building" },
  { normalizer: "brief_type", input: "building", expected: "building" },
  { normalizer: "phase", input: "building", expected: "BUILDING" },
  { normalizer: "priority", input: "Deferred", expected: "Deferred" },
  { normalizer: "brief_type", input: "Deferred", expected: "Deferred" },
  { normalizer: "phase", input: "Deferred", expected: "Deferred" },
  { normalizer: "priority", input: "SUPERSEDED-BY-FR-201", expected: "SUPERSEDED-BY-FR-201" },
  { normalizer: "brief_type", input: "SUPERSEDED-BY-FR-201", expected: "SUPERSEDED-BY-FR-201" },
  { normalizer: "phase", input: "SUPERSEDED-BY-FR-201", expected: "SUPERSEDED-BY-FR-201" },
  { normalizer: "priority", input: "technical debt", expected: "technical debt" },
  { normalizer: "brief_type", input: "technical debt", expected: "Technical Debt" },
  { normalizer: "phase", input: "technical debt", expected: "technical debt" },
  { normalizer: "priority", input: "TECH DEBT", expected: "TECH DEBT" },
  { normalizer: "brief_type", input: "TECH DEBT", expected: "Technical Debt" },
  { normalizer: "phase", input: "TECH DEBT", expected: "TECH DEBT" },
];

/** One replayable canonicality fixture: `isCanonical<X>(input) === expected`. */
export interface PredicateFixture {
  normalizer: SyncNormalizerId;
  input: string;
  expected: boolean;
}

/**
 * Canonicality verdicts computed by the BRAIN's real predicates at generation
 * time. These decide whether a passed-through value is REPORTED, so they are
 * behaviour, not data.
 */
export const PREDICATE_FIXTURES: readonly PredicateFixture[] = [
  { normalizer: "priority", input: "P0-Critical", expected: true },
  { normalizer: "brief_type", input: "P0-Critical", expected: false },
  { normalizer: "phase", input: "P0-Critical", expected: false },
  { normalizer: "priority", input: "P1-High", expected: true },
  { normalizer: "brief_type", input: "P1-High", expected: false },
  { normalizer: "phase", input: "P1-High", expected: false },
  { normalizer: "priority", input: "P2-Medium", expected: true },
  { normalizer: "brief_type", input: "P2-Medium", expected: false },
  { normalizer: "phase", input: "P2-Medium", expected: false },
  { normalizer: "priority", input: "P3-Low", expected: true },
  { normalizer: "brief_type", input: "P3-Low", expected: false },
  { normalizer: "phase", input: "P3-Low", expected: false },
  { normalizer: "priority", input: "INIT", expected: false },
  { normalizer: "brief_type", input: "INIT", expected: false },
  { normalizer: "phase", input: "INIT", expected: true },
  { normalizer: "priority", input: "PLANNING", expected: false },
  { normalizer: "brief_type", input: "PLANNING", expected: false },
  { normalizer: "phase", input: "PLANNING", expected: true },
  { normalizer: "priority", input: "APPROVAL", expected: false },
  { normalizer: "brief_type", input: "APPROVAL", expected: false },
  { normalizer: "phase", input: "APPROVAL", expected: true },
  { normalizer: "priority", input: "BUILDING", expected: false },
  { normalizer: "brief_type", input: "BUILDING", expected: false },
  { normalizer: "phase", input: "BUILDING", expected: true },
  { normalizer: "priority", input: "TESTING", expected: false },
  { normalizer: "brief_type", input: "TESTING", expected: true },
  { normalizer: "phase", input: "TESTING", expected: true },
  { normalizer: "priority", input: "REVIEWING", expected: false },
  { normalizer: "brief_type", input: "REVIEWING", expected: false },
  { normalizer: "phase", input: "REVIEWING", expected: true },
  { normalizer: "priority", input: "DOCUMENTING", expected: false },
  { normalizer: "brief_type", input: "DOCUMENTING", expected: false },
  { normalizer: "phase", input: "DOCUMENTING", expected: true },
  { normalizer: "priority", input: "COMMITTING", expected: false },
  { normalizer: "brief_type", input: "COMMITTING", expected: false },
  { normalizer: "phase", input: "COMMITTING", expected: true },
  { normalizer: "priority", input: "COMPLETE", expected: false },
  { normalizer: "brief_type", input: "COMPLETE", expected: false },
  { normalizer: "phase", input: "COMPLETE", expected: true },
  { normalizer: "priority", input: "BLOCKED", expected: false },
  { normalizer: "brief_type", input: "BLOCKED", expected: false },
  { normalizer: "phase", input: "BLOCKED", expected: true },
  { normalizer: "priority", input: "Feature", expected: false },
  { normalizer: "brief_type", input: "Feature", expected: true },
  { normalizer: "phase", input: "Feature", expected: false },
  { normalizer: "priority", input: "Bug", expected: false },
  { normalizer: "brief_type", input: "Bug", expected: true },
  { normalizer: "phase", input: "Bug", expected: false },
  { normalizer: "priority", input: "Migration", expected: false },
  { normalizer: "brief_type", input: "Migration", expected: true },
  { normalizer: "phase", input: "Migration", expected: false },
  { normalizer: "priority", input: "Technical Debt", expected: false },
  { normalizer: "brief_type", input: "Technical Debt", expected: true },
  { normalizer: "phase", input: "Technical Debt", expected: false },
  { normalizer: "priority", input: "Testing", expected: false },
  { normalizer: "brief_type", input: "Testing", expected: true },
  { normalizer: "phase", input: "Testing", expected: true },
  { normalizer: "priority", input: "Process Improvement", expected: false },
  { normalizer: "brief_type", input: "Process Improvement", expected: true },
  { normalizer: "phase", input: "Process Improvement", expected: false },
  { normalizer: "priority", input: "Documentation", expected: false },
  { normalizer: "brief_type", input: "Documentation", expected: true },
  { normalizer: "phase", input: "Documentation", expected: false },
  { normalizer: "priority", input: "Acceptance", expected: false },
  { normalizer: "brief_type", input: "Acceptance", expected: true },
  { normalizer: "phase", input: "Acceptance", expected: false },
  { normalizer: "priority", input: "Performance", expected: false },
  { normalizer: "brief_type", input: "Performance", expected: true },
  { normalizer: "phase", input: "Performance", expected: false },
  { normalizer: "priority", input: "Architecture", expected: false },
  { normalizer: "brief_type", input: "Architecture", expected: true },
  { normalizer: "phase", input: "Architecture", expected: false },
  { normalizer: "priority", input: "Dependency Update", expected: false },
  { normalizer: "brief_type", input: "Dependency Update", expected: true },
  { normalizer: "phase", input: "Dependency Update", expected: false },
  { normalizer: "priority", input: "Refactor", expected: false },
  { normalizer: "brief_type", input: "Refactor", expected: true },
  { normalizer: "phase", input: "Refactor", expected: false },
  { normalizer: "priority", input: "p0", expected: false },
  { normalizer: "brief_type", input: "p0", expected: false },
  { normalizer: "phase", input: "p0", expected: false },
  { normalizer: "priority", input: "p1", expected: false },
  { normalizer: "brief_type", input: "p1", expected: false },
  { normalizer: "phase", input: "p1", expected: false },
  { normalizer: "priority", input: "p2", expected: false },
  { normalizer: "brief_type", input: "p2", expected: false },
  { normalizer: "phase", input: "p2", expected: false },
  { normalizer: "priority", input: "p3", expected: false },
  { normalizer: "brief_type", input: "p3", expected: false },
  { normalizer: "phase", input: "p3", expected: false },
  { normalizer: "priority", input: "p0 - critical", expected: false },
  { normalizer: "brief_type", input: "p0 - critical", expected: false },
  { normalizer: "phase", input: "p0 - critical", expected: false },
  { normalizer: "priority", input: "p1 - high", expected: false },
  { normalizer: "brief_type", input: "p1 - high", expected: false },
  { normalizer: "phase", input: "p1 - high", expected: false },
  { normalizer: "priority", input: "p2 - medium", expected: false },
  { normalizer: "brief_type", input: "p2 - medium", expected: false },
  { normalizer: "phase", input: "p2 - medium", expected: false },
  { normalizer: "priority", input: "p3 - low", expected: false },
  { normalizer: "brief_type", input: "p3 - low", expected: false },
  { normalizer: "phase", input: "p3 - low", expected: false },
  { normalizer: "priority", input: "p0-critical", expected: false },
  { normalizer: "brief_type", input: "p0-critical", expected: false },
  { normalizer: "phase", input: "p0-critical", expected: false },
  { normalizer: "priority", input: "p1-high", expected: false },
  { normalizer: "brief_type", input: "p1-high", expected: false },
  { normalizer: "phase", input: "p1-high", expected: false },
  { normalizer: "priority", input: "p2-medium", expected: false },
  { normalizer: "brief_type", input: "p2-medium", expected: false },
  { normalizer: "phase", input: "p2-medium", expected: false },
  { normalizer: "priority", input: "p3-low", expected: false },
  { normalizer: "brief_type", input: "p3-low", expected: false },
  { normalizer: "phase", input: "p3-low", expected: false },
  { normalizer: "priority", input: "tech debt", expected: false },
  { normalizer: "brief_type", input: "tech debt", expected: false },
  { normalizer: "phase", input: "tech debt", expected: false },
  { normalizer: "priority", input: "td", expected: false },
  { normalizer: "brief_type", input: "td", expected: false },
  { normalizer: "phase", input: "td", expected: false },
  { normalizer: "priority", input: "debt", expected: false },
  { normalizer: "brief_type", input: "debt", expected: false },
  { normalizer: "phase", input: "debt", expected: false },
  { normalizer: "priority", input: "techdebt", expected: false },
  { normalizer: "brief_type", input: "techdebt", expected: false },
  { normalizer: "phase", input: "techdebt", expected: false },
  { normalizer: "priority", input: "technicaldebt", expected: false },
  { normalizer: "brief_type", input: "technicaldebt", expected: false },
  { normalizer: "phase", input: "technicaldebt", expected: false },
  { normalizer: "priority", input: "tech_debt", expected: false },
  { normalizer: "brief_type", input: "tech_debt", expected: false },
  { normalizer: "phase", input: "tech_debt", expected: false },
  { normalizer: "priority", input: "tech-debt", expected: false },
  { normalizer: "brief_type", input: "tech-debt", expected: false },
  { normalizer: "phase", input: "tech-debt", expected: false },
  { normalizer: "priority", input: "chore", expected: false },
  { normalizer: "brief_type", input: "chore", expected: false },
  { normalizer: "phase", input: "chore", expected: false },
  { normalizer: "priority", input: "bug fix", expected: false },
  { normalizer: "brief_type", input: "bug fix", expected: false },
  { normalizer: "phase", input: "bug fix", expected: false },
  { normalizer: "priority", input: "bugfix", expected: false },
  { normalizer: "brief_type", input: "bugfix", expected: false },
  { normalizer: "phase", input: "bugfix", expected: false },
  { normalizer: "priority", input: "fr", expected: false },
  { normalizer: "brief_type", input: "fr", expected: false },
  { normalizer: "phase", input: "fr", expected: false },
  { normalizer: "priority", input: "feature request", expected: false },
  { normalizer: "brief_type", input: "feature request", expected: false },
  { normalizer: "phase", input: "feature request", expected: false },
  { normalizer: "priority", input: "featurerequest", expected: false },
  { normalizer: "brief_type", input: "featurerequest", expected: false },
  { normalizer: "phase", input: "featurerequest", expected: false },
  { normalizer: "priority", input: "enhancement", expected: false },
  { normalizer: "brief_type", input: "enhancement", expected: false },
  { normalizer: "phase", input: "enhancement", expected: false },
  { normalizer: "priority", input: "feature enhancement", expected: false },
  { normalizer: "brief_type", input: "feature enhancement", expected: false },
  { normalizer: "phase", input: "feature enhancement", expected: false },
  { normalizer: "priority", input: "refactoring", expected: false },
  { normalizer: "brief_type", input: "refactoring", expected: false },
  { normalizer: "phase", input: "refactoring", expected: false },
  { normalizer: "priority", input: "architecturecleanup", expected: false },
  { normalizer: "brief_type", input: "architecturecleanup", expected: false },
  { normalizer: "phase", input: "architecturecleanup", expected: false },
  { normalizer: "priority", input: "dependencyupdate", expected: false },
  { normalizer: "brief_type", input: "dependencyupdate", expected: false },
  { normalizer: "phase", input: "dependencyupdate", expected: false },
  { normalizer: "priority", input: "doc", expected: false },
  { normalizer: "brief_type", input: "doc", expected: false },
  { normalizer: "phase", input: "doc", expected: false },
  { normalizer: "priority", input: "test", expected: false },
  { normalizer: "brief_type", input: "test", expected: false },
  { normalizer: "phase", input: "test", expected: false },
  { normalizer: "priority", input: "process", expected: false },
  { normalizer: "brief_type", input: "process", expected: false },
  { normalizer: "phase", input: "process", expected: false },
  { normalizer: "priority", input: "release", expected: false },
  { normalizer: "brief_type", input: "release", expected: false },
  { normalizer: "phase", input: "release", expected: false },
  { normalizer: "priority", input: "", expected: false },
  { normalizer: "brief_type", input: "", expected: false },
  { normalizer: "phase", input: "", expected: false },
  { normalizer: "priority", input: "   ", expected: false },
  { normalizer: "brief_type", input: "   ", expected: false },
  { normalizer: "phase", input: "   ", expected: false },
  { normalizer: "priority", input: "Unset", expected: false },
  { normalizer: "brief_type", input: "Unset", expected: false },
  { normalizer: "phase", input: "Unset", expected: false },
  { normalizer: "priority", input: "UNSET", expected: false },
  { normalizer: "brief_type", input: "UNSET", expected: false },
  { normalizer: "phase", input: "UNSET", expected: false },
  { normalizer: "priority", input: "P0", expected: false },
  { normalizer: "brief_type", input: "P0", expected: false },
  { normalizer: "phase", input: "P0", expected: false },
  { normalizer: "priority", input: "P1", expected: false },
  { normalizer: "brief_type", input: "P1", expected: false },
  { normalizer: "phase", input: "P1", expected: false },
  { normalizer: "priority", input: "P2", expected: false },
  { normalizer: "brief_type", input: "P2", expected: false },
  { normalizer: "phase", input: "P2", expected: false },
  { normalizer: "priority", input: "P3", expected: false },
  { normalizer: "brief_type", input: "P3", expected: false },
  { normalizer: "phase", input: "P3", expected: false },
  { normalizer: "priority", input: " P1 ", expected: false },
  { normalizer: "brief_type", input: " P1 ", expected: false },
  { normalizer: "phase", input: " P1 ", expected: false },
  { normalizer: "priority", input: "P1 - High", expected: false },
  { normalizer: "brief_type", input: "P1 - High", expected: false },
  { normalizer: "phase", input: "P1 - High", expected: false },
  { normalizer: "priority", input: "P4-Trivial", expected: false },
  { normalizer: "brief_type", input: "P4-Trivial", expected: false },
  { normalizer: "phase", input: "P4-Trivial", expected: false },
  { normalizer: "priority", input: "Spike", expected: false },
  { normalizer: "brief_type", input: "Spike", expected: false },
  { normalizer: "phase", input: "Spike", expected: false },
  { normalizer: "priority", input: "Investigation", expected: false },
  { normalizer: "brief_type", input: "Investigation", expected: false },
  { normalizer: "phase", input: "Investigation", expected: false },
  { normalizer: "priority", input: "Bug/Feature", expected: false },
  { normalizer: "brief_type", input: "Bug/Feature", expected: false },
  { normalizer: "phase", input: "Bug/Feature", expected: false },
  { normalizer: "priority", input: "Bug Fix / Compliance", expected: false },
  { normalizer: "brief_type", input: "Bug Fix / Compliance", expected: false },
  { normalizer: "phase", input: "Bug Fix / Compliance", expected: false },
  { normalizer: "priority", input: "building", expected: false },
  { normalizer: "brief_type", input: "building", expected: false },
  { normalizer: "phase", input: "building", expected: true },
  { normalizer: "priority", input: "Deferred", expected: false },
  { normalizer: "brief_type", input: "Deferred", expected: false },
  { normalizer: "phase", input: "Deferred", expected: false },
  { normalizer: "priority", input: "SUPERSEDED-BY-FR-201", expected: false },
  { normalizer: "brief_type", input: "SUPERSEDED-BY-FR-201", expected: false },
  { normalizer: "phase", input: "SUPERSEDED-BY-FR-201", expected: false },
  { normalizer: "priority", input: "technical debt", expected: false },
  { normalizer: "brief_type", input: "technical debt", expected: true },
  { normalizer: "phase", input: "technical debt", expected: false },
  { normalizer: "priority", input: "TECH DEBT", expected: false },
  { normalizer: "brief_type", input: "TECH DEBT", expected: false },
  { normalizer: "phase", input: "TECH DEBT", expected: false },
];

/**
 * One replayable ROW-level fixture — the whole `normalizeSyncRow` contract
 * for one input: what is stored, what folded, what was reported, and whether
 * the INPUT object was returned unchanged.
 */
export interface SyncRowFixture {
  table: string;
  row: Record<string, unknown>;
  expectedRow: Record<string, unknown>;
  expectedFolds: SyncFieldFold[];
  expectedNonCanonical: SyncFieldPassthrough[];
  expectedSameObject: boolean;
}

/**
 * Row-level outcomes computed by running the BRAIN's real `normalizeSyncRow`
 * at generation time. `normalizeSyncRow` is AUTHORED template text in the
 * builder, not derived from the source, so a byte-parity test cannot see a
 * brain-side edit to it — these fixtures are what makes the mirror
 * behavioural for the function both mergeRows copies actually call.
 *
 * At least one row carries a FOLDABLE-LOOKING `updated_at`, so a fold that
 * ever reached the LWW comparison column diverges here immediately.
 */
export const SYNC_ROW_FIXTURES: readonly SyncRowFixture[] = [
  { table: "brief_status", row: {"project":"moca-ai-agent","brief_id":"BR-045","brief_type":"TD","title":"HR read tools on mocasmart-mcp","status":"Done","priority":"P2","effort":"L-Large","phase":"building","updated_at":"2026-08-04 00:00:00"}, expectedRow: {"project":"moca-ai-agent","brief_id":"BR-045","brief_type":"Technical Debt","title":"HR read tools on mocasmart-mcp","status":"Done","priority":"P2-Medium","effort":"L-Large","phase":"BUILDING","updated_at":"2026-08-04 00:00:00"}, expectedFolds: [{"field":"brief_type","from":"TD","to":"Technical Debt"},{"field":"priority","from":"P2","to":"P2-Medium"},{"field":"phase","from":"building","to":"BUILDING"}], expectedNonCanonical: [], expectedSameObject: false },
  { table: "brief_status", row: {"project":"p","brief_id":"ARM-1","priority":"P1","updated_at":"P2"}, expectedRow: {"project":"p","brief_id":"ARM-1","priority":"P1-High","updated_at":"P2"}, expectedFolds: [{"field":"priority","from":"P1","to":"P1-High"}], expectedNonCanonical: [], expectedSameObject: false },
  { table: "brief_status", row: {"project":"p","brief_id":"ARM-2","priority":"P1-High","updated_at":"P2"}, expectedRow: {"project":"p","brief_id":"ARM-2","priority":"P1-High","updated_at":"P2"}, expectedFolds: [], expectedNonCanonical: [], expectedSameObject: true },
  { table: "brief_status", row: {"project":"p","brief_id":"CLEAN-1","brief_type":"Technical Debt","priority":"P2-Medium","phase":"COMPLETE","updated_at":"2026-08-04 00:00:00"}, expectedRow: {"project":"p","brief_id":"CLEAN-1","brief_type":"Technical Debt","priority":"P2-Medium","phase":"COMPLETE","updated_at":"2026-08-04 00:00:00"}, expectedFolds: [], expectedNonCanonical: [], expectedSameObject: true },
  { table: "brief_status", row: {"project":"p","brief_id":"UNK-1","brief_type":"Spike","priority":"P4-Trivial","phase":"Deferred","updated_at":"2026-08-04 00:00:00"}, expectedRow: {"project":"p","brief_id":"UNK-1","brief_type":"Spike","priority":"P4-Trivial","phase":"Deferred","updated_at":"2026-08-04 00:00:00"}, expectedFolds: [], expectedNonCanonical: [{"field":"brief_type","value":"Spike"},{"field":"priority","value":"P4-Trivial"},{"field":"phase","value":"Deferred"}], expectedSameObject: true },
  { table: "brief_status", row: {"project":"p","brief_id":"UNSET-1","priority":"","phase":"   ","updated_at":"x"}, expectedRow: {"project":"p","brief_id":"UNSET-1","priority":null,"phase":null,"updated_at":"x"}, expectedFolds: [{"field":"priority","from":"","to":null},{"field":"phase","from":"   ","to":null}], expectedNonCanonical: [], expectedSameObject: false },
  { table: "brief_status", row: {"project":"p","brief_id":"UNSET-2","priority":"Unset"}, expectedRow: {"project":"p","brief_id":"UNSET-2","priority":null}, expectedFolds: [{"field":"priority","from":"Unset","to":null}], expectedNonCanonical: [], expectedSameObject: false },
  { table: "brief_status", row: {"project":"p","brief_id":"NULL-1","brief_type":null,"priority":null,"phase":null}, expectedRow: {"project":"p","brief_id":"NULL-1","brief_type":null,"priority":null,"phase":null}, expectedFolds: [], expectedNonCanonical: [], expectedSameObject: true },
  { table: "brief_status", row: {"project":"p","brief_id":"SPARSE-1","updated_at":"ts"}, expectedRow: {"project":"p","brief_id":"SPARSE-1","updated_at":"ts"}, expectedFolds: [], expectedNonCanonical: [], expectedSameObject: true },
  { table: "brief_status", row: {"project":"p","brief_id":"TYPE-1","priority":7,"phase":false,"brief_type":"td"}, expectedRow: {"project":"p","brief_id":"TYPE-1","priority":7,"phase":false,"brief_type":"Technical Debt"}, expectedFolds: [{"field":"brief_type","from":"td","to":"Technical Debt"}], expectedNonCanonical: [], expectedSameObject: false },
  { table: "brief_status", row: {"project":"p","brief_id":"MIX-1","brief_type":"Feature Request","priority":"P4-Trivial","phase":"COMPLETE","updated_at":"2026-08-04 00:00:00"}, expectedRow: {"project":"p","brief_id":"MIX-1","brief_type":"Feature","priority":"P4-Trivial","phase":"COMPLETE","updated_at":"2026-08-04 00:00:00"}, expectedFolds: [{"field":"brief_type","from":"Feature Request","to":"Feature"}], expectedNonCanonical: [{"field":"priority","value":"P4-Trivial"}], expectedSameObject: false },
  { table: "learnings", row: {"project":"p","title":"P2","content":"TD","phase":"building","updated_at":"P2"}, expectedRow: {"project":"p","title":"P2","content":"TD","phase":"building","updated_at":"P2"}, expectedFolds: [], expectedNonCanonical: [], expectedSameObject: true },
  { table: "not_a_sync_table", row: {"priority":"P2"}, expectedRow: {"priority":"P2"}, expectedFolds: [], expectedNonCanonical: [], expectedSameObject: true },
];
