#!/bin/bash

# Description: CI-style drift guard for agent-prompt harness files. For every
#              agent/target in the manifest, compares the harness body against
#              the canonical prompt body (sha + version marker). Exits non-zero
#              if ANY harness is out-of-sync (TD-021).
# Usage: check_harness_drift.sh --project-root <dir> [--manifest <path>] [--overlay <path>] [--filter <name-glob>]
#   --project-root <dir>  - REQUIRED. Root that manifest paths resolve against.
#   --manifest <path>     - Manifest file. Default: <project-root>/
#                           harness-manifest.json (FR-136: each project ships
#                           its own data manifest).
#   --overlay <path>      - OPTIONAL Layer-2 personal-overlay manifest merged
#                           into the base before flatten (FR-136 base+overlay
#                           seam). Default: auto-discover
#                           <brain>/registry/harness-manifest.personal.json.
#   --filter <name-glob>  - Only check agents whose name matches the glob.
# Dependencies: python3, _common.sh (auto-sourced from script dir)
# Exit codes:
#   0 - All checked harness targets are in sync with canonical
#   1 - One or more harness targets DRIFTED or MISSING
#   2 - Usage error (bad/missing arguments)
#
# The report is self-evidencing in the spirit of verify_mirror.sh: for every
# target it prints the canonical body sha, the harness body sha, both version
# markers, and a per-target verdict (MATCH / DRIFTED / MISSING). The exit code
# cannot be misread as PASS unless every target shows MATCH.
#
# CODEX TARGETS: the harness body for codex is the decoded
# `developer_instructions` value from the TOML. The leading GENERATED-MARKER
# comment is not part of that value, so it does not affect the sha compare.
#
# FR-137 SKILLS SURFACE: after the agent loop, the guard also drift-checks the
# surfaces.skills targets (codex AGENTS.md compiler, gemini per-skill TOML
# converter). The canonical-deriver for skills IS the md_to_* compiler — there
# is no separate "canonical body" — so the guard re-derives to a temp file and
# compares against on-disk. For the AGENTS.md compiler target the trailing
# date-stamped GENERATED-MARKER line is STRIPPED before sha so the verdict is
# date-stable across days (FR-137 D-4 idempotency snag, option a).

set -euo pipefail

# ---------------------------------------------------------------------------
# Locate the adapter directory and shared helpers.
# ---------------------------------------------------------------------------
ADAPTER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# shellcheck source=_common.sh
source "$ADAPTER_DIR/_common.sh"

readonly SCHEMA="$ADAPTER_DIR/manifest.schema.json"
# FR-137: core-owned skills surface declaration, unioned with the merged agent
# manifest's surfaces (mirrors compile_harnesses.sh).
readonly CORE_SURFACES="$ADAPTER_DIR/surfaces-manifest.json"
# The known prefix of the date-stamped trailing marker emitted by
# md_to_agents_md.sh; stripped before sha so skills drift is date-stable.
readonly AGENTS_MD_MARKER_PREFIX="<!-- Generated by igris cli-adapter md_to_agents_md.sh"

# Resolve the runtime brain dir (IGRIS_BRAIN_DIR, else ~/.igris) to locate the
# OPTIONAL personal overlay (FR-139 seam) under <brain>/registry/.
BRAIN_DIR="${IGRIS_BRAIN_DIR:-$HOME/.igris}"
readonly DEFAULT_OVERLAY="$BRAIN_DIR/registry/harness-manifest.personal.json"

# ---------------------------------------------------------------------------
# usage — prints usage and exits with code 2.
# ---------------------------------------------------------------------------
usage() {
  echo "Usage: $0 --project-root <dir> [--manifest <path>] [--overlay <path>] [--filter <name-glob>]" >&2
  echo "" >&2
  echo "Fails (exit 1) if any harness file has drifted from its canonical prompt." >&2
  exit 2
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
PROJECT_ROOT=""
MANIFEST=""
OVERLAY=""
OVERLAY_SET=0
FILTER='*'

while [ "$#" -gt 0 ]; do
  case "$1" in
    --project-root)
      PROJECT_ROOT="${2:-}"
      shift 2 || usage
      ;;
    --manifest)
      MANIFEST="${2:-}"
      shift 2 || usage
      ;;
    --overlay)
      OVERLAY="${2:-}"
      OVERLAY_SET=1
      shift 2 || usage
      ;;
    --filter)
      FILTER="${2:-}"
      shift 2 || usage
      ;;
    --help|-h)
      usage
      ;;
    *)
      echo "Error: unknown argument '$1'" >&2
      usage
      ;;
  esac
done

if [ -z "$PROJECT_ROOT" ]; then
  echo "Error: --project-root is required" >&2
  usage
fi
if [ ! -d "$PROJECT_ROOT" ]; then
  echo "Error: project root '$PROJECT_ROOT' is not a directory" >&2
  exit 1
fi

PROJECT_ROOT="$( cd "$PROJECT_ROOT" && pwd )"

# FR-136 manifest resolution: default to <project-root>/harness-manifest.json,
# NO fallback to the old next-to-script location. Fail clearly if absent.
if [ -z "$MANIFEST" ]; then
  MANIFEST="$PROJECT_ROOT/harness-manifest.json"
fi
if [ ! -f "$MANIFEST" ]; then
  echo "Error: harness manifest not found at $MANIFEST; pass --manifest <path>" >&2
  exit 1
fi

# FR-136 overlay resolution (explicit --overlay wins, else auto-discover).
if [ "$OVERLAY_SET" -eq 0 ]; then
  if [ -f "$DEFAULT_OVERLAY" ]; then
    OVERLAY="$DEFAULT_OVERLAY"
  else
    OVERLAY=""
  fi
elif [ -n "$OVERLAY" ] && [ ! -f "$OVERLAY" ]; then
  echo "Error: overlay manifest not found at $OVERLAY" >&2
  exit 1
fi

# Validate base (+ overlay) against the schema; never no-ops.
if ! validate_manifest "$MANIFEST" "$SCHEMA"; then
  exit 1
fi
if [ -n "$OVERLAY" ] && ! validate_manifest "$OVERLAY" "$SCHEMA"; then
  exit 1
fi

# Merge base + optional personal overlay (collision = hard error).
MERGED_MANIFEST="$MANIFEST"
TMP_MERGED=""
if [ -n "$OVERLAY" ]; then
  TMP_MERGED="$(mktemp "${TMPDIR:-/tmp}/igris-harness-merged.XXXXXX.json")"
  trap 'rm -f "$TMP_MERGED"' EXIT
  if ! merge_overlay_manifest "$MANIFEST" "$OVERLAY" > "$TMP_MERGED"; then
    exit 1
  fi
  MERGED_MANIFEST="$TMP_MERGED"
fi

# ---------------------------------------------------------------------------
# canonical_body_with_exception <canonical-md> <exception-json-or-empty>
#
# Emits the canonical body, with the documented body-exception appendix
# inserted when an exception sidecar is supplied. This is the exact body the
# corresponding harness is expected to carry.
# ---------------------------------------------------------------------------
canonical_body_with_exception() {
  local canonical="$1"
  local exception="$2"
  local body
  body=$(strip_frontmatter "$canonical")
  if [ -z "$exception" ]; then
    printf '%s' "$body"
    return 0
  fi
  python3 - "$body" "$exception" <<'PY'
import json
import sys

body = sys.argv[1]
with open(sys.argv[2], "r", encoding="utf-8") as fh:
    exc = json.load(fh)
anchor = exc["anchor"]
insert_lines = exc["insert"]
lines = body.splitlines()
matches = [i for i, ln in enumerate(lines) if ln.strip() == anchor.strip()]
if len(matches) != 1:
    sys.stderr.write(
        f"Error: body-exception anchor matched {len(matches)} lines\n"
    )
    sys.exit(1)
idx = matches[0]
lines = lines[: idx + 1] + insert_lines + lines[idx + 1 :]
sys.stdout.write("\n".join(lines))
PY
}

# ---------------------------------------------------------------------------
# sha_of_string <string>  — sha256 of a literal string (no file needed).
# ---------------------------------------------------------------------------
sha_of_string() {
  python3 - "$1" <<'PY'
import hashlib
import sys
print(hashlib.sha256(sys.argv[1].encode("utf-8")).hexdigest())
PY
}

# ---------------------------------------------------------------------------
# codex_body <toml-path>  — decode developer_instructions from a codex TOML.
# Emits empty + returns 1 if the file is missing or unparseable.
# ---------------------------------------------------------------------------
codex_body() {
  local toml_path="$1"
  if [ ! -f "$toml_path" ]; then
    return 1
  fi
  python3 - "$toml_path" <<'PY'
import sys
try:
    import tomllib
except ImportError:  # python < 3.11
    sys.exit(2)
try:
    with open(sys.argv[1], "rb") as fh:
        data = tomllib.load(fh)
except Exception:
    sys.exit(1)
val = data.get("developer_instructions")
if val is None:
    sys.exit(1)
sys.stdout.write(val)
PY
}

# ---------------------------------------------------------------------------
# Flatten the manifest into work rows (same column layout as
# compile_harnesses.sh; `-` is the empty-body-exception sentinel).
# ---------------------------------------------------------------------------
WORK_ROWS=$(python3 - "$MERGED_MANIFEST" "$FILTER" <<'PY'
import fnmatch
import json
import sys

with open(sys.argv[1], "r", encoding="utf-8") as fh:
    manifest = json.load(fh)
name_filter = sys.argv[2]

for agent in manifest.get("agents", []):
    name = agent["name"]
    if not fnmatch.fnmatch(name, name_filter):
        continue
    canon = agent["canonical"]
    versioned = "1" if canon.get("versioned") else "0"
    canon_dir = canon["dir"]
    canon_ref = canon.get("glob", "") if canon.get("versioned") else canon.get("file", "")
    body_exc = agent.get("body_exception", "") or "-"
    for target in agent.get("targets", []):
        print("\t".join([
            name, versioned, canon_dir, canon_ref, body_exc,
            target["type"], target["path"],
        ]))
PY
)

# ---------------------------------------------------------------------------
# Check each work row. Accumulators span BOTH the agents surface (this loop)
# and the skills surface (the FR-137 pass below).
# ---------------------------------------------------------------------------
TOTAL=0
MATCH=0
DRIFT=0

echo "Harness drift check (project root: $PROJECT_ROOT):"
echo ""

if [ -n "$WORK_ROWS" ]; then
while IFS=$'\t' read -r name versioned canon_dir canon_ref body_exc ttype target_path; do
  [ -z "$name" ] && continue
  TOTAL=$((TOTAL + 1))

  # Resolve canonical. An absolute or `~`-prefixed canon_dir is used verbatim
  # (FR-142 copy-vendor points canonical.dir at the vendored copy under
  # ~/.igris/registry/<name>/); a relative dir is project-relative. Mirrors the
  # canonical resolution in compile_harnesses.sh.
  case "$canon_dir" in
    "~"/*) canon_base="$HOME/${canon_dir#"~/"}" ;;
    /*)    canon_base="$canon_dir" ;;
    *)     canon_base="$PROJECT_ROOT/$canon_dir" ;;
  esac

  # Resolve canonical.
  canon_abs=""
  if [ "$versioned" = "1" ]; then
    if ! canon_abs=$(latest_canonical "$canon_base" "$canon_ref"); then
      echo "  [$name/$ttype] MISSING — no canonical match for '$canon_ref' in $canon_dir"
      DRIFT=$((DRIFT + 1))
      continue
    fi
  else
    canon_abs="$canon_base/$canon_ref"
    if [ ! -f "$canon_abs" ]; then
      echo "  [$name/$ttype] MISSING — canonical file absent: $canon_abs"
      DRIFT=$((DRIFT + 1))
      continue
    fi
  fi

  # Resolve the body-exception sidecar.
  exc_abs=""
  if [ -n "$body_exc" ] && [ "$body_exc" != "-" ]; then
    exc_abs="$ADAPTER_DIR/body-exceptions/$body_exc.json"
    if [ ! -f "$exc_abs" ]; then
      echo "  [$name/$ttype] MISSING — body-exception sidecar absent: $exc_abs"
      DRIFT=$((DRIFT + 1))
      continue
    fi
  fi

  target_abs="$PROJECT_ROOT/$target_path"
  canon_version=$(read_canonical_version "$canon_abs")

  # Expected body = canonical body (+ exception appendix when applicable).
  expected_body=$(canonical_body_with_exception "$canon_abs" "$exc_abs")
  expected_sha=$(sha_of_string "$expected_body")

  # Resolve the actual harness body per target type.
  actual_body=""
  if [ "$ttype" = "claude" ]; then
    if [ ! -f "$target_abs" ]; then
      echo "  [$name/$ttype] MISSING — harness file absent: $target_abs"
      DRIFT=$((DRIFT + 1))
      continue
    fi
    actual_body=$(strip_frontmatter "$target_abs")
  elif [ "$ttype" = "codex" ]; then
    if ! actual_body=$(codex_body "$target_abs"); then
      echo "  [$name/$ttype] MISSING — codex harness absent or unparseable: $target_abs"
      DRIFT=$((DRIFT + 1))
      continue
    fi
  else
    echo "  [$name/$ttype] DRIFTED — unknown target type"
    DRIFT=$((DRIFT + 1))
    continue
  fi

  actual_sha=$(sha_of_string "$actual_body")
  actual_version=$(read_canonical_version "$target_abs" 2>/dev/null || true)
  # codex bodies live inside a TOML value; read_canonical_version on the .toml
  # path scans the whole file and still finds the `> **Version:**` line.

  # Verdict: sha must match; version marker must match when both present.
  verdict="MATCH"
  reason=""
  if [ "$expected_sha" != "$actual_sha" ]; then
    verdict="DRIFTED"
    reason="body sha mismatch"
  elif [ -n "$canon_version" ] && [ -n "$actual_version" ] \
       && [ "$canon_version" != "$actual_version" ]; then
    verdict="DRIFTED"
    reason="version marker mismatch"
  fi

  echo "  [$name/$ttype] $verdict"
  echo "      canonical : $canon_abs"
  echo "      harness   : $target_abs"
  echo "      canon sha : $expected_sha (version ${canon_version:-none})"
  echo "      harness sha: $actual_sha (version ${actual_version:-none})"
  if [ "$verdict" = "MATCH" ]; then
    MATCH=$((MATCH + 1))
  else
    echo "      reason    : $reason"
    DRIFT=$((DRIFT + 1))
  fi
done <<< "$WORK_ROWS"
fi

# ---------------------------------------------------------------------------
# FR-137: skills-surface drift pass. For each skills target (unioned from the
# core surfaces-manifest.json and the merged agent manifest), re-derive the
# projected artifact to a temp file via the md_to_* compiler and compare
# against on-disk. The compiler IS the canonical-deriver. For the AGENTS.md
# compiler target the trailing date-stamped marker line is stripped from BOTH
# sides before sha so the verdict is date-stable.
# ---------------------------------------------------------------------------
SKILL_ROWS=$(python3 - "$CORE_SURFACES" "$MERGED_MANIFEST" "$PROJECT_ROOT" <<'PY'
import json
import os
import sys


def load_skills(path):
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except OSError:
        return None
    return (data.get("surfaces") or {}).get("skills")


# Only union the GLOBAL core surfaces-manifest.json when the checked project
# OWNS it (realpath under --project-root) — see compile_harnesses.sh. This
# keeps core skills from being flagged against unrelated project roots.
sources = [sys.argv[2]]
try:
    cs_real = os.path.realpath(sys.argv[1])
    pr_real = os.path.realpath(sys.argv[3])
    if os.path.commonpath([cs_real, pr_real]) == pr_real:
        sources.insert(0, sys.argv[1])
except (OSError, ValueError):
    pass

seen = set()
for src in sources:
    skills = load_skills(src)
    if not skills:
        continue
    source = skills.get("source", "") or "-"
    for t in skills.get("targets", []):
        ttype = t.get("type", "")
        path = t.get("path", "")
        key = (ttype, path)
        if key in seen:
            continue
        seen.add(key)
        print("\t".join([source, ttype, t.get("method", ""), path]))
PY
)

# sha_file_stripped <file> — sha256 of a file's contents with any line
# beginning with the AGENTS.md generated-marker prefix removed (date-stable).
sha_file_stripped() {
  python3 - "$1" "$AGENTS_MD_MARKER_PREFIX" <<'PY'
import hashlib
import sys
with open(sys.argv[1], "r", encoding="utf-8") as fh:
    text = fh.read()
prefix = sys.argv[2]
kept = [ln for ln in text.splitlines(keepends=True)
        if not ln.lstrip().startswith(prefix)]
print(hashlib.sha256("".join(kept).encode("utf-8")).hexdigest())
PY
}

if [ -n "$SKILL_ROWS" ]; then
  while IFS=$'\t' read -r s_source s_type s_method s_path; do
    [ -z "$s_type" ] && continue
    TOTAL=$((TOTAL + 1))

    # Resolve source (`~`/absolute verbatim, else project-relative; `-`=default).
    src_abs=""
    if [ -n "$s_source" ] && [ "$s_source" != "-" ]; then
      case "$s_source" in
        "~"/*) src_abs="$HOME/${s_source#"~/"}" ;;
        /*)    src_abs="$s_source" ;;
        *)     src_abs="$PROJECT_ROOT/$s_source" ;;
      esac
    fi
    case "$s_path" in
      "~"/*) out_abs="$HOME/${s_path#"~/"}" ;;
      /*)    out_abs="$s_path" ;;
      *)     out_abs="$PROJECT_ROOT/$s_path" ;;
    esac

    verdict="MATCH"
    reason=""
    case "$s_type/$s_method" in
      codex/compiler)
        if [ ! -f "$out_abs" ]; then
          echo "  [skills/$s_type] MISSING — projected artifact absent: $out_abs"
          DRIFT=$((DRIFT + 1))
          continue
        fi
        tmp_agents="$(mktemp "${TMPDIR:-/tmp}/igris-drift-agents.XXXXXX.md")"
        if [ -n "$src_abs" ]; then
          bash "$ADAPTER_DIR/md_to_agents_md.sh" "$tmp_agents" "$src_abs" >/dev/null 2>&1 || true
        else
          bash "$ADAPTER_DIR/md_to_agents_md.sh" "$tmp_agents" >/dev/null 2>&1 || true
        fi
        expected_sha="$(sha_file_stripped "$tmp_agents")"
        actual_sha="$(sha_file_stripped "$out_abs")"
        rm -f "$tmp_agents"
        if [ "$expected_sha" != "$actual_sha" ]; then
          verdict="DRIFTED"
          reason="re-derived AGENTS.md sha mismatch (date marker stripped)"
        fi
        echo "  [skills/$s_type] $verdict"
        echo "      source     : ${src_abs:-<md_to_agents_md default>}"
        echo "      artifact   : $out_abs"
        echo "      expected sha: $expected_sha"
        echo "      artifact sha: $actual_sha"
        ;;
      gemini/converter)
        conv_root="${src_abs:-$HOME/.igris/core/skills}"
        if [ ! -d "$conv_root" ]; then
          echo "  [skills/$s_type] MISSING — skills root absent: $conv_root"
          DRIFT=$((DRIFT + 1))
          continue
        fi
        any_missing=0
        any_drift=0
        checked=0
        while IFS= read -r -d '' skill_md; do
          skill_name="$(basename "$(dirname "$skill_md")")"
          on_disk="$out_abs/$skill_name.toml"
          if [ ! -f "$on_disk" ]; then
            any_missing=1
            continue
          fi
          tmp_toml="$(mktemp "${TMPDIR:-/tmp}/igris-drift-gemini.XXXXXX.toml")"
          bash "$ADAPTER_DIR/md_to_gemini_toml.sh" "$skill_md" "$tmp_toml" >/dev/null 2>&1 || true
          if ! diff -q "$tmp_toml" "$on_disk" >/dev/null 2>&1; then
            any_drift=1
          fi
          rm -f "$tmp_toml"
          checked=$((checked + 1))
        done < <(find "$conv_root" -mindepth 2 -maxdepth 2 -type f \
                   -name 'SKILL.md' -print0 | sort -z)
        if [ "$any_missing" -eq 1 ]; then
          verdict="MISSING"
          reason="one or more projected {name}.toml absent"
        elif [ "$any_drift" -eq 1 ]; then
          verdict="DRIFTED"
          reason="re-derived TOML differs from on-disk"
        fi
        echo "  [skills/$s_type] $verdict"
        echo "      source     : $conv_root"
        echo "      artifact dir: $out_abs ($checked skills checked)"
        ;;
      *)
        verdict="DRIFTED"
        reason="unsupported type/method '$s_type/$s_method'"
        echo "  [skills/$s_type] $verdict"
        ;;
    esac

    if [ "$verdict" = "MATCH" ]; then
      MATCH=$((MATCH + 1))
    else
      echo "      reason     : $reason"
      DRIFT=$((DRIFT + 1))
    fi
  done <<< "$SKILL_ROWS"
fi

if [ "$TOTAL" -eq 0 ]; then
  echo "No agent/skills targets matched (filter='$FILTER')." >&2
  exit 0
fi

echo ""
echo "  ----"
echo "  $TOTAL targets — $MATCH in sync, $DRIFT drifted/missing"

if [ "$DRIFT" -gt 0 ]; then
  exit 1
fi
exit 0
