#!/bin/bash

# Description: Compile all non-Claude-only Igris skills into a single AGENTS.md
#              file for Codex CLI. Enforces a 32KB size cap.
# Usage: md_to_agents_md.sh <output-agents-md-path> [skills-root]
#   output-agents-md-path - Destination for AGENTS.md (absolute or relative)
#   skills-root           - Optional: directory containing {skill}/SKILL.md
#                           entries. Defaults to ~/.igris/core/skills/.
# Dependencies: python3, _common.sh (auto-sourced from script dir)
# Exit codes:
#   0 - Success (even if some skills were skipped by cap)
#   1 - Error (missing output path, no skills root, IO error)
#   2 - Usage error

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
readonly AGENTS_MD_CAP_BYTES=32768
readonly GENERATED_MARKER="<!-- Generated by igris cli-adapter md_to_agents_md.sh"

# ---------------------------------------------------------------------------
# Locate and source shared helpers.
# ---------------------------------------------------------------------------
ADAPTER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# shellcheck source=_common.sh
source "$ADAPTER_DIR/_common.sh"

# ---------------------------------------------------------------------------
# usage — prints usage and exits with code 2.
# ---------------------------------------------------------------------------
usage() {
  echo "Usage: $0 <output-agents-md-path> [skills-root]" >&2
  echo "" >&2
  echo "Concatenates all non-Claude-only skill bodies into AGENTS.md." >&2
  echo "Default skills root: ~/.igris/core/skills/" >&2
  echo "32KB cap enforced; skipped skills logged to stderr." >&2
  exit 2
}

# ---------------------------------------------------------------------------
# Argument validation
# ---------------------------------------------------------------------------
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
  usage
fi

OUTPUT_PATH="$1"
SKILLS_ROOT="${2:-$HOME/.igris/core/skills}"

if [ -z "$OUTPUT_PATH" ]; then
  usage
fi

if [ ! -d "$SKILLS_ROOT" ]; then
  echo "Error: Skills root '$SKILLS_ROOT' does not exist" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# check_existing_agents_md — warn if user likely edited the file manually.
#
# Looks for our generated marker. If the file exists but lacks the marker,
# print a warning to stderr (non-fatal per plan — no --force flag in v1).
# ---------------------------------------------------------------------------
check_existing_agents_md() {
  local path="$1"
  if [ -f "$path" ] && ! grep -q "$GENERATED_MARKER" "$path" 2>/dev/null; then
    echo "Warning: '$path' exists without the generated marker — overwriting anyway." >&2
    echo "         If you edited it manually, save a backup before re-running." >&2
  fi
}

# ---------------------------------------------------------------------------
# Collect candidate skills (alphabetical for deterministic output).
# ---------------------------------------------------------------------------
SKILL_PATHS=()
while IFS= read -r -d '' skill_md; do
  SKILL_PATHS+=("$skill_md")
done < <(find "$SKILLS_ROOT" -mindepth 2 -maxdepth 2 -type f -name 'SKILL.md' -print0 | sort -z)

if [ "${#SKILL_PATHS[@]}" -eq 0 ]; then
  echo "Error: No SKILL.md files found under '$SKILLS_ROOT'" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Prepare output directory and accumulators.
# ---------------------------------------------------------------------------
check_existing_agents_md "$OUTPUT_PATH"

OUTPUT_DIR=$(dirname "$OUTPUT_PATH")
mkdir -p "$OUTPUT_DIR"

INCLUDED=()
SKIPPED_CLAUDE_ONLY=()
SKIPPED_CAP=()

# Buffer content in a temp file so we only commit on full success.
TMP_OUTPUT=$(mktemp "${TMPDIR:-/tmp}/igris_agents_md.XXXXXX")
trap 'rm -f "$TMP_OUTPUT"' EXIT

# ---------------------------------------------------------------------------
# Stream each skill body into the temp file, respecting the 32KB cap.
# Byte counting is done with `wc -c` for portability.
# ---------------------------------------------------------------------------
current_bytes=0

for skill_md in "${SKILL_PATHS[@]}"; do
  skill_dir=$(dirname "$skill_md")
  skill_name=$(basename "$skill_dir")

  # Skill name authority: frontmatter `name:` field when present, fall back
  # to directory basename for directory-only skills.
  fm_name=$(get_skill_field "$skill_md" "name")
  display_name="${fm_name:-$skill_name}"

  if is_claude_only "$skill_md"; then
    SKIPPED_CLAUDE_ONLY+=("$display_name")
    echo "  Skipped '$display_name': Claude-only (Agent()/Skill() heuristic or explicit opt-out)" >&2
    continue
  fi

  body=$(strip_frontmatter "$skill_md")

  # Stage the section in a scratch file so we preserve trailing newlines
  # (command substitution `$(...)` strips them, which would concat the
  # next section onto the previous body).
  section_tmp=$(mktemp "${TMPDIR:-/tmp}/igris_section.XXXXXX")
  printf '# %s\n\n%s\n\n' "$display_name" "$body" > "$section_tmp"
  section_bytes=$(wc -c < "$section_tmp" | tr -d ' ')

  # Projected size if we add this section.
  projected=$((current_bytes + section_bytes))
  if [ "$projected" -gt "$AGENTS_MD_CAP_BYTES" ]; then
    SKIPPED_CAP+=("$display_name")
    rm -f "$section_tmp"
    echo "  Skipped '$display_name': would exceed ${AGENTS_MD_CAP_BYTES}B cap (need ${section_bytes}B, have ${current_bytes}B used)" >&2
    continue
  fi

  cat "$section_tmp" >> "$TMP_OUTPUT"
  rm -f "$section_tmp"
  current_bytes=$projected
  INCLUDED+=("$display_name")
done

# ---------------------------------------------------------------------------
# Append trailing generator marker with inclusion/exclusion summary.
# The marker itself counts toward usage — but we accept a slight overage
# (comment is small, <1KB) so skipped skills are always disclosed.
# ---------------------------------------------------------------------------
DATE_UTC=$(date -u +"%Y-%m-%d")
n_included=${#INCLUDED[@]}
n_skipped_claude=${#SKIPPED_CLAUDE_ONLY[@]}
n_skipped_cap=${#SKIPPED_CAP[@]}
n_skipped=$((n_skipped_claude + n_skipped_cap))

{
  # Guarantee the marker starts on its own line, even if the last skill body
  # lacked a trailing newline.
  printf '\n'
  printf '%s on %s - %d skills included, %d skipped' \
    "$GENERATED_MARKER" "$DATE_UTC" "$n_included" "$n_skipped"
  if [ "$n_skipped_claude" -gt 0 ]; then
    printf ' | Claude-only: %s' "$(IFS=, ; echo "${SKIPPED_CLAUDE_ONLY[*]}")"
  fi
  if [ "$n_skipped_cap" -gt 0 ]; then
    printf ' | Over-cap: %s' "$(IFS=, ; echo "${SKIPPED_CAP[*]}")"
  fi
  printf ' -->\n'
} >> "$TMP_OUTPUT"

# ---------------------------------------------------------------------------
# Atomic commit to final path.
# ---------------------------------------------------------------------------
mv "$TMP_OUTPUT" "$OUTPUT_PATH"
trap - EXIT

final_bytes=$(wc -c < "$OUTPUT_PATH" | tr -d ' ')
echo "AGENTS.md written: $OUTPUT_PATH (${final_bytes}B, $n_included included, $n_skipped skipped)"
