#!/bin/bash

# Description: Sync a canonical agent prompt into a Codex CLI subagent harness
#              file (.codex/agents/<name>.toml). Emits a 3-key TOML document:
#              description, developer_instructions, name (TD-021).
# Usage: sync_codex_agents.sh [--d1-reimplement] <canonical-md> <output-toml> [agent-name]
#   --d1-reimplement  - Required opt-in flag. See D1-STATUS below.
#   canonical-md      - Canonical prompt source (markdown, may have frontmatter)
#   output-toml       - Destination .codex/agents/<name>.toml
#   agent-name        - Optional: TOML `name` value. Defaults to the canonical
#                       frontmatter `name:` field, then the output basename.
# Dependencies: python3, _common.sh (auto-sourced from script dir)
# Exit codes:
#   0 - Success (codex TOML emitted)
#   1 - Error (missing input, parse failure, IO error, D1 not resolved)
#   2 - Usage error (wrong arguments)
#
# D1-STATUS — DECISION GATE (TD-021 Phase 1.5):
#   Decision D1 (wrap codex's native import vs reimplement the TOML emit) is
#   currently BLOCKED. The `codex` CLI is not on PATH and not at any probeable
#   install location in this environment, so its native agent-import command
#   could not be characterized (scriptable / idempotent / re-runnable).
#
#   This script implements the REIMPLEMENT path: it emits the 3-key codex
#   subagent TOML directly using _common.sh's toml_escape helpers. The format
#   is fully specified (TD-021 Phase 1 finding #2): exactly 3 keys -
#   `description` (single-line basic string), `developer_instructions`
#   (triple-quoted multiline string holding the prompt body), `name`
#   (single-line basic string). This emit path is low-risk and self-contained.
#
#   Because D1 is formally BLOCKED, the codex-emit path is GUARDED: the script
#   refuses to run unless `--d1-reimplement` is passed (or the environment
#   variable IGRIS_CODEX_D1=reimplement is set). This makes the capability
#   available without silently committing to a decision the operator owns.
#   If a future probe finds codex's import IS scriptable+idempotent, a WRAP
#   variant can be added behind a sibling `--d1-wrap` flag without disturbing
#   this path.
#
# GENERATED-MARKER:
#   A leading TOML comment line is emitted. TOML comments do not affect
#   parsing, and check_harness_drift.sh compares the decoded
#   `developer_instructions` body sha (ignoring the comment), so the marker
#   is safe here - unlike the .claude/agents body which must stay byte-equal.

set -euo pipefail

# ---------------------------------------------------------------------------
# Locate and source shared helpers.
# ---------------------------------------------------------------------------
ADAPTER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# shellcheck source=_common.sh
source "$ADAPTER_DIR/_common.sh"

readonly GENERATED_MARKER="# Generated by igris cli-adapter sync_codex_agents.sh"

# ---------------------------------------------------------------------------
# usage — prints usage and exits with code 2.
# ---------------------------------------------------------------------------
usage() {
  echo "Usage: $0 [--d1-reimplement] <canonical-md> <output-toml> [agent-name]" >&2
  echo "" >&2
  echo "Emits a 3-key Codex subagent TOML (description, developer_instructions," >&2
  echo "name) from a canonical agent prompt." >&2
  echo "" >&2
  echo "Decision D1 is BLOCKED (codex CLI not probeable); the codex-emit path" >&2
  echo "is guarded. Pass --d1-reimplement (or set IGRIS_CODEX_D1=reimplement)" >&2
  echo "to opt into the reimplement emit path." >&2
  exit 2
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
D1_REIMPLEMENT=0
if [ "${IGRIS_CODEX_D1:-}" = "reimplement" ]; then
  D1_REIMPLEMENT=1
fi

POSITIONAL=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --d1-reimplement)
      D1_REIMPLEMENT=1
      shift
      ;;
    --help|-h)
      usage
      ;;
    --*)
      echo "Error: unknown flag '$1'" >&2
      usage
      ;;
    *)
      POSITIONAL+=("$1")
      shift
      ;;
  esac
done

if [ "${#POSITIONAL[@]}" -lt 2 ] || [ "${#POSITIONAL[@]}" -gt 3 ]; then
  usage
fi

CANONICAL_PATH="${POSITIONAL[0]}"
OUTPUT_PATH="${POSITIONAL[1]}"
AGENT_NAME="${POSITIONAL[2]:-}"

if [ -z "$CANONICAL_PATH" ] || [ -z "$OUTPUT_PATH" ]; then
  usage
fi

if [ ! -f "$CANONICAL_PATH" ]; then
  echo "Error: Canonical file '$CANONICAL_PATH' does not exist" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# D1 gate. The codex-emit path is BLOCKED until the operator resolves D1.
# ---------------------------------------------------------------------------
if [ "$D1_REIMPLEMENT" -ne 1 ]; then
  echo "Error: codex subagent sync is gated on Decision D1 (TD-021 Phase 1.5)." >&2
  echo "       D1 is BLOCKED: the codex CLI was not probeable in this" >&2
  echo "       environment, so wrap-vs-reimplement was not auto-decided." >&2
  echo "       To use the reimplement emit path, re-run with --d1-reimplement" >&2
  echo "       or set IGRIS_CODEX_D1=reimplement. See the header comment." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# REIMPLEMENT emit path. Build the 3-key TOML from canonical.
# ---------------------------------------------------------------------------
DESCRIPTION=$(get_skill_field "$CANONICAL_PATH" "description")
if [ -z "$DESCRIPTION" ]; then
  echo "Warning: No description found in '$CANONICAL_PATH' — using empty string" >&2
fi
ESCAPED_DESC=$(toml_escape_description "$DESCRIPTION")

BODY=$(strip_frontmatter "$CANONICAL_PATH")
ESCAPED_BODY=$(toml_escape "$BODY")

# Resolve the TOML `name`: explicit arg > canonical frontmatter `name:` >
# output filename stem.
if [ -z "$AGENT_NAME" ]; then
  AGENT_NAME=$(get_skill_field "$CANONICAL_PATH" "name")
fi
if [ -z "$AGENT_NAME" ]; then
  AGENT_NAME=$(basename "$OUTPUT_PATH")
  AGENT_NAME="${AGENT_NAME%.toml}"
fi
ESCAPED_NAME=$(toml_escape_description "$AGENT_NAME")

# ---------------------------------------------------------------------------
# Emit TOML atomically. Key order: description, developer_instructions, name
# — matches the observed codex-import output (TD-021 finding #2).
# ---------------------------------------------------------------------------
OUTPUT_DIR=$(dirname "$OUTPUT_PATH")
mkdir -p "$OUTPUT_DIR"

TMP_OUTPUT=$(mktemp "${TMPDIR:-/tmp}/igris_codex_harness.XXXXXX")
trap 'rm -f "$TMP_OUTPUT"' EXIT

python3 - "$TMP_OUTPUT" "$ESCAPED_DESC" "$ESCAPED_BODY" "$ESCAPED_NAME" "$GENERATED_MARKER" <<'PY'
import sys

out_path = sys.argv[1]
description = sys.argv[2]
body = sys.argv[3]
name = sys.argv[4]
marker = sys.argv[5]

toml = marker + "\n"
toml += f'description = "{description}"\n'
toml += 'developer_instructions = """\n'
toml += body
if not toml.endswith("\n"):
    toml += "\n"
toml += '"""\n'
toml += f'name = "{name}"\n'

with open(out_path, "w", encoding="utf-8") as fh:
    fh.write(toml)
PY

mv "$TMP_OUTPUT" "$OUTPUT_PATH"
trap - EXIT

echo "Codex agent harness synced: $OUTPUT_PATH"
