#!/bin/bash

# Description: Sync a canonical agent prompt into a Codex CLI subagent harness
#              file (.codex/agents/<name>.toml). Emits a 3-key TOML document:
#              description, developer_instructions, name (TD-021).
# Usage: sync_codex_agents.sh <frontmatter-md> <body-md> <output-toml> [agent-name]
#   frontmatter-md    - FR-151 sidecar holding the metadata frontmatter (or a
#                       compile-time tempfile when the canonical carries only
#                       inline frontmatter — see resolve_or_extract_frontmatter
#                       in compile_harnesses.sh, TD-195 fallback).
#   body-md           - Canonical body source (may carry a stray
#                       `> **Version:**` blockquote — strip_frontmatter is a
#                       no-op when no `---` block is present).
#   output-toml       - Destination .codex/agents/<name>.toml
#   agent-name        - Optional: TOML `name` value. Defaults to the
#                       frontmatter-md `name:` field, then the output basename.
# Dependencies: python3, _common.sh (auto-sourced from script dir)
# Exit codes:
#   0 - Success (codex TOML emitted)
#   1 - Error (missing input, parse failure, IO error)
#   2 - Usage error (wrong arguments)
#
# DEPRECATED FLAG: `--d1-reimplement` (and IGRIS_CODEX_D1=reimplement) are
#   accepted but IGNORED no-ops, retained for back-compat with callers/scripts
#   that still pass them. They no longer gate anything. Remove in a future
#   cleanup once no caller passes them.
#
# D1-STATUS — RESOLVED, REIMPLEMENT (FR-138):
#   Decision D1 (wrap codex's native import vs reimplement the TOML emit) is
#   RESOLVED in favor of REIMPLEMENT. This script emits the 3-key codex
#   subagent TOML directly using _common.sh's toml_escape helpers — the live,
#   ratified, default path (no opt-in required). The format is fully specified
#   (TD-021 Phase 1 finding #2): exactly 3 keys - `description` (single-line
#   basic string), `developer_instructions` (triple-quoted multiline string
#   holding the prompt body), `name` (single-line basic string). This emit
#   path is low-risk and self-contained.
#
#   If a future probe finds codex's import IS scriptable+idempotent, a WRAP
#   variant can be added behind a sibling `--d1-wrap` flag without disturbing
#   this path.
#
# GENERATED-MARKER:
#   A leading TOML comment line is emitted. TOML comments do not affect
#   parsing, and check_harness_drift.sh compares the decoded
#   `developer_instructions` body sha (ignoring the comment), so the marker
#   is safe here - unlike the .claude/agents body which must stay byte-equal.

set -euo pipefail

# ---------------------------------------------------------------------------
# Locate and source shared helpers.
# ---------------------------------------------------------------------------
ADAPTER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# shellcheck source=_common.sh
source "$ADAPTER_DIR/_common.sh"

readonly GENERATED_MARKER="# Generated by igris cli-adapter sync_codex_agents.sh"

# ---------------------------------------------------------------------------
# usage — prints usage and exits with code 2.
# ---------------------------------------------------------------------------
usage() {
  echo "Usage: $0 <frontmatter-md> <body-md> <output-toml> [agent-name]" >&2
  echo "" >&2
  echo "Emits a 3-key Codex subagent TOML (description, developer_instructions," >&2
  echo "name) from an FR-151-split frontmatter sidecar + body. Live emit path" >&2
  echo "(D1 RESOLVED — REIMPLEMENT, FR-138; signature refactored FR-152)." >&2
  echo "" >&2
  echo "DEPRECATED: --d1-reimplement / IGRIS_CODEX_D1=reimplement are accepted" >&2
  echo "but ignored no-ops, retained for back-compat." >&2
  exit 2
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
POSITIONAL=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --d1-reimplement)
      # DEPRECATED no-op (FR-138): accepted for back-compat, ignored. The
      # codex emit path is live and unconditional now.
      shift
      ;;
    --help|-h)
      usage
      ;;
    --*)
      echo "Error: unknown flag '$1'" >&2
      usage
      ;;
    *)
      POSITIONAL+=("$1")
      shift
      ;;
  esac
done

# FR-152 signature: <frontmatter-md> <body-md> <output-toml> [agent-name].
if [ "${#POSITIONAL[@]}" -lt 3 ] || [ "${#POSITIONAL[@]}" -gt 4 ]; then
  usage
fi

FRONTMATTER_PATH="${POSITIONAL[0]}"
BODY_PATH="${POSITIONAL[1]}"
OUTPUT_PATH="${POSITIONAL[2]}"
AGENT_NAME="${POSITIONAL[3]:-}"

if [ -z "$FRONTMATTER_PATH" ] || [ -z "$BODY_PATH" ] || [ -z "$OUTPUT_PATH" ]; then
  usage
fi

if [ ! -f "$FRONTMATTER_PATH" ]; then
  echo "Error: Frontmatter file '$FRONTMATTER_PATH' does not exist" >&2
  exit 1
fi
if [ ! -f "$BODY_PATH" ]; then
  echo "Error: Body file '$BODY_PATH' does not exist" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# REIMPLEMENT emit path (D1 RESOLVED — FR-138). Build the 3-key TOML from the
# split frontmatter sidecar + body (FR-152 signature refactor — frontmatter and
# body are addressed separately so the FR-151 sidecar shape is first-class).
# ---------------------------------------------------------------------------
DESCRIPTION=$(get_skill_field "$FRONTMATTER_PATH" "description")
if [ -z "$DESCRIPTION" ]; then
  echo "Warning: No description found in '$FRONTMATTER_PATH' — using empty string" >&2
fi
ESCAPED_DESC=$(toml_escape_description "$DESCRIPTION")

BODY=$(strip_frontmatter "$BODY_PATH")
ESCAPED_BODY=$(toml_escape "$BODY")

# Resolve the TOML `name`: explicit arg > frontmatter `name:` > output stem.
if [ -z "$AGENT_NAME" ]; then
  AGENT_NAME=$(get_skill_field "$FRONTMATTER_PATH" "name")
fi
if [ -z "$AGENT_NAME" ]; then
  AGENT_NAME=$(basename "$OUTPUT_PATH")
  AGENT_NAME="${AGENT_NAME%.toml}"
fi
ESCAPED_NAME=$(toml_escape_description "$AGENT_NAME")

# ---------------------------------------------------------------------------
# Emit TOML atomically. Key order: description, developer_instructions, name
# — matches the observed codex-import output (TD-021 finding #2).
# ---------------------------------------------------------------------------
OUTPUT_DIR=$(dirname "$OUTPUT_PATH")
mkdir -p "$OUTPUT_DIR"

TMP_OUTPUT=$(mktemp "${TMPDIR:-/tmp}/igris_codex_harness.XXXXXX")
trap 'rm -f "$TMP_OUTPUT"' EXIT

python3 - "$TMP_OUTPUT" "$ESCAPED_DESC" "$ESCAPED_BODY" "$ESCAPED_NAME" "$GENERATED_MARKER" <<'PY'
import sys

out_path = sys.argv[1]
description = sys.argv[2]
body = sys.argv[3]
name = sys.argv[4]
marker = sys.argv[5]

toml = marker + "\n"
toml += f'description = "{description}"\n'
toml += 'developer_instructions = """\n'
toml += body
if not toml.endswith("\n"):
    toml += "\n"
toml += '"""\n'
toml += f'name = "{name}"\n'

with open(out_path, "w", encoding="utf-8") as fh:
    fh.write(toml)
PY

mv "$TMP_OUTPUT" "$OUTPUT_PATH"
trap - EXIT

echo "Codex agent harness synced: $OUTPUT_PATH"
