/**
 * global-claude-md.test.ts — TD-176.
 *
 * Real fs against tmp dirs. No mocks (per L-159). HOME is overridden so
 * `globalClaudeMdPath()` resolves into a sandboxed `~/.claude/`.
 *
 * Coverage:
 *   1. parseInstalledVersion — well-formed, placeholder, missing line.
 *   2. needsRewrite — drift / no-op / null / downgrade / patch boundary.
 *   3. renderGlobalClaudeMd — substitution, preserved date, stamped date,
 *      no leftover placeholders.
 *   4. regenerateGlobalClaudeMd — writes when stale, no-op when current,
 *      creates ~/.claude/ dir, atomic (no .tmp.* straggler), idempotent.
 */

import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

let tmpHome: string;
let tmplPath: string;
const envBackup: Record<string, string | undefined> = {};

/** Template body mirroring the shipped CLAUDE.global.md.tmpl. */
const TEMPLATE = `# Igris AI — Centralized Brain

## Brain Status

- **Version:** {{IGRIS_VERSION}}
- **Installed:** {{INSTALL_DATE}}
- **Source Repo:** {{SOURCE_REPO}}

## Note

This file is auto-generated by \`igris init\`.
`;

/** Compute the sandboxed global CLAUDE.md path under the tmp HOME. */
function globalPath(): string {
  return join(tmpHome, ".claude", "CLAUDE.md");
}

/** A well-formed v6 file (as written by the retired shell installer). */
function v6File(): string {
  return `# Igris AI — Centralized Brain

## Brain Status

- **Version:** 6.0.0
- **Installed:** 2026-02-16T07:37:48Z
- **Source Repo:** /Users/me/StudioProjects/igris-ai

## Note

This file is auto-generated by \`igris_brain_init.sh\`.
`;
}

beforeEach(() => {
  tmpHome = mkdtempSync(join(tmpdir(), "igris-cli-global-claude-home-"));
  const tmplDir = mkdtempSync(join(tmpdir(), "igris-cli-global-claude-tmpl-"));
  tmplPath = join(tmplDir, "CLAUDE.global.md.tmpl");
  writeFileSync(tmplPath, TEMPLATE);
  envBackup.HOME = process.env.HOME;
  envBackup.USERPROFILE = process.env.USERPROFILE;
  process.env.HOME = tmpHome;
  process.env.USERPROFILE = tmpHome;
});

afterEach(() => {
  rmSync(tmpHome, { recursive: true, force: true });
  rmSync(tmplPath, { recursive: true, force: true });
  process.env.HOME = envBackup.HOME;
  process.env.USERPROFILE = envBackup.USERPROFILE;
});

describe("global-claude-md — parseInstalledVersion", () => {
  it("extracts the version from a well-formed file", async () => {
    const m = await import("../lib/global-claude-md.js");
    expect(m.parseInstalledVersion(v6File())).toBe("6.0.0");
  });

  it("returns null when the Version line still has a placeholder", async () => {
    const m = await import("../lib/global-claude-md.js");
    expect(m.parseInstalledVersion(TEMPLATE)).toBeNull();
  });

  it("returns null when there is no Version line", async () => {
    const m = await import("../lib/global-claude-md.js");
    expect(m.parseInstalledVersion("# no version here\n")).toBeNull();
  });
});

describe("global-claude-md — needsRewrite", () => {
  it("rewrites when installed is older (6.0.0 -> 7.0.0)", async () => {
    const m = await import("../lib/global-claude-md.js");
    expect(m.needsRewrite("6.0.0", "7.0.0")).toBe(true);
  });

  it("no-op when installed equals current (7.0.0 == 7.0.0)", async () => {
    const m = await import("../lib/global-claude-md.js");
    expect(m.needsRewrite("7.0.0", "7.0.0")).toBe(false);
  });

  it("rewrites when installed version is null (absent/malformed)", async () => {
    const m = await import("../lib/global-claude-md.js");
    expect(m.needsRewrite(null, "7.0.0")).toBe(true);
  });

  it("no-op on downgrade (newer file, older CLI: 7.1.0 vs 7.0.0)", async () => {
    const m = await import("../lib/global-claude-md.js");
    expect(m.needsRewrite("7.1.0", "7.0.0")).toBe(false);
  });

  it("rewrites on a patch-level bump (7.0.0 -> 7.0.1)", async () => {
    const m = await import("../lib/global-claude-md.js");
    expect(m.needsRewrite("7.0.0", "7.0.1")).toBe(true);
  });

  it("rewrites on a minor-level bump (7.0.5 -> 7.1.0)", async () => {
    const m = await import("../lib/global-claude-md.js");
    expect(m.needsRewrite("7.0.5", "7.1.0")).toBe(true);
  });
});

describe("global-claude-md — renderGlobalClaudeMd", () => {
  it("substitutes version and preserves a supplied install date", async () => {
    const m = await import("../lib/global-claude-md.js");
    const out = m.renderGlobalClaudeMd({
      cliVersion: "7.0.0",
      installDate: "2026-02-16T07:37:48Z",
      sourceRepo: "/Users/me/StudioProjects/igris-ai",
      templatePath: tmplPath,
    });
    expect(out).toContain("- **Version:** 7.0.0");
    expect(out).toContain("- **Installed:** 2026-02-16T07:37:48Z");
    expect(out).toContain("- **Source Repo:** /Users/me/StudioProjects/igris-ai");
  });

  it("stamps today's date when no install date is supplied", async () => {
    const m = await import("../lib/global-claude-md.js");
    const out = m.renderGlobalClaudeMd({
      cliVersion: "7.0.0",
      templatePath: tmplPath,
    });
    const today = new Date().toISOString().slice(0, 10);
    expect(out).toContain(`- **Installed:** ${today}`);
  });

  it("leaves no {{...}} placeholders in the rendered output", async () => {
    const m = await import("../lib/global-claude-md.js");
    const out = m.renderGlobalClaudeMd({
      cliVersion: "7.0.0",
      templatePath: tmplPath,
    });
    expect(out).not.toContain("{{");
  });

  it("raises GlobalClaudeMdTemplateError when the template is missing", async () => {
    const m = await import("../lib/global-claude-md.js");
    const { GlobalClaudeMdTemplateError } = m;
    expect(() =>
      m.renderGlobalClaudeMd({
        cliVersion: "7.0.0",
        templatePath: join(tmpHome, "does-not-exist.tmpl"),
      }),
    ).toThrow(GlobalClaudeMdTemplateError);
  });
});

describe("global-claude-md — regenerateGlobalClaudeMd", () => {
  it("rewrites a stale v6 file to v7 (written: true)", async () => {
    const m = await import("../lib/global-claude-md.js");
    mkdirSync(join(tmpHome, ".claude"), { recursive: true });
    writeFileSync(globalPath(), v6File());

    const res = m.regenerateGlobalClaudeMd({
      cliVersion: "7.0.0",
      templatePath: tmplPath,
    });
    expect(res.written).toBe(true);
    expect(res.path).toBe(globalPath());
    expect(res.previousVersion).toBe("6.0.0");

    const out = readFileSync(globalPath(), "utf-8");
    expect(out).toContain("- **Version:** 7.0.0");
    // Install date preserved from the v6 file.
    expect(out).toContain("- **Installed:** 2026-02-16T07:37:48Z");
    // Source repo preserved from the v6 file.
    expect(out).toContain(
      "- **Source Repo:** /Users/me/StudioProjects/igris-ai",
    );
  });

  it("is a no-op when the file is already current (written: false)", async () => {
    const m = await import("../lib/global-claude-md.js");
    mkdirSync(join(tmpHome, ".claude"), { recursive: true });
    const current = m.renderGlobalClaudeMd({
      cliVersion: "7.0.0",
      installDate: "2026-02-16T07:37:48Z",
      sourceRepo: "/Users/me/StudioProjects/igris-ai",
      templatePath: tmplPath,
    });
    writeFileSync(globalPath(), current);

    const res = m.regenerateGlobalClaudeMd({
      cliVersion: "7.0.0",
      templatePath: tmplPath,
    });
    expect(res.written).toBe(false);
    // Bytes unchanged.
    expect(readFileSync(globalPath(), "utf-8")).toBe(current);
  });

  it("creates the ~/.claude/ directory when it is absent", async () => {
    const m = await import("../lib/global-claude-md.js");
    expect(existsSync(join(tmpHome, ".claude"))).toBe(false);

    const res = m.regenerateGlobalClaudeMd({
      cliVersion: "7.0.0",
      templatePath: tmplPath,
    });
    expect(res.written).toBe(true);
    expect(res.previousVersion).toBeNull();
    expect(existsSync(globalPath())).toBe(true);
  });

  it("leaves no .tmp.* straggler (atomic rename completed)", async () => {
    const m = await import("../lib/global-claude-md.js");
    m.regenerateGlobalClaudeMd({
      cliVersion: "7.0.0",
      templatePath: tmplPath,
    });
    const stragglers = readdirSync(join(tmpHome, ".claude")).filter((e) =>
      e.includes(".tmp."),
    );
    expect(stragglers).toEqual([]);
  });

  it("is idempotent — a second run on a current file changes nothing", async () => {
    const m = await import("../lib/global-claude-md.js");
    m.regenerateGlobalClaudeMd({ cliVersion: "7.0.0", templatePath: tmplPath });
    const first = readFileSync(globalPath(), "utf-8");

    const res = m.regenerateGlobalClaudeMd({
      cliVersion: "7.0.0",
      templatePath: tmplPath,
    });
    expect(res.written).toBe(false);
    expect(readFileSync(globalPath(), "utf-8")).toBe(first);
  });
});
