/**
 * Igris Brain -- Sync Egress Manifest builder (TD-253).
 *
 * A single pure builder that derives the consumer-facing egress disclosure
 * ENTIRELY from `SYNC_TABLES` (the single source of truth for what replicates
 * to a remote brain). It emits two committed, never-hand-edited artifacts:
 *
 *   1. `docs/reference/sync-egress-manifest.md` — public disclosure doc.
 *   2. `cli/src/lib/sync/egress-manifest.generated.ts` — the SAME facts as a TS
 *      module the CLI imports (the CLI and brain-mcp-server have zero
 *      cross-imports, so each side reads its own committed copy).
 *
 * Both artifacts are regenerated by `scripts/gen-egress-manifest.ts`. The parity
 * test (`__tests__/egress-manifest-parity.test.ts`) regenerates in-memory and
 * asserts byte-equality with the committed files, so a `SYNC_TABLES` edit that
 * isn't regenerated fails CI (disclosure can't drift from the array).
 *
 * NO column is hand-listed here — every column, strategy, and redaction
 * annotation is read off the array. The category grouping is the ONLY authored
 * layer (a readability aid); any table missing from the map falls back to
 * "Other" so a newly-added SYNC_TABLES entry never breaks generation.
 *
 * @module tools/egress-manifest
 * @author fifty.dev
 */

import type { SyncTableConfig } from './sync.js';
import { SYNC_NORMALIZED_FIELDS } from './brief-normalize.js';

// ---------------------------------------------------------------------------
// TD-338 — ingress normalization disclosure
// ---------------------------------------------------------------------------

/**
 * `table.column` names normalized on replication INGRESS, DERIVED from
 * `SYNC_NORMALIZED_FIELDS` so the disclosure cannot drift from the map that
 * actually drives the fold. Adding a normalized field (TD-333's `status`, say)
 * updates this doc automatically — and the parity test fails until the
 * artifacts are regenerated.
 */
const NORMALIZED_INGRESS_COLUMNS: string[] = Object.entries(SYNC_NORMALIZED_FIELDS)
  .flatMap(([table, fields]) => Object.keys(fields).map((f) => `${table}.${f}`));

// ---------------------------------------------------------------------------
// Committed-artifact locations (repo-relative) — referenced by the disclosure
// text AND resolved by the generator/parity test.
// ---------------------------------------------------------------------------

/** Repo-relative path to the generated public disclosure doc. */
export const MANIFEST_DOC_REL_PATH = 'docs/reference/sync-egress-manifest.md';

/** Repo-relative path to the generated CLI-side manifest module. */
export const MANIFEST_CLI_REL_PATH = 'cli/src/lib/sync/egress-manifest.generated.ts';

// ---------------------------------------------------------------------------
// Category grouping (the only authored layer — a readability aid over the
// column dump). Tables render in category order; within a category, in
// SYNC_TABLES order. Unmapped tables fall back to "Other".
// ---------------------------------------------------------------------------

const CATEGORY_ORDER = [
  'Project registry',
  'Learnings & errors',
  'Session, brief & task content',
  'Instance & host metadata',
  'Knowledge graph',
  'Reusable-asset catalog',
  'Schedules & runs',
  'Perception & subconscious',
  'Other',
] as const;

const OTHER_CATEGORY = 'Other';

const TABLE_CATEGORY: Record<string, string> = {
  projects: 'Project registry',
  learnings: 'Learnings & errors',
  errors: 'Learnings & errors',
  sessions: 'Session, brief & task content',
  brief_status: 'Session, brief & task content',
  brief_files: 'Session, brief & task content',
  session_files: 'Session, brief & task content',
  definition_files: 'Session, brief & task content',
  agent_metrics: 'Session, brief & task content',
  agent_events: 'Session, brief & task content',
  ceremony_events: 'Session, brief & task content',
  event_log: 'Session, brief & task content',
  instances: 'Instance & host metadata',
  entity_edges: 'Knowledge graph',
  graph_nodes: 'Knowledge graph',
  goals: 'Knowledge graph',
  catalog: 'Reusable-asset catalog',
  schedules: 'Schedules & runs',
  schedule_runs: 'Schedules & runs',
  suggestions: 'Perception & subconscious',
  dismissed_patterns: 'Perception & subconscious',
};

// ---------------------------------------------------------------------------
// Public shapes
// ---------------------------------------------------------------------------

/** One disclosed table's egress facts (all read off its SyncTableConfig). */
export interface EgressTableInfo {
  table: string;
  /** Human-readable sync strategy label. */
  strategy: string;
  /** Every disclosed column, in SYNC_TABLES order. */
  columns: string[];
  /** The subset of `columns` relativized before egress (from `redactCols`). */
  redactCols: string[];
}

/** A category bucket holding its tables (only categories with ≥1 table appear). */
export interface EgressCategory {
  name: string;
  tables: EgressTableInfo[];
}

/** The structured manifest — the machine-readable middle form. */
export interface EgressManifest {
  categories: EgressCategory[];
  /** Flattened list of every relativized column, as `{table, column}`. */
  redactedColumns: { table: string; column: string }[];
  /** Comma-joined lowercase category names that actually have tables. */
  categorySummary: string;
}

/** The full build result: the structured manifest + both rendered artifacts. */
export interface EgressManifestResult {
  manifest: EgressManifest;
  markdown: string;
  cliModule: string;
}

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

function strategyLabel(strategy: SyncTableConfig['strategy']): string {
  return strategy === 'lww' ? 'last-write-wins' : 'append-only';
}

/**
 * Build the structured manifest by reading `SYNC_TABLES`. Pure — the caller
 * passes the array so this is trivially testable with any input.
 */
function buildManifest(tables: SyncTableConfig[]): EgressManifest {
  const infos: EgressTableInfo[] = tables.map((cfg) => ({
    table: cfg.table,
    strategy: strategyLabel(cfg.strategy),
    columns: [...cfg.columns],
    redactCols: [...(cfg.redactCols ?? [])],
  }));

  // Group into categories, preserving CATEGORY_ORDER then SYNC_TABLES order.
  const byCategory = new Map<string, EgressTableInfo[]>();
  for (const info of infos) {
    const category = TABLE_CATEGORY[info.table] ?? OTHER_CATEGORY;
    const bucket = byCategory.get(category);
    if (bucket) bucket.push(info);
    else byCategory.set(category, [info]);
  }

  const categories: EgressCategory[] = [];
  for (const name of CATEGORY_ORDER) {
    const bucket = byCategory.get(name);
    if (bucket && bucket.length > 0) categories.push({ name, tables: bucket });
  }

  const redactedColumns: { table: string; column: string }[] = [];
  for (const info of infos) {
    for (const column of info.redactCols) {
      redactedColumns.push({ table: info.table, column });
    }
  }

  const categorySummary = categories
    .map((c) => c.name.toLowerCase())
    .join(', ');

  return { categories, redactedColumns, categorySummary };
}

// ---------------------------------------------------------------------------
// Markdown rendering (the public disclosure doc)
// ---------------------------------------------------------------------------

function renderMarkdown(manifest: EgressManifest): string {
  const lines: string[] = [];

  lines.push(
    '<!-- GENERATED by brain-mcp-server/scripts/gen-egress-manifest.ts — DO NOT EDIT BY HAND. -->',
    '<!-- Re-run `npm run gen:egress-manifest` (in brain-mcp-server/) to refresh; edits here are overwritten. -->',
    '',
    '# Sync Egress Manifest',
    '',
    'When you enable remote brain sync (a VPS configured via `igris init` or',
    '`igris configure`), Igris pushes rows changed since the last sync to your',
    'configured server over HTTPS. This document discloses **exactly** which',
    'tables and columns egress, and which local filesystem paths are relativized',
    'before any row leaves your machine.',
    '',
    'It is generated from `SYNC_TABLES` in `brain-mcp-server/src/tools/sync.ts` —',
    'the single source of truth. A parity test',
    '(`brain-mcp-server/src/tools/__tests__/egress-manifest-parity.test.ts`) fails',
    'CI if this file drifts from that array.',
    '',
    '## Path redaction',
    '',
    'Before egress, the columns below — which hold absolute local filesystem',
    'paths — are relativized so your machine\'s directory layout is not disclosed:',
    '',
    '- your home directory becomes `~` (e.g. `/Users/you/code/app` → `~/code/app`);',
    '- a path outside your home directory is reduced to its final path segment',
    '  (e.g. `/opt/work/app` → `app`);',
    '- an already-relative value is left unchanged.',
    '',
    'Redacted columns:',
    '',
  );

  if (manifest.redactedColumns.length === 0) {
    lines.push('- _(none)_', '');
  } else {
    for (const { table, column } of manifest.redactedColumns) {
      lines.push(`- \`${table}.${column}\``);
    }
    lines.push('');
  }

  lines.push(
    '## What we rewrite on the way IN (TD-338)',
    '',
    'Egress is only half the honesty contract. Rows arriving FROM a remote brain',
    'are merged last-write-wins into your local store, and a small, declared set',
    'of `brief_status` columns is **normalized on arrival** — the same fold the',
    'local write boundary applies when you create or update a brief:',
    '',
    `- ${NORMALIZED_INGRESS_COLUMNS.map((c) => `\`${c}\``).join(', ')}.`,
    '',
    'The rules, in full:',
    '',
    '- **Only declared synonyms fold.** `P1` becomes `P1-High` because the fold',
    '  table says they are the same value; `TD` becomes `Technical Debt` for the',
    '  same reason.',
    '- **Unknown values are never folded and never dropped.** A value with no',
    '  declared canonical form (`P4-Trivial`, `Spike`) is stored exactly as it',
    '  arrived, and reported.',
    '- **Every fold and every unknown value is named** in the sync output — the',
    '  pull summary, the `POST /sync/push` response body (so the machine that',
    '  pushed learns its row was folded on arrival), and the `igris boot-sync`',
    '  digest. Nothing is rewritten silently.',
    '- **Timestamps are never touched.** The last-write-wins comparison column is',
    '  deliberately excluded from the fold, so normalizing a row cannot make your',
    '  brain and the remote overwrite each other in a loop. The consequence is',
    '  stated plainly: your copy may hold the canonical spelling while an',
    '  older remote keeps its own, at the same timestamp, and neither will',
    '  overwrite the other.',
    '',
    '## What egresses',
    '',
    'Rows changed since the last successful sync are pushed. Tables are grouped',
    'below by category; every column is disclosed, and a relativized path column',
    'is annotated inline.',
    '',
  );

  for (const category of manifest.categories) {
    lines.push(`### ${category.name}`, '');
    for (const info of category.tables) {
      const redactSet = new Set(info.redactCols);
      lines.push(`#### \`${info.table}\` — ${info.strategy}`, '');
      for (const column of info.columns) {
        if (redactSet.has(column)) {
          lines.push(
            `- \`${column}\` — local filesystem path, relativized to \`~\` before egress`,
          );
        } else {
          lines.push(`- \`${column}\``);
        }
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// CLI TS module rendering (the CLI-side copy the disclosure surfaces read)
// ---------------------------------------------------------------------------

function tsStringLiteral(value: string): string {
  return JSON.stringify(value);
}

function renderCliModule(manifest: EgressManifest): string {
  const redactedEntries = manifest.redactedColumns
    .map(
      ({ table, column }) =>
        `  { table: ${tsStringLiteral(table)}, column: ${tsStringLiteral(column)} },`,
    )
    .join('\n');

  const disclosureLines = buildDisclosureLines(manifest)
    .map((line) => `  ${tsStringLiteral(line)},`)
    .join('\n');

  const lines: string[] = [
    '// GENERATED by brain-mcp-server/scripts/gen-egress-manifest.ts — DO NOT EDIT BY HAND.',
    '// Re-run `npm run gen:egress-manifest` (in brain-mcp-server/) to refresh; edits here are overwritten.',
    '//',
    '// Consumer-facing egress disclosure derived from SYNC_TABLES (the single',
    '// source of truth in brain-mcp-server/src/tools/sync.ts). The CLI and',
    '// brain-mcp-server have zero cross-imports, so the CLI reads this committed',
    '// copy; the brain-side parity test asserts it is byte-identical to a fresh',
    '// regeneration, so any SYNC_TABLES change that is not regenerated fails CI.',
    '',
    '/** One relativized (redacted) column: a local FS path stripped before egress. */',
    'export interface EgressRedactedColumn {',
    '  readonly table: string;',
    '  readonly column: string;',
    '}',
    '',
    '/** Plain-language summary of the data categories that egress on remote sync. */',
    `export const EGRESS_CATEGORY_SUMMARY = ${tsStringLiteral(manifest.categorySummary)};`,
    '',
    '/** Columns relativized (home → ~, foreign-absolute → basename) before egress. */',
    'export const EGRESS_REDACTED_COLUMNS: readonly EgressRedactedColumn[] = [',
    redactedEntries,
    '];',
    '',
    '/** Repo-relative path to the full human-readable egress manifest. */',
    `export const MANIFEST_DOC_PATH = ${tsStringLiteral(MANIFEST_DOC_REL_PATH)};`,
    '',
    '/** Pre-rendered disclosure lines printed at the VPS consent moment + sync dry-run. */',
    'export const EGRESS_DISCLOSURE_LINES: readonly string[] = [',
    disclosureLines,
    '];',
    '',
  ];

  return lines.join('\n');
}

/**
 * The pre-rendered disclosure lines shared by the VPS consent prompt and the
 * `igris sync --dry-run` plan. Derived from the manifest so the two surfaces
 * cannot diverge from the doc.
 */
function buildDisclosureLines(manifest: EgressManifest): string[] {
  const redacted = manifest.redactedColumns
    .map(({ table, column }) => `${table}.${column}`)
    .join(', ');
  const redactedClause =
    manifest.redactedColumns.length === 0
      ? 'no local filesystem paths egress'
      : `local filesystem paths are relativized to ~ before egress (${redacted})`;
  return [
    'Remote sync egresses the following to your configured VPS (over HTTPS):',
    `  categories: ${manifest.categorySummary}`,
    `  ${redactedClause}`,
    // TD-338: what we rewrite on the way IN belongs at the consent moment too —
    // the operator is agreeing to a two-way exchange, not just an upload.
    `  on arrival, these columns are normalized to the canonical vocabulary (unknown values kept + reported): ${NORMALIZED_INGRESS_COLUMNS.join(', ')}`,
    `  full manifest: ${MANIFEST_DOC_REL_PATH}`,
  ];
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Build the egress manifest + both rendered artifacts from a SYNC_TABLES-shaped
 * array. Everything (columns, strategies, redaction annotations) is derived
 * from the array — nothing is hand-listed.
 */
export function buildEgressManifest(
  tables: SyncTableConfig[],
): EgressManifestResult {
  const manifest = buildManifest(tables);
  return {
    manifest,
    markdown: renderMarkdown(manifest),
    cliModule: renderCliModule(manifest),
  };
}
