// GENERATED by brain-mcp-server/scripts/gen-egress-manifest.ts — DO NOT EDIT BY HAND.
// Re-run `npm run gen:egress-manifest` (in brain-mcp-server/) to refresh; edits here are overwritten.
//
// Consumer-facing egress disclosure derived from SYNC_TABLES (the single
// source of truth in brain-mcp-server/src/tools/sync.ts). The CLI and
// brain-mcp-server have zero cross-imports, so the CLI reads this committed
// copy; the brain-side parity test asserts it is byte-identical to a fresh
// regeneration, so any SYNC_TABLES change that is not regenerated fails CI.

/** One relativized (redacted) column: a local FS path stripped before egress. */
export interface EgressRedactedColumn {
  readonly table: string;
  readonly column: string;
}

/** Plain-language summary of the data categories that egress on remote sync. */
export const EGRESS_CATEGORY_SUMMARY = "project registry, learnings & errors, session, brief & task content, instance & host metadata, knowledge graph, reusable-asset catalog, schedules & runs, perception & subconscious";

/** Columns relativized (home → ~, foreign-absolute → basename) before egress. */
export const EGRESS_REDACTED_COLUMNS: readonly EgressRedactedColumn[] = [
  { table: "projects", column: "path" },
  { table: "instances", column: "project_path" },
];

/** Repo-relative path to the full human-readable egress manifest. */
export const MANIFEST_DOC_PATH = "docs/reference/sync-egress-manifest.md";

/** Pre-rendered disclosure lines printed at the VPS consent moment + sync dry-run. */
export const EGRESS_DISCLOSURE_LINES: readonly string[] = [
  "Remote sync egresses the following to your configured VPS (over HTTPS):",
  "  categories: project registry, learnings & errors, session, brief & task content, instance & host metadata, knowledge graph, reusable-asset catalog, schedules & runs, perception & subconscious",
  "  local filesystem paths are relativized to ~ before egress (projects.path, instances.project_path)",
  "  full manifest: docs/reference/sync-egress-manifest.md",
];
