/**
 * TD-338 — brief-normalize CLI-mirror drift gate.
 *
 * Regenerates the committed artifact in-memory from the live `brief-normalize.ts`
 * exports via `buildBriefNormalizeMirror` and asserts byte-equality with the
 * committed file (read by repo-relative fs path — a FILE READ, never a
 * cross-package import). Any fold-table or canonical-set edit that is not
 * regenerated with `npm run gen:brief-normalize-mirror` fails here, so the CLI's
 * `mergeRows` cannot silently fold a different vocabulary than the brain's.
 *
 * The BEHAVIOURAL half of the guard lives on the CLI side
 * (`cli/src/__tests__/brief-normalize-mirror.test.ts`), which replays
 * `NORMALIZE_FIXTURES`. This file proves the fixtures are current; that one
 * proves the CLI reproduces them.
 *
 * @module tools/__tests__/brief-normalize-mirror-parity.test
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  assertNormalizerBodies,
  buildBriefNormalizeMirror,
  normalizerIdsInUse,
  MIRROR_CLI_REL_PATH,
} from '../brief-normalize-mirror.js';
import {
  CANONICAL_PRIORITIES,
  SYNC_NORMALIZED_FIELDS,
  normalizeBriefType,
  normalizePhase,
  normalizePriority,
  normalizeSyncRow,
} from '../brief-normalize.js';
import { SYNC_TABLES } from '../sync.js';

// __tests__ → tools → src → brain-mcp-server → repo root
const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../../../..');

function readCommitted(relPath: string): string {
  return readFileSync(resolve(REPO_ROOT, relPath), 'utf8');
}

describe('brief-normalize mirror parity (TD-338)', () => {
  const { cliModule, fixtures } = buildBriefNormalizeMirror();

  it('cli/src/lib/brief-normalize.generated.ts is byte-identical to a fresh regeneration', () => {
    expect(readCommitted(MIRROR_CLI_REL_PATH)).toBe(cliModule);
  });

  it('carries the DO-NOT-EDIT header the mirror rule requires', () => {
    expect(cliModule.startsWith('// GENERATED by ')).toBe(true);
    expect(cliModule).toContain('DO NOT EDIT BY HAND');
    expect(cliModule).toContain('brain-mcp-server/src/tools/brief-normalize.ts');
  });

  it('the fixtures are the BRAIN normalizers own output, not a hand-written table', () => {
    // If this ever diverges, the generator stopped calling the real normalizers.
    expect(fixtures.length).toBeGreaterThan(50);
    for (const f of fixtures) {
      const actual =
        f.normalizer === 'priority'
          ? normalizePriority(f.input)
          : f.normalizer === 'brief_type'
            ? normalizeBriefType(f.input)
            : normalizePhase(f.input);
      expect(actual, `fixture drift for ${f.normalizer}(${JSON.stringify(f.input)})`).toBe(
        f.expected,
      );
    }
  });

  it('covers every fold-table key and every canonical priority', () => {
    const covered = new Set(fixtures.map((f) => f.input));
    for (const p of CANONICAL_PRIORITIES) expect(covered.has(p)).toBe(true);
    expect(covered.has('P1')).toBe(true);
    expect(covered.has('P4-Trivial')).toBe(true); // the unknown that must NOT fold
    expect(covered.has('td')).toBe(true);
  });

  it('bakes fixtures for EVERY authored function family, not just the leaf normalizers', () => {
    // The TD-338 warden finding: the leaf-normalizer corpus left `normalizeSyncRow`
    // and the three `isCanonical*` predicates unguarded, while the module header
    // and the coding-guidelines rule both claimed full coverage.
    const { predicateFixtures, rowFixtures } = buildBriefNormalizeMirror();
    expect(fixtures.length).toBeGreaterThan(50);
    expect(predicateFixtures.length).toBeGreaterThan(50);
    expect(rowFixtures.length).toBeGreaterThan(8);
    for (const table of [cliModule]) {
      expect(table).toContain('export const NORMALIZE_FIXTURES');
      expect(table).toContain('export const PREDICATE_FIXTURES');
      expect(table).toContain('export const SYNC_ROW_FIXTURES');
    }
  });

  it('the row fixtures are normalizeSyncRow OWN output, and none bumped updated_at', () => {
    const { rowFixtures } = buildBriefNormalizeMirror();
    for (const f of rowFixtures) {
      const actual = normalizeSyncRow(f.table, f.row);
      expect(actual.row, `row fixture drift for ${f.table}`).toEqual(f.expectedRow);
      expect(actual.folds).toEqual(f.expectedFolds);
      expect(actual.nonCanonical).toEqual(f.expectedNonCanonical);
      // The invariant the whole no-oscillation argument rests on, asserted over
      // the corpus rather than one hand-picked row.
      if (f.row.updated_at !== undefined) {
        expect(f.expectedRow.updated_at).toBe(f.row.updated_at);
      }
    }
    // ...and the corpus must actually CONTAIN the trap, or the loop above is
    // vacuous for the fold-plus-bump mutation.
    expect(
      rowFixtures.some((f) => f.table === 'brief_status' && f.row.updated_at === 'P2'),
    ).toBe(true);
  });
});

describe('the mirror renderer DERIVES the normalizer surface from the map (TD-338 / TD-333)', () => {
  it('derives the id set from SYNC_NORMALIZED_FIELDS values, sorted', () => {
    expect(normalizerIdsInUse(SYNC_NORMALIZED_FIELDS)).toEqual([
      'brief_type',
      'phase',
      'priority',
    ]);
    // A second table reusing an id must not duplicate it.
    expect(
      normalizerIdsInUse({ a: { x: 'priority' }, b: { y: 'priority', z: 'phase' } }),
    ).toEqual(['phase', 'priority']);
  });

  it('emits the union and the dispatch table from that derived set', () => {
    const { cliModule } = buildBriefNormalizeMirror();
    // Neither is hand-listed in the builder any more, so adding a map entry
    // widens both automatically — this is what makes TD-333 "one line plus one
    // body" TRUE rather than a claim that needed correcting.
    expect(cliModule).toContain(
      'export type SyncNormalizerId = "brief_type" | "phase" | "priority";',
    );
    expect(cliModule).toContain(
      '  priority: { normalize: normalizePriority, isCanonical: isCanonicalPriority },',
    );
  });

  it('a NEW mapped id widens the union and the dispatch WITHOUT a renderer edit', () => {
    // Simulate TD-333 by mapping `status` to an id that HAS a body. The point is
    // the union/dispatch move on their own; only the body is authored.
    const { cliModule } = buildBriefNormalizeMirror({
      brief_status: { priority: 'priority', status: 'phase' },
    });
    expect(cliModule).toContain('export type SyncNormalizerId = "phase" | "priority";');
    expect(cliModule).toContain('    "status": "phase",');
    expect(cliModule).toContain(
      '  phase: { normalize: normalizePhase, isCanonical: isCanonicalPhase },',
    );
  });

  it('THROWS at generation time when a mapped id has no authored body', () => {
    // The real TD-333 shape: `status: 'status'` with no normalizeStatus yet.
    // Without this guard the renderer emits a dispatch row calling a function it
    // never defined, and the first symptom is a CLI typecheck error far from
    // the cause.
    expect(() =>
      buildBriefNormalizeMirror({ brief_status: { status: 'status' } }),
    ).toThrow(/no authored body for normalizer id\(s\) 'status'/);
    // ...and the message must say exactly what to add.
    expect(() => assertNormalizerBodies(['status'])).toThrow(
      /normalizeStatus\/isCanonicalStatus/,
    );
    expect(() => assertNormalizerBodies(['brief_type', 'phase', 'priority'])).not.toThrow();
  });
});

describe('SYNC_NORMALIZED_FIELDS is well-formed against SYNC_TABLES (TD-338)', () => {
  it('every mapped table exists in SYNC_TABLES', () => {
    const known = new Set(SYNC_TABLES.map((c) => c.table));
    for (const table of Object.keys(SYNC_NORMALIZED_FIELDS)) {
      expect(known.has(table), `mapped table '${table}' is not a SYNC_TABLES entry`).toBe(true);
    }
  });

  it('every mapped field is a synced COLUMN of that table', () => {
    // A typo'd field name would otherwise silently no-op at runtime — the same
    // failure mode the egress parity test guards for `redactCols`.
    for (const [table, fields] of Object.entries(SYNC_NORMALIZED_FIELDS)) {
      const cfg = SYNC_TABLES.find((c) => c.table === table);
      expect(cfg).toBeDefined();
      for (const field of Object.keys(fields)) {
        expect(
          cfg?.columns,
          `normalized field '${field}' on table '${table}' is not in its columns array`,
        ).toContain(field);
      }
    }
  });

  it('NEVER maps a table timestampCol or a syncKey column', () => {
    // The no-oscillation property (T3) and the row-lookup key both depend on
    // this. Asserted for every mapped table, not just brief_status.
    for (const [table, fields] of Object.entries(SYNC_NORMALIZED_FIELDS)) {
      const cfg = SYNC_TABLES.find((c) => c.table === table);
      const mapped = Object.keys(fields);
      expect(mapped).not.toContain(cfg?.timestampCol);
      for (const k of cfg?.syncKey ?? []) expect(mapped).not.toContain(k);
    }
  });

  it('never maps a field that a mergeFields strategy already owns', () => {
    // Two transforms on one column would make the stored value depend on order.
    for (const [table, fields] of Object.entries(SYNC_NORMALIZED_FIELDS)) {
      const cfg = SYNC_TABLES.find((c) => c.table === table);
      for (const field of Object.keys(fields)) {
        expect(cfg?.mergeFields?.[field]).toBeUndefined();
      }
    }
  });
});
