/**
 * TD-338 — brief-normalize CLI-mirror drift gate.
 *
 * Regenerates the committed artifact in-memory from the live `brief-normalize.ts`
 * exports via `buildBriefNormalizeMirror` and asserts byte-equality with the
 * committed file (read by repo-relative fs path — a FILE READ, never a
 * cross-package import). Any fold-table or canonical-set edit that is not
 * regenerated with `npm run gen:brief-normalize-mirror` fails here, so the CLI's
 * `mergeRows` cannot silently fold a different vocabulary than the brain's.
 *
 * The BEHAVIOURAL half of the guard lives on the CLI side
 * (`cli/src/__tests__/brief-normalize-mirror.test.ts`), which replays
 * `NORMALIZE_FIXTURES`. This file proves the fixtures are current; that one
 * proves the CLI reproduces them.
 *
 * @module tools/__tests__/brief-normalize-mirror-parity.test
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  assertNormalizerBodies,
  buildBriefNormalizeMirror,
  normalizerIdsInUse,
  MIRROR_CLI_REL_PATH,
} from '../brief-normalize-mirror.js';
import {
  CANONICAL_PRIORITIES,
  SYNC_NORMALIZED_FIELDS,
  normalizeBriefType,
  normalizePhase,
  normalizePriority,
  normalizeStatus,
  normalizeSyncRow,
} from '../brief-normalize.js';
import { SYNC_TABLES } from '../sync.js';

// __tests__ → tools → src → brain-mcp-server → repo root
const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../../../..');

function readCommitted(relPath: string): string {
  return readFileSync(resolve(REPO_ROOT, relPath), 'utf8');
}

describe('brief-normalize mirror parity (TD-338)', () => {
  const { cliModule, fixtures } = buildBriefNormalizeMirror();

  it('cli/src/lib/brief-normalize.generated.ts is byte-identical to a fresh regeneration', () => {
    expect(readCommitted(MIRROR_CLI_REL_PATH)).toBe(cliModule);
  });

  it('carries the DO-NOT-EDIT header the mirror rule requires', () => {
    expect(cliModule.startsWith('// GENERATED by ')).toBe(true);
    expect(cliModule).toContain('DO NOT EDIT BY HAND');
    expect(cliModule).toContain('brain-mcp-server/src/tools/brief-normalize.ts');
  });

  it('the fixtures are the BRAIN normalizers own output, not a hand-written table', () => {
    // If this ever diverges, the generator stopped calling the real normalizers.
    //
    // THE DISPATCH IS A MAP, NOT A TERNARY CHAIN. It used to be a nested
    // ternary whose final `else` was `normalizePhase`, so TD-333's `status`
    // fixtures were checked against the PHASE normalizer — 99 rows replayed
    // through the wrong function. A map plus the completeness assertion below
    // makes a new id fail LOUDLY instead of silently mis-routing.
    const byId: Record<string, (v: string | null | undefined) => string | null> = {
      priority: normalizePriority,
      brief_type: normalizeBriefType,
      phase: normalizePhase,
      status: normalizeStatus,
    };
    expect(fixtures.length).toBeGreaterThan(50);
    const idsSeen = new Set<string>();
    for (const f of fixtures) {
      const fn = byId[f.normalizer];
      expect(fn, `no dispatch arm for normalizer id '${f.normalizer}'`).toBeDefined();
      idsSeen.add(f.normalizer);
      expect(fn(f.input), `fixture drift for ${f.normalizer}(${JSON.stringify(f.input)})`).toBe(
        f.expected,
      );
    }
    // ...and every id the MAP declares must actually appear in the corpus, so a
    // mapped-but-unseeded normalizer cannot pass by having zero fixtures.
    expect([...idsSeen].sort()).toEqual(normalizerIdsInUse(SYNC_NORMALIZED_FIELDS));
  });

  it('covers every fold-table key and every canonical priority', () => {
    const covered = new Set(fixtures.map((f) => f.input));
    for (const p of CANONICAL_PRIORITIES) expect(covered.has(p)).toBe(true);
    expect(covered.has('P1')).toBe(true);
    expect(covered.has('P4-Trivial')).toBe(true); // the unknown that must NOT fold
    expect(covered.has('td')).toBe(true);
  });

  it('TD-333: all three corpora carry status rows, and they DISCRIMINATE', () => {
    // A new normalizer id that is mapped but not seeded gets a corpus of the
    // OTHER fields' edge cases — every row a vacuous passthrough. So assert the
    // outcome CLASSES, not just the count.
    const { predicateFixtures, rowFixtures } = buildBriefNormalizeMirror();
    const statusLeaf = fixtures.filter((f) => f.normalizer === 'status');
    expect(statusLeaf.length).toBeGreaterThan(20);
    expect(
      statusLeaf.some((f) => f.expected !== null && f.expected !== f.input),
      'no status FOLD in the corpus',
    ).toBe(true);
    expect(
      statusLeaf.some((f) => f.expected === f.input),
      'no status PASSTHROUGH in the corpus',
    ).toBe(true);
    // The three folds, by name.
    for (const [input, expected] of [
      ['Completed', 'Done'],
      ['Complete', 'Done'],
      ['InProgress', 'In Progress'],
    ] as const) {
      expect(
        statusLeaf.some((f) => f.input === input && f.expected === expected),
        `${input} -> ${expected} missing from the corpus`,
      ).toBe(true);
    }
    // The TD-311 exclusions must be REPRESENTED as passthroughs, or a future
    // fold of them would not be caught cross-package.
    for (const untouchable of [
      'Cancelled',
      'Superseded',
      'Done(Resolvedbydec8d1f)',
      'Split (see FR-061, FR-062, FR-063)',
    ]) {
      expect(
        statusLeaf.some((f) => f.input === untouchable && f.expected === untouchable),
        `${untouchable} missing from the corpus`,
      ).toBe(true);
    }

    const statusPred = predicateFixtures.filter((f) => f.normalizer === 'status');
    expect(statusPred.some((f) => f.expected === true)).toBe(true);
    expect(statusPred.some((f) => f.expected === false)).toBe(true);

    const statusRows = rowFixtures.filter((f) =>
      f.expectedFolds.some((d) => d.field === 'status'),
    );
    expect(statusRows.length).toBeGreaterThan(0);
    expect(
      rowFixtures.some((f) => f.expectedNonCanonical.some((d) => d.field === 'status')),
      'no status passthrough row fixture',
    ).toBe(true);
    // A status fold alongside a foldable-looking updated_at — the no-bump arm
    // re-armed for the FOURTH normalizer, not inherited from priority's.
    expect(
      statusRows.some((f) => f.row.updated_at === 'P2' && f.expectedRow.updated_at === 'P2'),
      'no status-fold row with a foldable-looking updated_at',
    ).toBe(true);
  });

  it('bakes fixtures for EVERY authored function family, not just the leaf normalizers', () => {
    // The TD-338 warden finding: the leaf-normalizer corpus left `normalizeSyncRow`
    // and the three `isCanonical*` predicates unguarded, while the module header
    // and the coding-guidelines rule both claimed full coverage.
    const { predicateFixtures, rowFixtures } = buildBriefNormalizeMirror();
    expect(fixtures.length).toBeGreaterThan(50);
    expect(predicateFixtures.length).toBeGreaterThan(50);
    expect(rowFixtures.length).toBeGreaterThan(8);
    for (const table of [cliModule]) {
      expect(table).toContain('export const NORMALIZE_FIXTURES');
      expect(table).toContain('export const PREDICATE_FIXTURES');
      expect(table).toContain('export const SYNC_ROW_FIXTURES');
    }
  });

  it('the row fixtures are normalizeSyncRow OWN output, and none bumped updated_at', () => {
    const { rowFixtures } = buildBriefNormalizeMirror();
    for (const f of rowFixtures) {
      const actual = normalizeSyncRow(f.table, f.row);
      expect(actual.row, `row fixture drift for ${f.table}`).toEqual(f.expectedRow);
      expect(actual.folds).toEqual(f.expectedFolds);
      expect(actual.nonCanonical).toEqual(f.expectedNonCanonical);
      // The invariant the whole no-oscillation argument rests on, asserted over
      // the corpus rather than one hand-picked row.
      if (f.row.updated_at !== undefined) {
        expect(f.expectedRow.updated_at).toBe(f.row.updated_at);
      }
    }
    // ...and the corpus must actually CONTAIN the trap, or the loop above is
    // vacuous for the fold-plus-bump mutation.
    expect(
      rowFixtures.some((f) => f.table === 'brief_status' && f.row.updated_at === 'P2'),
    ).toBe(true);
  });
});

describe('the mirror renderer DERIVES the normalizer surface from the map (TD-338 / TD-333)', () => {
  it('derives the id set from SYNC_NORMALIZED_FIELDS values, sorted', () => {
    expect(normalizerIdsInUse(SYNC_NORMALIZED_FIELDS)).toEqual([
      'brief_type',
      'phase',
      'priority',
      'status', // TD-333
    ]);
    // A second table reusing an id must not duplicate it.
    expect(
      normalizerIdsInUse({ a: { x: 'priority' }, b: { y: 'priority', z: 'phase' } }),
    ).toEqual(['phase', 'priority']);
  });

  it('emits the union and the dispatch table from that derived set', () => {
    const { cliModule } = buildBriefNormalizeMirror();
    // Neither is hand-listed in the builder, so adding a map entry widens both
    // automatically — the half of the TD-333 sequencing claim that WAS true.
    // (The DATA layer was not: TD-333 paid six edits in the builder. See the
    // NORMALIZER_BODIES docstring.) `status` joined this union under TD-333.
    expect(cliModule).toContain(
      'export type SyncNormalizerId = "brief_type" | "phase" | "priority" | "status";',
    );
    expect(cliModule).toContain(
      '  priority: { normalize: normalizePriority, isCanonical: isCanonicalPriority },',
    );
    expect(cliModule).toContain(
      '  status: { normalize: normalizeStatus, isCanonical: isCanonicalStatus },',
    );
    // ...and the DATA the status body reads must be emitted too, or the mirror
    // does not compile. This is the edit class the "one line" claim omitted.
    expect(cliModule).toContain('export const CANONICAL_STATUSES: readonly string[] = [');
    expect(cliModule).toContain('export const STATUS_ALIASES: Readonly<Record<string, string>> = {');
    expect(cliModule).toContain('const STATUS_CANONICAL: Readonly<Record<string, string>> =');
  });

  it('a NEW mapped id widens the union and the dispatch WITHOUT a renderer edit', () => {
    // Map a field to an id that HAS a body. The point is that the union and the
    // dispatch move on their own; only the body is authored.
    const { cliModule } = buildBriefNormalizeMirror({
      brief_status: { priority: 'priority', effort: 'phase' },
    });
    expect(cliModule).toContain('export type SyncNormalizerId = "phase" | "priority";');
    expect(cliModule).toContain('    "effort": "phase",');
    expect(cliModule).toContain(
      '  phase: { normalize: normalizePhase, isCanonical: isCanonicalPhase },',
    );
  });

  it('THROWS at generation time when a mapped id has no authored body', () => {
    // TD-333 DROVE THIS GUARD FOR REAL. `status: 'status'` was added to the map
    // before `NORMALIZER_BODIES.status` existed and the generator threw exactly
    // this message, naming `normalizeStatus`/`isCanonicalStatus`. It is now a
    // shipped id, so the guard is re-armed here with the NEXT unmapped one.
    // Without it the renderer emits a dispatch row calling a function it never
    // defined, and the first symptom is a CLI typecheck error far from the cause.
    expect(() =>
      buildBriefNormalizeMirror({ brief_status: { effort: 'effort' } }),
    ).toThrow(/no authored body for normalizer id\(s\) 'effort'/);
    // ...and the message must say exactly what to add.
    expect(() => assertNormalizerBodies(['effort'])).toThrow(
      /normalizeEffort\/isCanonicalEffort/,
    );
    // A multi-word id must PascalCase correctly in the remediation text — that
    // is what made the TD-333 message actionable (`normalizeStatus`, and
    // `normalizeBriefType` for the snake_case case).
    expect(() => assertNormalizerBodies(['claimed_by'])).toThrow(
      /normalizeClaimedBy\/isCanonicalClaimedBy/,
    );
    expect(() =>
      assertNormalizerBodies(['brief_type', 'phase', 'priority', 'status']),
    ).not.toThrow();
  });
});

describe('SYNC_NORMALIZED_FIELDS is well-formed against SYNC_TABLES (TD-338)', () => {
  it('every mapped table exists in SYNC_TABLES', () => {
    const known = new Set(SYNC_TABLES.map((c) => c.table));
    for (const table of Object.keys(SYNC_NORMALIZED_FIELDS)) {
      expect(known.has(table), `mapped table '${table}' is not a SYNC_TABLES entry`).toBe(true);
    }
  });

  it('every mapped field is a synced COLUMN of that table', () => {
    // A typo'd field name would otherwise silently no-op at runtime — the same
    // failure mode the egress parity test guards for `redactCols`.
    for (const [table, fields] of Object.entries(SYNC_NORMALIZED_FIELDS)) {
      const cfg = SYNC_TABLES.find((c) => c.table === table);
      expect(cfg).toBeDefined();
      for (const field of Object.keys(fields)) {
        expect(
          cfg?.columns,
          `normalized field '${field}' on table '${table}' is not in its columns array`,
        ).toContain(field);
      }
    }
  });

  it('NEVER maps a table timestampCol or a syncKey column', () => {
    // The no-oscillation property (T3) and the row-lookup key both depend on
    // this. Asserted for every mapped table, not just brief_status.
    for (const [table, fields] of Object.entries(SYNC_NORMALIZED_FIELDS)) {
      const cfg = SYNC_TABLES.find((c) => c.table === table);
      const mapped = Object.keys(fields);
      expect(mapped).not.toContain(cfg?.timestampCol);
      for (const k of cfg?.syncKey ?? []) expect(mapped).not.toContain(k);
    }
  });

  it('never maps a field that a mergeFields strategy already owns', () => {
    // Two transforms on one column would make the stored value depend on order.
    for (const [table, fields] of Object.entries(SYNC_NORMALIZED_FIELDS)) {
      const cfg = SYNC_TABLES.find((c) => c.table === table);
      for (const field of Object.keys(fields)) {
        expect(cfg?.mergeFields?.[field]).toBeUndefined();
      }
    }
  });
});
