/**
 * `igris add --core <surface>` writers — FR-180.
 *
 * Core-path materialization: writes the surface into the igris-ai SOURCE
 * checkout (`core/…`) and mirrors it to the runtime brain (`~/.igris/core/…`)
 * per the TD-096 mirror rule, verifying byte-equality with the
 * `verify_mirror.sh` primitive. Gated by `--core` / CWD auto-detect in
 * `verbs/add.ts` (D1).
 *
 * Phase 1 implements `addCoreSkill` (skills auto-discover, so the only write
 * is `core/skills/<name>/SKILL.md` + the runtime mirror — no manifest edit;
 * see FR-180-plan grounding #5). The agent/mcp/identity core writers land in
 * later phases.
 */

import {
  existsSync,
  mkdirSync,
  writeFileSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { execFileSync } from "node:child_process";
import { brainDir } from "../lib/paths.js";
import { info } from "../lib/log.js";

/** Result of a core-surface materialize. */
export interface AddCoreResult {
  /** True iff the source write + runtime mirror + verify all succeeded. */
  ok: boolean;
  /** Exit code to surface on failure (1 = write/mirror error, 2 = usage). */
  code: number;
  /** Human-readable failure reason (empty on success). */
  reason: string;
  /** The source path written (`<repo>/core/skills/<name>/SKILL.md`). */
  sourcePath: string;
  /** The runtime mirror path (`~/.igris/core/skills/<name>/SKILL.md`). */
  mirrorPath: string;
  /** Verbatim `verify_mirror.sh` output (so the caller can quote it). */
  verifyOutput: string;
}

/** Options for {@link addCoreSkill}. */
export interface AddCoreSkillOptions {
  /** Skill name (lower-kebab). */
  name?: string;
  /** Repo root (the igris-ai checkout). */
  projectRoot: string;
  /** Test seam: brain root override (defaults to brainDir()). */
  brainRoot?: string;
  /**
   * Test seam: skip the runtime mirror + verify_mirror step (unit tests that
   * only assert the source scaffold write). Default false — production always
   * mirrors + verifies (TD-096).
   */
  skipMirror?: boolean;
}

/** Skill name must be lower-kebab (mirrors the registry NAME_PATTERN). */
const SKILL_NAME_PATTERN = /^[a-z0-9][a-z0-9-]*$/;

/**
 * Build the SKILL.md scaffold for a new core skill. The `description:` scalar
 * contains a mid-value `: ` (`usage: /<name>`), so per §13 #587 / TD-219 the
 * WHOLE scalar is DOUBLE-QUOTED — strict YAML parsers (Codex) otherwise read
 * the second `: ` as a nested mapping and SILENTLY skip the skill.
 */
function skillScaffold(name: string): string {
  return `---
name: ${name}
description: "TODO describe ${name} - usage: /${name}"
disable-model-invocation: false
allowed-tools:
  - Read
  - Grep
  - Glob
  - Bash
---

# ${name}

> TODO: scaffold generated by \`igris add --core skill ${name}\`. Replace this
> body with the skill's real instructions.

## What this skill does

TODO.

## Steps

1. TODO.
`;
}

/**
 * FR-180: materialize a new CORE skill. Writes
 * `<repo>/core/skills/<name>/SKILL.md` (auto-discovered by the surfaces
 * manifest's core skills glob — no manifest edit needed), mirrors it to
 * `~/.igris/core/skills/<name>/SKILL.md` (TD-096), and verifies byte-equality
 * with `verify_mirror.sh`. Returns a structured result so `add.ts` can chain
 * `projectAndVerify` only when the write + mirror succeeded.
 *
 * Refuses to clobber an existing source SKILL.md (a re-add to core should be
 * an explicit edit, not a silent overwrite).
 */
export function addCoreSkill(opts: AddCoreSkillOptions): AddCoreResult {
  const sourcePath = join(
    opts.projectRoot,
    "core",
    "skills",
    opts.name ?? "",
    "SKILL.md",
  );
  const root = opts.brainRoot ?? brainDir();
  const mirrorPath = join(
    root,
    "core",
    "skills",
    opts.name ?? "",
    "SKILL.md",
  );

  if (opts.name === undefined || opts.name.length === 0) {
    return {
      ok: false,
      code: 2,
      reason: "skill <name> is required",
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }
  if (!SKILL_NAME_PATTERN.test(opts.name)) {
    return {
      ok: false,
      code: 2,
      reason: `name '${opts.name}' must match /^[a-z0-9][a-z0-9-]*$/`,
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }
  if (existsSync(sourcePath)) {
    return {
      ok: false,
      code: 1,
      reason: `core skill already exists at ${sourcePath}; edit it directly (no clobber)`,
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }

  // --- Write the source scaffold. ------------------------------------------
  try {
    mkdirSync(dirname(sourcePath), { recursive: true });
    writeFileSync(sourcePath, skillScaffold(opts.name), "utf-8");
  } catch (err) {
    return {
      ok: false,
      code: 1,
      reason: `failed to write source SKILL.md: ${(err as Error).message}`,
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }

  if (opts.skipMirror === true) {
    return {
      ok: true,
      code: 0,
      reason: "",
      sourcePath,
      mirrorPath,
      verifyOutput: "(mirror skipped)",
    };
  }

  // --- TD-096 mirror: cp source → runtime, then verify byte-equality. ------
  try {
    mkdirSync(dirname(mirrorPath), { recursive: true });
    execFileSync("cp", [sourcePath, mirrorPath], { stdio: "ignore" });
  } catch (err) {
    return {
      ok: false,
      code: 1,
      reason: `failed to mirror to runtime (${mirrorPath}): ${(err as Error).message}`,
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }

  // Run the verify_mirror.sh primitive (BR-062 self-evidencing verdict). The
  // script lives in the runtime brain at core/scripts/verify_mirror.sh.
  const verifyScript = join(root, "core", "scripts", "verify_mirror.sh");
  let verifyOutput = "";
  try {
    verifyOutput = execFileSync(
      "bash",
      [verifyScript, sourcePath, mirrorPath],
      { encoding: "utf-8" },
    );
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string };
    verifyOutput = `${e.stdout ?? ""}${e.stderr ?? ""}`;
    return {
      ok: false,
      code: 1,
      reason: `verify_mirror.sh reported a non-MATCH for ${opts.name}; see output`,
      sourcePath,
      mirrorPath,
      verifyOutput,
    };
  }

  info(`Mirror verified (${sourcePath} <-> ${mirrorPath}): MATCH`);
  return {
    ok: true,
    code: 0,
    reason: "",
    sourcePath,
    mirrorPath,
    verifyOutput,
  };
}
