/**
 * `igris add --core <surface>` writers — FR-180.
 *
 * Core-path materialization: writes the surface into the igris-ai SOURCE
 * checkout (`core/…`) and mirrors it to the runtime brain (`~/.igris/core/…`)
 * per the TD-096 mirror rule, verifying byte-equality with the
 * `verify_mirror.sh` primitive. Gated by `--core` / CWD auto-detect in
 * `verbs/add.ts` (D1).
 *
 * Phase 1 implements `addCoreSkill` (skills auto-discover, so the only write
 * is `core/skills/<name>/SKILL.md` + the runtime mirror — no manifest edit;
 * see FR-180-plan grounding #5). Phase 2 implements `addCoreAgent` (agents
 * live in the repo-root `harness-manifest.json` + a canonical
 * `core/agents/<name>.md`, mirrored to the runtime brain). FR-187 Phase 2b
 * (operator decision A1 + memory #872): agent ENUMERATION is no longer written
 * into the three legacy surfaces (`core/igris_tree.json` agents map, the two
 * "Available Agents" CSV lines). The SINGLE source of the agent roster is each
 * agent's OWN frontmatter, discovered into `core/os/INDEX.md` by re-running
 * `core/scripts/gen_os_index.sh`. So "enumerate" becomes "(vendor the agent .md)
 * + (regenerate the INDEX)". Phase 3 implements `addCoreMcp` (a core MCP server
 * is a `surfaces.mcp_servers[]` block in `core/scripts/cli-adapters/
 * surfaces-manifest.json` — the GLOBAL Layer-1 surfaces file the MCP flatten
 * reads when the project owns it; mirrored to the runtime brain, TD-096). Phase 5
 * implements `addCoreHook`. (FR-202 M4 retired the os_identity surface, so there
 * is no identity core writer.)
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { execFileSync } from "node:child_process";
import { brainDir } from "../lib/paths.js";
import { info } from "../lib/log.js";

/** Result of a core-surface materialize. */
export interface AddCoreResult {
  /** True iff the source write + runtime mirror + verify all succeeded. */
  ok: boolean;
  /** Exit code to surface on failure (1 = write/mirror error, 2 = usage). */
  code: number;
  /** Human-readable failure reason (empty on success). */
  reason: string;
  /** The source path written (`<repo>/core/skills/<name>/SKILL.md`). */
  sourcePath: string;
  /** The runtime mirror path (`~/.igris/core/skills/<name>/SKILL.md`). */
  mirrorPath: string;
  /** Verbatim `verify_mirror.sh` output (so the caller can quote it). */
  verifyOutput: string;
}

/** Options for {@link addCoreSkill}. */
export interface AddCoreSkillOptions {
  /** Skill name (lower-kebab). */
  name?: string;
  /** Repo root (the igris-ai checkout). */
  projectRoot: string;
  /** Test seam: brain root override (defaults to brainDir()). */
  brainRoot?: string;
  /**
   * Test seam: skip the runtime mirror + verify_mirror step (unit tests that
   * only assert the source scaffold write). Default false — production always
   * mirrors + verifies (TD-096).
   */
  skipMirror?: boolean;
}

/** Skill name must be lower-kebab (mirrors the registry NAME_PATTERN). */
const SKILL_NAME_PATTERN = /^[a-z0-9][a-z0-9-]*$/;

/**
 * Build the SKILL.md scaffold for a new core skill. The `description:` scalar
 * contains a mid-value `: ` (`usage: /<name>`), so per §13 #587 / TD-219 the
 * WHOLE scalar is DOUBLE-QUOTED — strict YAML parsers (Codex) otherwise read
 * the second `: ` as a nested mapping and SILENTLY skip the skill.
 */
function skillScaffold(name: string): string {
  return `---
name: ${name}
description: "TODO describe ${name} - usage: /${name}"
disable-model-invocation: false
allowed-tools:
  - Read
  - Grep
  - Glob
  - Bash
---

# ${name}

> TODO: scaffold generated by \`igris add --core skill ${name}\`. Replace this
> body with the skill's real instructions.

## What this skill does

TODO.

## Steps

1. TODO.
`;
}

/**
 * FR-180: materialize a new CORE skill. Writes
 * `<repo>/core/skills/<name>/SKILL.md` (auto-discovered by the surfaces
 * manifest's core skills glob — no manifest edit needed), mirrors it to
 * `~/.igris/core/skills/<name>/SKILL.md` (TD-096), and verifies byte-equality
 * with `verify_mirror.sh`. Returns a structured result so `add.ts` can chain
 * `projectAndVerify` only when the write + mirror succeeded.
 *
 * Refuses to clobber an existing source SKILL.md (a re-add to core should be
 * an explicit edit, not a silent overwrite).
 */
export function addCoreSkill(opts: AddCoreSkillOptions): AddCoreResult {
  const sourcePath = join(
    opts.projectRoot,
    "core",
    "skills",
    opts.name ?? "",
    "SKILL.md",
  );
  const root = opts.brainRoot ?? brainDir();
  const mirrorPath = join(
    root,
    "core",
    "skills",
    opts.name ?? "",
    "SKILL.md",
  );

  if (opts.name === undefined || opts.name.length === 0) {
    return {
      ok: false,
      code: 2,
      reason: "skill <name> is required",
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }
  if (!SKILL_NAME_PATTERN.test(opts.name)) {
    return {
      ok: false,
      code: 2,
      reason: `name '${opts.name}' must match /^[a-z0-9][a-z0-9-]*$/`,
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }
  if (existsSync(sourcePath)) {
    return {
      ok: false,
      code: 1,
      reason: `core skill already exists at ${sourcePath}; edit it directly (no clobber)`,
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }

  // --- Write the source scaffold. ------------------------------------------
  try {
    mkdirSync(dirname(sourcePath), { recursive: true });
    writeFileSync(sourcePath, skillScaffold(opts.name), "utf-8");
  } catch (err) {
    return {
      ok: false,
      code: 1,
      reason: `failed to write source SKILL.md: ${(err as Error).message}`,
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }

  if (opts.skipMirror === true) {
    return {
      ok: true,
      code: 0,
      reason: "",
      sourcePath,
      mirrorPath,
      verifyOutput: "(mirror skipped)",
    };
  }

  // --- TD-096 mirror: cp source → runtime, then verify byte-equality. ------
  try {
    mkdirSync(dirname(mirrorPath), { recursive: true });
    execFileSync("cp", [sourcePath, mirrorPath], { stdio: "ignore" });
  } catch (err) {
    return {
      ok: false,
      code: 1,
      reason: `failed to mirror to runtime (${mirrorPath}): ${(err as Error).message}`,
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }

  // Run the verify_mirror.sh primitive (BR-062 self-evidencing verdict). The
  // script lives in the runtime brain at core/scripts/verify_mirror.sh.
  const verifyScript = join(root, "core", "scripts", "verify_mirror.sh");
  let verifyOutput = "";
  try {
    verifyOutput = execFileSync(
      "bash",
      [verifyScript, sourcePath, mirrorPath],
      { encoding: "utf-8" },
    );
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string };
    verifyOutput = `${e.stdout ?? ""}${e.stderr ?? ""}`;
    return {
      ok: false,
      code: 1,
      reason: `verify_mirror.sh reported a non-MATCH for ${opts.name}; see output`,
      sourcePath,
      mirrorPath,
      verifyOutput,
    };
  }

  info(`Mirror verified (${sourcePath} <-> ${mirrorPath}): MATCH`);
  return {
    ok: true,
    code: 0,
    reason: "",
    sourcePath,
    mirrorPath,
    verifyOutput,
  };
}

// ---------------------------------------------------------------------------
// FR-180 Phase 2: core AGENT add path.
// ---------------------------------------------------------------------------

/** Agent name must be lower-kebab (parallels {@link SKILL_NAME_PATTERN}). */
const AGENT_NAME_PATTERN = /^[a-z0-9][a-z0-9-]*$/;

/** Result of one TD-096 mirror + verify for a single `core/` file. */
interface MirrorVerify {
  ok: boolean;
  /** Verbatim `verify_mirror.sh` output (so the caller can quote it). */
  output: string;
  /** Failure reason (empty on MATCH). */
  reason: string;
}

/**
 * TD-096: `cp <source> <mirror>` then run the `verify_mirror.sh` primitive,
 * returning a structured MATCH/non-MATCH verdict + the verbatim output. The
 * runtime `verify_mirror.sh` lives at `<brainRoot>/core/scripts/verify_mirror.sh`.
 * Shared by every `core/` file with a runtime mirror that an add touches (the
 * canonical agent prompt, the surfaces manifest, the shared hook script).
 */
function mirrorAndVerify(
  sourcePath: string,
  mirrorPath: string,
  brainRoot: string,
): MirrorVerify {
  try {
    mkdirSync(dirname(mirrorPath), { recursive: true });
    execFileSync("cp", [sourcePath, mirrorPath], { stdio: "ignore" });
  } catch (err) {
    return {
      ok: false,
      output: "",
      reason: `failed to mirror to runtime (${mirrorPath}): ${(err as Error).message}`,
    };
  }
  const verifyScript = join(brainRoot, "core", "scripts", "verify_mirror.sh");
  try {
    const output = execFileSync("bash", [verifyScript, sourcePath, mirrorPath], {
      encoding: "utf-8",
    });
    return { ok: true, output, reason: "" };
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string };
    return {
      ok: false,
      output: `${e.stdout ?? ""}${e.stderr ?? ""}`,
      reason: `verify_mirror.sh reported a non-MATCH for ${mirrorPath}; see output`,
    };
  }
}

/** Options for {@link addCoreAgent}. */
export interface AddCoreAgentOptions {
  /** Agent name (lower-kebab). */
  name?: string;
  /** Repo root (the igris-ai checkout). */
  projectRoot: string;
  /** Test seam: brain root override (defaults to brainDir()). */
  brainRoot?: string;
  /**
   * Test seam: skip the runtime mirror + verify_mirror steps (unit tests that
   * only assert the source writes). Default false — production always mirrors
   * + verifies the canonical prompt + the enumeration surfaces (TD-096).
   */
  skipMirror?: boolean;
}

/**
 * Build the agent-prompt scaffold for a new core agent. The `description:`
 * scalar is DOUBLE-QUOTED (§13 #587 / TD-219) so any future colon a maintainer
 * adds while filling it in cannot be misread as a nested mapping by strict-YAML
 * harnesses (Codex).
 */
function agentScaffold(name: string): string {
  return `---
name: ${name}
description: "TODO describe the ${name} agent and when the orchestrator should delegate to it."
tools: Read, Grep, Glob, Bash
model: sonnet
memory: project
---

# ${name.toUpperCase()}

You are **${name.toUpperCase()}**, a specialist in the Igris AI system.

> TODO: scaffold generated by \`igris add --core agent ${name}\`. Replace this
> body with the agent's real role, capabilities, workflow, and constraints.

## CORE IDENTITY

- **Persona:** ${name.toUpperCase()}
- **Role:** TODO
- **Mode:** TODO (read-only / read-write)
- **Focus:** TODO

## CONTEXT PROTOCOL

On activation, load your own context directly (no registry lookup) — name the
exact docs this agent needs, e.g.:
- \`~/.igris/projects/{project}/context/coding_guidelines.md\`
- {any other \`~/.igris/projects/{project}/context/<doc>.md\` this role consumes}

If a file is missing, proceed without it. An investigate-on-demand agent
preloads nothing — it states that here instead of a list.

You do NOT need: the os/ INDEX, SOUL.md, session files, brief protocol.

## CAPABILITIES

1. TODO.

## WORKFLOW

1. TODO.

## CONSTRAINTS

1. TODO.

---

**TODO TAGLINE.**
`;
}

/**
 * Build the repo-root `harness-manifest.json` agent entry for a new core agent,
 * mirroring the shape of the 7 existing entries (codex/gemini/opencode targets;
 * claude carries no target — it reads core agents natively from the
 * `.claude/agents/` symlinks `igris install` materializes, so there is no
 * harness-manifest projection to emit for it).
 */
function agentManifestEntry(name: string): Record<string, unknown> {
  return {
    name,
    canonical: {
      dir: "core/agents",
      file: `${name}.md`,
      versioned: false,
    },
    targets: [
      { type: "codex", path: `.codex/agents/${name}.toml` },
      { type: "gemini", path: `~/.gemini/agents/${name}.md` },
      { type: "opencode", path: `~/.config/opencode/agent/${name}.md` },
    ],
  };
}

/**
 * FR-180 (Phase 2) + FR-187 (Phase 2b): materialize a new CORE agent. Performs
 * the agent surface set in one atomic-ish pass (each write refuses to clobber,
 * so a partial re-run is safe to re-invoke after fixing the cause):
 *
 *   1. write `core/agents/<name>.md` (the canonical prompt) + TD-096 mirror to
 *      `~/.igris/core/agents/<name>.md` (install symlinks core agents from the
 *      brain root, so the runtime file must exist).
 *   2. append the agent entry to the repo-root `harness-manifest.json` (the
 *      authoritative agent manifest, FR-136). This file has NO runtime mirror —
 *      it is read from the checkout when `harness compile` runs from the repo.
 *   3. ENUMERATION (FR-187 Phase 2b): regenerate the agent roster by running
 *      `core/scripts/gen_os_index.sh`. The new agent's OWN frontmatter (the
 *      `name`/`description` we just wrote in step 1) is what makes it appear in
 *      the regenerated `core/os/INDEX.md` roster — this is the single source of
 *      enumeration (operator decision A1: the igris_tree.json agents map is
 *      retired; memory #872: CLAUDE.md is not an enumeration surface). The regen
 *      is SELF-VERIFYING: if the roster row did not appear, we fail loudly.
 *
 * Refuses to clobber an existing canonical prompt or an already-declared
 * manifest entry (a re-add to core should be an explicit edit, not a silent
 * overwrite).
 */
export function addCoreAgent(opts: AddCoreAgentOptions): AddCoreResult {
  const sourcePath = join(opts.projectRoot, "core", "agents", `${opts.name ?? ""}.md`);
  const root = opts.brainRoot ?? brainDir();
  const mirrorPath = join(root, "core", "agents", `${opts.name ?? ""}.md`);

  const fail = (code: number, reason: string, verifyOutput = ""): AddCoreResult => ({
    ok: false,
    code,
    reason,
    sourcePath,
    mirrorPath,
    verifyOutput,
  });

  if (opts.name === undefined || opts.name.length === 0) {
    return fail(2, "agent <name> is required");
  }
  if (!AGENT_NAME_PATTERN.test(opts.name)) {
    return fail(2, `name '${opts.name}' must match /^[a-z0-9][a-z0-9-]*$/`);
  }
  const name = opts.name;

  const manifestPath = join(opts.projectRoot, "harness-manifest.json");
  if (!existsSync(manifestPath)) {
    return fail(
      1,
      `repo-root harness-manifest.json not found at ${manifestPath}; not an igris-ai checkout`,
    );
  }
  if (existsSync(sourcePath)) {
    return fail(
      1,
      `core agent prompt already exists at ${sourcePath}; edit it directly (no clobber)`,
    );
  }

  // --- Parse the manifest + collision-check BEFORE any disk write. ----------
  let manifest: { agents?: Array<{ name?: string }> } & Record<string, unknown>;
  try {
    manifest = JSON.parse(readFileSync(manifestPath, "utf-8"));
  } catch (err) {
    return fail(1, `failed to parse ${manifestPath}: ${(err as Error).message}`);
  }
  const agents = Array.isArray(manifest.agents) ? manifest.agents : [];
  if (agents.some((a) => a.name === name)) {
    return fail(
      1,
      `agent '${name}' already declared in ${manifestPath}; edit it directly (no clobber)`,
    );
  }

  // --- 1. Canonical prompt + TD-096 mirror. ---------------------------------
  try {
    mkdirSync(dirname(sourcePath), { recursive: true });
    writeFileSync(sourcePath, agentScaffold(name), "utf-8");
  } catch (err) {
    return fail(1, `failed to write canonical agent prompt: ${(err as Error).message}`);
  }

  // --- 2. Append the manifest entry (NO runtime mirror — repo-only). --------
  agents.push(agentManifestEntry(name));
  manifest.agents = agents;
  try {
    writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf-8");
  } catch (err) {
    return fail(1, `failed to update ${manifestPath}: ${(err as Error).message}`);
  }

  // --- 3. ENUMERATION (FR-187 Phase 2b): regenerate the roster from frontmatter.
  // The agent's own frontmatter (step 1) is the source; gen_os_index.sh discovers
  // it into core/os/INDEX.md. Self-verifying: confirm the roster row appeared.
  const enumErr = regenerateAgentRoster(opts.projectRoot, name, true);
  if (enumErr !== null) {
    return fail(1, enumErr);
  }

  if (opts.skipMirror === true) {
    return {
      ok: true,
      code: 0,
      reason: "",
      sourcePath,
      mirrorPath,
      verifyOutput: "(mirror skipped)",
    };
  }

  // --- TD-096 mirror + verify the ONE touched `core/` file with a runtime
  // mirror: the canonical agent prompt. (harness-manifest.json is repo-only; the
  // regenerated core/os/INDEX.md is NOT mirrored here — its runtime cutover is a
  // separate concern, and Phase 2b only restores the source roster.)
  const mv = mirrorAndVerify(sourcePath, mirrorPath, root);
  if (!mv.ok) {
    return fail(1, mv.reason, mv.output);
  }
  info(`Mirror verified (${sourcePath} <-> ${mirrorPath}): MATCH`);

  return {
    ok: true,
    code: 0,
    reason: "",
    sourcePath,
    mirrorPath,
    verifyOutput: mv.output,
  };
}

/**
 * FR-187 (Phase 2b) agent enumeration: regenerate the agent roster by running
 * the discovery generator `core/scripts/gen_os_index.sh` (cwd = projectRoot).
 * The generator scans every `core/agents/*.md` frontmatter and rewrites
 * `core/os/INDEX.md` — so an agent appears (add) / disappears (remove) purely as
 * a function of whether its `.md` exists. This is the SINGLE source of agent
 * enumeration (operator decision A1: igris_tree.json agents map retired; memory
 * #872: CLAUDE.md is not an enumeration surface).
 *
 * Because the INDEX is regenerated WHOLESALE from the on-disk agent set, the
 * operation is naturally idempotent — re-running it never duplicates a row.
 *
 * `expectPresent` makes the call self-verifying: when `true` (add) we confirm the
 * regenerated roster now CONTAINS `| <name> |`; when `false` (remove) we confirm
 * it no longer does. A mismatch means the regen reported phantom success — we
 * surface a loud, actionable failure rather than claiming success.
 *
 * Returns null on success, or a reason string on the first failure (the caller
 * maps it to exit 1).
 */
function regenerateAgentRoster(
  projectRoot: string,
  name: string,
  expectPresent: boolean,
): string | null {
  const script = join(projectRoot, "core", "scripts", "gen_os_index.sh");
  if (!existsSync(script)) {
    return `agent roster generator not found at ${script}; not an igris-ai checkout`;
  }
  try {
    execFileSync("bash", [script], { cwd: projectRoot, stdio: "ignore" });
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string; message?: string };
    const detail = `${e.stderr ?? ""}${e.stdout ?? ""}`.trim() || e.message || "unknown error";
    return `gen_os_index.sh failed to regenerate the agent roster: ${detail}`;
  }

  // Self-verify: the roster row must (add) / must not (remove) be present.
  const indexPath = join(projectRoot, "core", "os", "INDEX.md");
  let index: string;
  try {
    index = readFileSync(indexPath, "utf-8");
  } catch (err) {
    return `could not read regenerated roster at ${indexPath}: ${(err as Error).message}`;
  }
  const rowPresent = index.includes(`| ${name} |`);
  if (expectPresent && !rowPresent) {
    return (
      `agent '${name}' did NOT appear in the regenerated roster (${indexPath}); ` +
      "the agent .md frontmatter (name/description) may be malformed — refusing to report phantom success"
    );
  }
  if (!expectPresent && rowPresent) {
    return (
      `agent '${name}' is STILL present in the regenerated roster (${indexPath}) ` +
      "after removal — refusing to report phantom success"
    );
  }
  return null;
}

// ---------------------------------------------------------------------------
// FR-180 Phase 3: core MCP add path.
// ---------------------------------------------------------------------------

/** MCP name must be lower-kebab (parallels the registry NAME_PATTERN). */
const MCP_NAME_PATTERN = /^[a-z0-9][a-z0-9-]*$/;

/** The MCP harness target types (mirrors VALID_MCP_TARGET_TYPES in registry.ts). */
const MCP_TARGET_TYPES = [
  "claude",
  "codex",
  "gemini",
  "opencode",
  "antigravity",
] as const;
type McpCoreTargetType = (typeof MCP_TARGET_TYPES)[number];

/**
 * §14 SECURITY: the env-var-indirection WRITE GUARD on the CORE path (FR-160
 * decision #1; identical rule to `parseEnvPair` in registry.ts). A `--env`
 * VALUE must be a single `${VAR}` reference — inline secrets are REJECTED so no
 * secret ever lands in the core surfaces manifest (which is committed + mirrored
 * to every install). The real secret is resolved from the environment by the
 * harness at launch time; the manifest only stores the indirection ref.
 */
const CORE_ENV_VAR_REF = /^\$\{[A-Za-z_][A-Za-z0-9_]*\}$/;

/** A parsed MCP target spec for the core block. */
interface CoreMcpTarget {
  type: McpCoreTargetType;
  method: "merge";
  enabled?: boolean;
}

/** Parse one `type:merge[:enabled]` target spec (mirrors parseMcpTarget). */
function parseCoreMcpTarget(spec: string): CoreMcpTarget | string {
  const parts = spec.split(":");
  if (parts.length < 2 || parts.length > 3) {
    return `--target '${spec}' must be of the form type:merge[:enabled]`;
  }
  const [type, method, enabledRaw] = parts;
  if (!(MCP_TARGET_TYPES as readonly string[]).includes(type)) {
    return `--target type '${type}' is not one of ${JSON.stringify(MCP_TARGET_TYPES)}`;
  }
  if (method !== "merge") {
    return `--target method '${method}' must be 'merge'`;
  }
  const t: CoreMcpTarget = { type: type as McpCoreTargetType, method: "merge" };
  if (enabledRaw !== undefined) {
    if (enabledRaw !== "true" && enabledRaw !== "false") {
      return `--target '${spec}' enabled flag must be 'true' or 'false'`;
    }
    t.enabled = enabledRaw === "true";
  }
  return t;
}

/** The core MCP block shape written into surfaces.mcp_servers[]. */
interface CoreMcpCanonical {
  command: string;
  args?: string[];
  env?: Record<string, string>;
  startup_timeout_sec?: number;
}
interface CoreMcpBlock {
  name: string;
  layer: "core";
  canonical: CoreMcpCanonical;
  targets: CoreMcpTarget[];
}

/** Options for {@link addCoreMcp}. */
export interface AddCoreMcpOptions {
  /** MCP server name (lower-kebab). */
  name?: string;
  /** Repo root (the igris-ai checkout). */
  projectRoot: string;
  /** MCP launch command (required for a NEW core block). */
  command?: string;
  /** MCP launch args. */
  args?: string[];
  /** MCP env indirection refs as "KEY=${VAR}" strings (§14: inline secrets rejected). */
  env?: string[];
  /** MCP target specs, each `type:merge[:enabled]` (≥1 required). */
  targets?: string[];
  /** Codex-only startup-timeout passthrough (seconds). */
  startupTimeoutSec?: number;
  /** Test seam: brain root override (defaults to brainDir()). */
  brainRoot?: string;
  /** Test seam: skip the runtime mirror + verify_mirror step. Default false. */
  skipMirror?: boolean;
}

/**
 * FR-180 (Phase 3): materialize a new CORE MCP server. A core MCP server is a
 * `surfaces.mcp_servers[]` block in the GLOBAL Layer-1 surfaces file
 * (`core/scripts/cli-adapters/surfaces-manifest.json`) — the file the
 * `flatten_mcp_rows` flatten reads (and unions) when the project being compiled
 * OWNS it. This is the MCP analogue of where core SKILLS auto-discover from and
 * where the core skills block already lives; unlike skills (which glob a dir),
 * MCP needs an explicit block, so we append one.
 *
 * The block carries the §14 `${VAR}`-indirected `canonical.env` (inline secrets
 * are REJECTED at the boundary — `parseCoreMcpEnv`), `command`/`args`, optional
 * `startup_timeout_sec`, and `targets[type:merge[:enabled]]`. After the source
 * write the file is mirrored to `~/.igris/core/scripts/cli-adapters/
 * surfaces-manifest.json` and byte-verified (TD-096).
 *
 * Refuses to clobber a `mcp_servers` block of the same name (a re-add to core
 * should be an explicit edit, not a silent overwrite — parity with the skill +
 * agent core writers).
 */
export function addCoreMcp(opts: AddCoreMcpOptions): AddCoreResult {
  const sourcePath = join(
    opts.projectRoot,
    "core",
    "scripts",
    "cli-adapters",
    "surfaces-manifest.json",
  );
  const root = opts.brainRoot ?? brainDir();
  const mirrorPath = join(
    root,
    "core",
    "scripts",
    "cli-adapters",
    "surfaces-manifest.json",
  );

  const fail = (code: number, reason: string, verifyOutput = ""): AddCoreResult => ({
    ok: false,
    code,
    reason,
    sourcePath,
    mirrorPath,
    verifyOutput,
  });

  // --- Guards (all BEFORE any disk write). ----------------------------------
  if (opts.name === undefined || opts.name.length === 0) {
    return fail(2, "mcp <name> is required");
  }
  if (!MCP_NAME_PATTERN.test(opts.name)) {
    return fail(2, `name '${opts.name}' must match /^[a-z0-9][a-z0-9-]*$/`);
  }
  const name = opts.name;

  if (opts.command === undefined || opts.command.length === 0) {
    return fail(2, `mcp '${name}': --command <bin> is required for a new core MCP server`);
  }

  if (opts.targets === undefined || opts.targets.length === 0) {
    return fail(2, `mcp '${name}': at least one --target <type:merge[:enabled]> is required`);
  }
  const targets: CoreMcpTarget[] = [];
  for (const spec of opts.targets) {
    const parsed = parseCoreMcpTarget(spec);
    if (typeof parsed === "string") {
      return fail(2, `mcp '${name}': ${parsed}`);
    }
    targets.push(parsed);
  }

  // §14 SECURITY: every --env VALUE must be a single ${VAR} reference.
  const envMap: Record<string, string> = {};
  for (const spec of opts.env ?? []) {
    const eq = spec.indexOf("=");
    if (eq <= 0) {
      return fail(2, `mcp '${name}': --env '${spec}' must be of the form KEY=\${VAR}`);
    }
    const key = spec.slice(0, eq);
    const value = spec.slice(eq + 1);
    if (!CORE_ENV_VAR_REF.test(value)) {
      return fail(
        2,
        `mcp '${name}': --env '${spec}': value '${value}' must be a single \${VAR} ` +
          "reference (e.g. ${MY_TOKEN}), NOT an inline secret. Core MCP env values are " +
          "stored as indirection refs; the real secret never enters the surfaces manifest.",
      );
    }
    envMap[key] = value;
  }

  if (!existsSync(sourcePath)) {
    return fail(
      1,
      `core surfaces manifest not found at ${sourcePath}; not an igris-ai checkout`,
    );
  }

  // --- Parse the manifest + collision-check BEFORE the write. ---------------
  let manifest: {
    surfaces?: { mcp_servers?: Array<{ name?: string }> } & Record<string, unknown>;
  } & Record<string, unknown>;
  try {
    manifest = JSON.parse(readFileSync(sourcePath, "utf-8"));
  } catch (err) {
    return fail(1, `failed to parse ${sourcePath}: ${(err as Error).message}`);
  }
  const surfaces = (manifest.surfaces ?? {}) as {
    mcp_servers?: CoreMcpBlock[];
  } & Record<string, unknown>;
  const existing = Array.isArray(surfaces.mcp_servers) ? surfaces.mcp_servers : [];
  if (existing.some((m) => m.name === name)) {
    return fail(
      1,
      `core MCP server '${name}' already declared in ${sourcePath}; edit it directly (no clobber)`,
    );
  }

  // --- Build + append the block. --------------------------------------------
  const canonical: CoreMcpCanonical = { command: opts.command };
  if (opts.args !== undefined && opts.args.length > 0) {
    canonical.args = opts.args;
  }
  if (Object.keys(envMap).length > 0) {
    canonical.env = envMap;
  }
  if (opts.startupTimeoutSec !== undefined) {
    canonical.startup_timeout_sec = opts.startupTimeoutSec;
  }
  const block: CoreMcpBlock = { name, layer: "core", canonical, targets };

  surfaces.mcp_servers = [...existing, block];
  manifest.surfaces = surfaces;
  try {
    writeFileSync(sourcePath, `${JSON.stringify(manifest, null, 2)}\n`, "utf-8");
  } catch (err) {
    return fail(1, `failed to update ${sourcePath}: ${(err as Error).message}`);
  }

  if (opts.skipMirror === true) {
    return {
      ok: true,
      code: 0,
      reason: "",
      sourcePath,
      mirrorPath,
      verifyOutput: "(mirror skipped)",
    };
  }

  // --- TD-096 mirror + verify the surfaces manifest. ------------------------
  const mv = mirrorAndVerify(sourcePath, mirrorPath, root);
  if (!mv.ok) {
    return fail(1, mv.reason, mv.output);
  }
  info(`Mirror verified (${sourcePath} <-> ${mirrorPath}): MATCH`);
  return {
    ok: true,
    code: 0,
    reason: "",
    sourcePath,
    mirrorPath,
    verifyOutput: mv.output,
  };
}

// ---------------------------------------------------------------------------
// FR-180 Phase 5 (D7): core HOOK add path.
// ---------------------------------------------------------------------------

/** Hook name must be lower-kebab (parallels SKILL/AGENT/MCP patterns). */
const HOOK_NAME_PATTERN = /^[a-z0-9][a-z0-9-]*$/;

/** The six portable events a hook can fire on (mirrors VALID_HOOK_EVENTS). */
const HOOK_EVENTS = [
  "SessionStart",
  "SessionEnd",
  "PreToolUse",
  "PostToolUse",
  "PreCompact",
  "PostCompact",
] as const;
type HookCoreEvent = (typeof HOOK_EVENTS)[number];

/** The hook harness target types (mirrors VALID_HOOK_TARGET_TYPES). */
const HOOK_TARGET_TYPES = ["claude", "opencode", "antigravity"] as const;
type HookCoreTargetType = (typeof HOOK_TARGET_TYPES)[number];

interface CoreHookTarget {
  type: HookCoreTargetType;
  method: "merge";
  enabled?: boolean;
}

/** Parse one `type:merge[:enabled]` hook target spec (mirrors parseCoreMcpTarget). */
function parseCoreHookTarget(spec: string): CoreHookTarget | string {
  const parts = spec.split(":");
  if (parts.length < 2 || parts.length > 3) {
    return `--target '${spec}' must be of the form type:merge[:enabled]`;
  }
  const [type, method, enabledRaw] = parts;
  if (!(HOOK_TARGET_TYPES as readonly string[]).includes(type)) {
    return `--target type '${type}' is not one of ${JSON.stringify(HOOK_TARGET_TYPES)}`;
  }
  if (method !== "merge") {
    return `--target method '${method}' must be 'merge'`;
  }
  const t: CoreHookTarget = { type: type as HookCoreTargetType, method: "merge" };
  if (enabledRaw !== undefined) {
    if (enabledRaw !== "true" && enabledRaw !== "false") {
      return `--target '${spec}' enabled flag must be 'true' or 'false'`;
    }
    t.enabled = enabledRaw === "true";
  }
  return t;
}

/** The core hook block shape written into surfaces.hooks[]. */
interface CoreHookCanonical {
  command: string;
  matcher?: string;
  timeout?: number;
}
interface CoreHookBlock {
  name: string;
  event: HookCoreEvent;
  layer: "core";
  canonical: CoreHookCanonical;
  targets: CoreHookTarget[];
}

/** Options for {@link addCoreHook}. */
export interface AddCoreHookOptions {
  /** Hook name (lower-kebab). */
  name?: string;
  /** Repo root (the igris-ai checkout). */
  projectRoot: string;
  /** The event the hook fires on (required). */
  event?: string;
  /** Tool-name glob for Pre/PostToolUse (optional). */
  matcher?: string;
  /** Per-hook timeout in seconds (optional). */
  timeout?: number;
  /** Hook target specs, each `type:merge[:enabled]` (default claude:merge). */
  targets?: string[];
  /** Test seam: brain root override (defaults to brainDir()). */
  brainRoot?: string;
  /** Test seam: skip the runtime mirror + verify_mirror step. Default false. */
  skipMirror?: boolean;
}

/** Scaffold body for a core hook script. Executable; a no-op pass-through. */
function coreHookScriptScaffold(name: string, event: string): string {
  return `#!/usr/bin/env bash
# Core Igris hook '${name}' for the ${event} event.
# Generated by \`igris add --core hook ${name} --event ${event}\`. Replace the
# body below with the hook's real behavior; this script ships in the brain-core
# tarball and runs on every install that registers the hook.
set -euo pipefail

# TODO: implement the ${event} hook for '${name}'.
exit 0
`;
}

/**
 * FR-180 (Phase 5): materialize a new CORE event-hook. A core hook is BOTH:
 *   1. a shared SCRIPT at `core/hooks/shared/<event>.sh` (+ TD-096 runtime
 *      mirror) — the script the harness runs;
 *   2. a `surfaces.hooks[]` block in `core/scripts/cli-adapters/
 *      surfaces-manifest.json` (+ TD-096 mirror) — the GLOBAL Layer-1 surfaces
 *      file `flatten_hook_rows` unions when the project OWNS it. The block's
 *      `canonical.command` points at `$HOME/.igris/core/hooks/shared/<event>.sh`
 *      so the projector merges THAT path into the harness config.
 *
 * NOTE on event-vs-name: the shared script is keyed by EVENT (parity with the
 * existing canonical hooks: session_start.sh, pre_tool_use.sh, …). A core hook
 * `add` writes/reuses `core/hooks/shared/<event>.sh` and registers a NAMED block
 * pointing at it. If a script for that event already exists (the canonical set),
 * we REUSE it (no clobber) and only add the surfaces block.
 *
 * Refuses to clobber a `hooks` block of the same name (a re-add to core should
 * be an explicit edit — parity with the skill/agent/mcp core writers).
 *
 * TD-096: the shared script + the surfaces manifest are both `core/` files with
 * a runtime mirror → both are cp'd + verify_mirror.sh'd.
 */
export function addCoreHook(opts: AddCoreHookOptions): AddCoreResult {
  const root = opts.brainRoot ?? brainDir();
  const manifestSource = join(
    opts.projectRoot,
    "core",
    "scripts",
    "cli-adapters",
    "surfaces-manifest.json",
  );
  const manifestMirror = join(
    root,
    "core",
    "scripts",
    "cli-adapters",
    "surfaces-manifest.json",
  );

  const fail = (code: number, reason: string, verifyOutput = ""): AddCoreResult => ({
    ok: false,
    code,
    reason,
    sourcePath: manifestSource,
    mirrorPath: manifestMirror,
    verifyOutput,
  });

  // --- Guards (all BEFORE any disk write). ----------------------------------
  if (opts.name === undefined || opts.name.length === 0) {
    return fail(2, "hook <name> is required");
  }
  if (!HOOK_NAME_PATTERN.test(opts.name)) {
    return fail(2, `name '${opts.name}' must match /^[a-z0-9][a-z0-9-]*$/`);
  }
  const name = opts.name;

  if (opts.event === undefined || opts.event.length === 0) {
    return fail(2, `hook '${name}': --event <${HOOK_EVENTS.join("|")}> is required`);
  }
  if (!(HOOK_EVENTS as readonly string[]).includes(opts.event)) {
    return fail(
      2,
      `hook '${name}': --event '${opts.event}' is not one of ${JSON.stringify(HOOK_EVENTS)}`,
    );
  }
  const event = opts.event as HookCoreEvent;

  const targetSpecs =
    opts.targets !== undefined && opts.targets.length > 0
      ? opts.targets
      : ["claude:merge"];
  const targets: CoreHookTarget[] = [];
  const seenTypes = new Set<string>();
  for (const spec of targetSpecs) {
    const parsed = parseCoreHookTarget(spec);
    if (typeof parsed === "string") {
      return fail(2, `hook '${name}': ${parsed}`);
    }
    if (seenTypes.has(parsed.type)) {
      return fail(2, `hook '${name}': duplicate --target type '${parsed.type}'`);
    }
    seenTypes.add(parsed.type);
    targets.push(parsed);
  }

  if (!existsSync(manifestSource)) {
    return fail(
      1,
      `core surfaces manifest not found at ${manifestSource}; not an igris-ai checkout`,
    );
  }

  // --- Parse the manifest + collision-check BEFORE the write. ---------------
  let manifest: {
    surfaces?: {
      hooks?: Array<{ name?: string; event?: string; targets?: { type?: string }[] }>;
    } & Record<string, unknown>;
  } & Record<string, unknown>;
  try {
    manifest = JSON.parse(readFileSync(manifestSource, "utf-8"));
  } catch (err) {
    return fail(1, `failed to parse ${manifestSource}: ${(err as Error).message}`);
  }
  const surfaces = (manifest.surfaces ?? {}) as {
    hooks?: CoreHookBlock[];
  } & Record<string, unknown>;
  const existing = Array.isArray(surfaces.hooks) ? surfaces.hooks : [];
  if (existing.some((h) => h.name === name)) {
    return fail(
      1,
      `core hook '${name}' already declared in ${manifestSource}; edit it directly (no clobber)`,
    );
  }
  // (event, target type) cell collision across existing blocks.
  const seenCells = new Set<string>();
  for (const b of existing) {
    for (const t of b.targets ?? []) {
      seenCells.add(`${b.event} ${t.type}`);
    }
  }
  for (const t of targets) {
    const cell = `${event} ${t.type}`;
    if (seenCells.has(cell)) {
      return fail(
        1,
        `core hook cell (${event}, ${t.type}) already declared in ${manifestSource}; ` +
          "two hooks must not both own the same event in the same harness",
      );
    }
  }

  // --- 1. Write/reuse the shared script. ------------------------------------
  const scriptSource = join(
    opts.projectRoot,
    "core",
    "hooks",
    "shared",
    `${event}.sh`,
  );
  const scriptMirror = join(root, "core", "hooks", "shared", `${event}.sh`);
  if (!existsSync(scriptSource)) {
    try {
      mkdirSync(dirname(scriptSource), { recursive: true });
      writeFileSync(scriptSource, coreHookScriptScaffold(name, event), {
        encoding: "utf-8",
        mode: 0o755,
      });
    } catch (err) {
      return fail(1, `failed to write core hook script: ${(err as Error).message}`);
    }
  }

  // --- 2. Build + append the surfaces block. --------------------------------
  const canonical: CoreHookCanonical = {
    command: `$HOME/.igris/core/hooks/shared/${event}.sh`,
  };
  if (opts.matcher !== undefined && opts.matcher.length > 0) {
    canonical.matcher = opts.matcher;
  }
  if (opts.timeout !== undefined) {
    canonical.timeout = opts.timeout;
  }
  const block: CoreHookBlock = { name, event, layer: "core", canonical, targets };
  surfaces.hooks = [...existing, block];
  manifest.surfaces = surfaces;
  try {
    writeFileSync(manifestSource, `${JSON.stringify(manifest, null, 2)}\n`, "utf-8");
  } catch (err) {
    return fail(1, `failed to update ${manifestSource}: ${(err as Error).message}`);
  }

  if (opts.skipMirror === true) {
    return {
      ok: true,
      code: 0,
      reason: "",
      sourcePath: manifestSource,
      mirrorPath: manifestMirror,
      verifyOutput: "(mirror skipped)",
    };
  }

  // --- TD-096 mirror + verify BOTH core/ files (the script + the manifest). --
  const verifyParts: string[] = [];
  const mirrors: Array<{ src: string; dst: string; label: string }> = [
    { src: scriptSource, dst: scriptMirror, label: "core/hooks/shared script" },
    { src: manifestSource, dst: manifestMirror, label: "core surfaces-manifest.json" },
  ];
  for (const m of mirrors) {
    const mv = mirrorAndVerify(m.src, m.dst, root);
    verifyParts.push(`# ${m.label}\n${mv.output}`);
    if (!mv.ok) {
      return fail(1, mv.reason, verifyParts.join("\n"));
    }
    info(`Mirror verified (${m.src} <-> ${m.dst}): MATCH`);
  }

  return {
    ok: true,
    code: 0,
    reason: "",
    sourcePath: manifestSource,
    mirrorPath: manifestMirror,
    verifyOutput: verifyParts.join("\n"),
  };
}
