/**
 * `igris add --core <surface>` writers — FR-180.
 *
 * Core-path materialization: writes the surface into the igris-ai SOURCE
 * checkout (`core/…`) and mirrors it to the runtime brain (`~/.igris/core/…`)
 * per the TD-096 mirror rule, verifying byte-equality with the
 * `verify_mirror.sh` primitive. Gated by `--core` / CWD auto-detect in
 * `verbs/add.ts` (D1).
 *
 * Phase 1 implements `addCoreSkill` (skills auto-discover, so the only write
 * is `core/skills/<name>/SKILL.md` + the runtime mirror — no manifest edit;
 * see FR-180-plan grounding #5). Phase 2 implements `addCoreAgent` (agents
 * live in the repo-root `harness-manifest.json` + a canonical
 * `core/agents/<name>.md`, mirrored to the runtime brain; plus the §13 agent
 * enumeration surfaces). The mcp/identity core writers land in later phases.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { execFileSync } from "node:child_process";
import { brainDir } from "../lib/paths.js";
import { info } from "../lib/log.js";

/** Result of a core-surface materialize. */
export interface AddCoreResult {
  /** True iff the source write + runtime mirror + verify all succeeded. */
  ok: boolean;
  /** Exit code to surface on failure (1 = write/mirror error, 2 = usage). */
  code: number;
  /** Human-readable failure reason (empty on success). */
  reason: string;
  /** The source path written (`<repo>/core/skills/<name>/SKILL.md`). */
  sourcePath: string;
  /** The runtime mirror path (`~/.igris/core/skills/<name>/SKILL.md`). */
  mirrorPath: string;
  /** Verbatim `verify_mirror.sh` output (so the caller can quote it). */
  verifyOutput: string;
}

/** Options for {@link addCoreSkill}. */
export interface AddCoreSkillOptions {
  /** Skill name (lower-kebab). */
  name?: string;
  /** Repo root (the igris-ai checkout). */
  projectRoot: string;
  /** Test seam: brain root override (defaults to brainDir()). */
  brainRoot?: string;
  /**
   * Test seam: skip the runtime mirror + verify_mirror step (unit tests that
   * only assert the source scaffold write). Default false — production always
   * mirrors + verifies (TD-096).
   */
  skipMirror?: boolean;
}

/** Skill name must be lower-kebab (mirrors the registry NAME_PATTERN). */
const SKILL_NAME_PATTERN = /^[a-z0-9][a-z0-9-]*$/;

/**
 * Build the SKILL.md scaffold for a new core skill. The `description:` scalar
 * contains a mid-value `: ` (`usage: /<name>`), so per §13 #587 / TD-219 the
 * WHOLE scalar is DOUBLE-QUOTED — strict YAML parsers (Codex) otherwise read
 * the second `: ` as a nested mapping and SILENTLY skip the skill.
 */
function skillScaffold(name: string): string {
  return `---
name: ${name}
description: "TODO describe ${name} - usage: /${name}"
disable-model-invocation: false
allowed-tools:
  - Read
  - Grep
  - Glob
  - Bash
---

# ${name}

> TODO: scaffold generated by \`igris add --core skill ${name}\`. Replace this
> body with the skill's real instructions.

## What this skill does

TODO.

## Steps

1. TODO.
`;
}

/**
 * FR-180: materialize a new CORE skill. Writes
 * `<repo>/core/skills/<name>/SKILL.md` (auto-discovered by the surfaces
 * manifest's core skills glob — no manifest edit needed), mirrors it to
 * `~/.igris/core/skills/<name>/SKILL.md` (TD-096), and verifies byte-equality
 * with `verify_mirror.sh`. Returns a structured result so `add.ts` can chain
 * `projectAndVerify` only when the write + mirror succeeded.
 *
 * Refuses to clobber an existing source SKILL.md (a re-add to core should be
 * an explicit edit, not a silent overwrite).
 */
export function addCoreSkill(opts: AddCoreSkillOptions): AddCoreResult {
  const sourcePath = join(
    opts.projectRoot,
    "core",
    "skills",
    opts.name ?? "",
    "SKILL.md",
  );
  const root = opts.brainRoot ?? brainDir();
  const mirrorPath = join(
    root,
    "core",
    "skills",
    opts.name ?? "",
    "SKILL.md",
  );

  if (opts.name === undefined || opts.name.length === 0) {
    return {
      ok: false,
      code: 2,
      reason: "skill <name> is required",
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }
  if (!SKILL_NAME_PATTERN.test(opts.name)) {
    return {
      ok: false,
      code: 2,
      reason: `name '${opts.name}' must match /^[a-z0-9][a-z0-9-]*$/`,
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }
  if (existsSync(sourcePath)) {
    return {
      ok: false,
      code: 1,
      reason: `core skill already exists at ${sourcePath}; edit it directly (no clobber)`,
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }

  // --- Write the source scaffold. ------------------------------------------
  try {
    mkdirSync(dirname(sourcePath), { recursive: true });
    writeFileSync(sourcePath, skillScaffold(opts.name), "utf-8");
  } catch (err) {
    return {
      ok: false,
      code: 1,
      reason: `failed to write source SKILL.md: ${(err as Error).message}`,
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }

  if (opts.skipMirror === true) {
    return {
      ok: true,
      code: 0,
      reason: "",
      sourcePath,
      mirrorPath,
      verifyOutput: "(mirror skipped)",
    };
  }

  // --- TD-096 mirror: cp source → runtime, then verify byte-equality. ------
  try {
    mkdirSync(dirname(mirrorPath), { recursive: true });
    execFileSync("cp", [sourcePath, mirrorPath], { stdio: "ignore" });
  } catch (err) {
    return {
      ok: false,
      code: 1,
      reason: `failed to mirror to runtime (${mirrorPath}): ${(err as Error).message}`,
      sourcePath,
      mirrorPath,
      verifyOutput: "",
    };
  }

  // Run the verify_mirror.sh primitive (BR-062 self-evidencing verdict). The
  // script lives in the runtime brain at core/scripts/verify_mirror.sh.
  const verifyScript = join(root, "core", "scripts", "verify_mirror.sh");
  let verifyOutput = "";
  try {
    verifyOutput = execFileSync(
      "bash",
      [verifyScript, sourcePath, mirrorPath],
      { encoding: "utf-8" },
    );
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string };
    verifyOutput = `${e.stdout ?? ""}${e.stderr ?? ""}`;
    return {
      ok: false,
      code: 1,
      reason: `verify_mirror.sh reported a non-MATCH for ${opts.name}; see output`,
      sourcePath,
      mirrorPath,
      verifyOutput,
    };
  }

  info(`Mirror verified (${sourcePath} <-> ${mirrorPath}): MATCH`);
  return {
    ok: true,
    code: 0,
    reason: "",
    sourcePath,
    mirrorPath,
    verifyOutput,
  };
}

// ---------------------------------------------------------------------------
// FR-180 Phase 2: core AGENT add path.
// ---------------------------------------------------------------------------

/** Agent name must be lower-kebab (parallels {@link SKILL_NAME_PATTERN}). */
const AGENT_NAME_PATTERN = /^[a-z0-9][a-z0-9-]*$/;

/** Result of one TD-096 mirror + verify for a single `core/` file. */
interface MirrorVerify {
  ok: boolean;
  /** Verbatim `verify_mirror.sh` output (so the caller can quote it). */
  output: string;
  /** Failure reason (empty on MATCH). */
  reason: string;
}

/**
 * TD-096: `cp <source> <mirror>` then run the `verify_mirror.sh` primitive,
 * returning a structured MATCH/non-MATCH verdict + the verbatim output. The
 * runtime `verify_mirror.sh` lives at `<brainRoot>/core/scripts/verify_mirror.sh`.
 * Shared by every `core/` file the agent add touches (the canonical agent
 * prompt + the 3 §13 enumeration surfaces that have a runtime mirror).
 */
function mirrorAndVerify(
  sourcePath: string,
  mirrorPath: string,
  brainRoot: string,
): MirrorVerify {
  try {
    mkdirSync(dirname(mirrorPath), { recursive: true });
    execFileSync("cp", [sourcePath, mirrorPath], { stdio: "ignore" });
  } catch (err) {
    return {
      ok: false,
      output: "",
      reason: `failed to mirror to runtime (${mirrorPath}): ${(err as Error).message}`,
    };
  }
  const verifyScript = join(brainRoot, "core", "scripts", "verify_mirror.sh");
  try {
    const output = execFileSync("bash", [verifyScript, sourcePath, mirrorPath], {
      encoding: "utf-8",
    });
    return { ok: true, output, reason: "" };
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string };
    return {
      ok: false,
      output: `${e.stdout ?? ""}${e.stderr ?? ""}`,
      reason: `verify_mirror.sh reported a non-MATCH for ${mirrorPath}; see output`,
    };
  }
}

/** Options for {@link addCoreAgent}. */
export interface AddCoreAgentOptions {
  /** Agent name (lower-kebab). */
  name?: string;
  /** Repo root (the igris-ai checkout). */
  projectRoot: string;
  /** Test seam: brain root override (defaults to brainDir()). */
  brainRoot?: string;
  /**
   * Test seam: skip the runtime mirror + verify_mirror steps (unit tests that
   * only assert the source writes). Default false — production always mirrors
   * + verifies the canonical prompt + the enumeration surfaces (TD-096).
   */
  skipMirror?: boolean;
}

/**
 * Build the agent-prompt scaffold for a new core agent. The `description:`
 * scalar is DOUBLE-QUOTED (§13 #587 / TD-219) so any future colon a maintainer
 * adds while filling it in cannot be misread as a nested mapping by strict-YAML
 * harnesses (Codex).
 */
function agentScaffold(name: string): string {
  return `---
name: ${name}
description: "TODO describe the ${name} agent and when the orchestrator should delegate to it."
tools: Read, Grep, Glob, Bash
model: sonnet
memory: project
---

# ${name.toUpperCase()}

You are **${name.toUpperCase()}**, a specialist in the Igris AI system.

> TODO: scaffold generated by \`igris add --core agent ${name}\`. Replace this
> body with the agent's real role, capabilities, workflow, and constraints.

## CORE IDENTITY

- **Persona:** ${name.toUpperCase()}
- **Role:** TODO
- **Mode:** TODO (read-only / read-write)
- **Focus:** TODO

## CONTEXT PROTOCOL

On activation:
1. Read \`~/.igris/core/igris_tree.json\`
2. Find \`agents.${name}\` → load listed context files

## CAPABILITIES

1. TODO.

## WORKFLOW

1. TODO.

## CONSTRAINTS

1. TODO.

---

**TODO TAGLINE.**
`;
}

/**
 * Build the repo-root `harness-manifest.json` agent entry for a new core agent,
 * mirroring the shape of the 7 existing entries (codex/gemini/opencode targets;
 * claude rides the whole-file CLAUDE.md render so it carries no target here).
 */
function agentManifestEntry(name: string): Record<string, unknown> {
  return {
    name,
    canonical: {
      dir: "core/agents",
      file: `${name}.md`,
      versioned: false,
    },
    targets: [
      { type: "codex", path: `.codex/agents/${name}.toml` },
      { type: "gemini", path: `~/.gemini/agents/${name}.md` },
      { type: "opencode", path: `~/.config/opencode/agent/${name}.md` },
    ],
  };
}

/**
 * Insert `name` into a comma+space-separated "Available Agents" line, keeping
 * it on the SAME single line (the enumeration-surface convention) and
 * idempotent (no-op if already present). Returns the new line.
 */
function appendAgentToCsvLine(line: string, name: string): string {
  const names = line
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
  if (names.includes(name)) {
    return line;
  }
  names.push(name);
  return names.join(", ");
}

/**
 * FR-180 (Phase 2): materialize a new CORE agent. Performs the full §13 agent
 * surface set in one atomic-ish pass (each write refuses to clobber, so a
 * partial re-run is safe to re-invoke after fixing the cause):
 *
 *   1. write `core/agents/<name>.md` (the canonical prompt) + TD-096 mirror to
 *      `~/.igris/core/agents/<name>.md` (install symlinks core agents from the
 *      brain root, so the runtime file must exist).
 *   2. append the agent entry to the repo-root `harness-manifest.json` (the
 *      authoritative agent manifest, FR-136). This file has NO runtime mirror —
 *      it is read from the checkout when `harness compile` runs from the repo.
 *   3. §13 agent enumeration surfaces: `core/igris_tree.json` `agents` map
 *      (+ mirror), `core/templates/CLAUDE.md.tmpl` Available Agents line
 *      (+ mirror), root `CLAUDE.md` Available Agents line.
 *
 * Refuses to clobber an existing canonical prompt or an already-declared
 * manifest entry (a re-add to core should be an explicit edit, not a silent
 * overwrite).
 */
export function addCoreAgent(opts: AddCoreAgentOptions): AddCoreResult {
  const sourcePath = join(opts.projectRoot, "core", "agents", `${opts.name ?? ""}.md`);
  const root = opts.brainRoot ?? brainDir();
  const mirrorPath = join(root, "core", "agents", `${opts.name ?? ""}.md`);

  const fail = (code: number, reason: string, verifyOutput = ""): AddCoreResult => ({
    ok: false,
    code,
    reason,
    sourcePath,
    mirrorPath,
    verifyOutput,
  });

  if (opts.name === undefined || opts.name.length === 0) {
    return fail(2, "agent <name> is required");
  }
  if (!AGENT_NAME_PATTERN.test(opts.name)) {
    return fail(2, `name '${opts.name}' must match /^[a-z0-9][a-z0-9-]*$/`);
  }
  const name = opts.name;

  const manifestPath = join(opts.projectRoot, "harness-manifest.json");
  if (!existsSync(manifestPath)) {
    return fail(
      1,
      `repo-root harness-manifest.json not found at ${manifestPath}; not an igris-ai checkout`,
    );
  }
  if (existsSync(sourcePath)) {
    return fail(
      1,
      `core agent prompt already exists at ${sourcePath}; edit it directly (no clobber)`,
    );
  }

  // --- Parse the manifest + collision-check BEFORE any disk write. ----------
  let manifest: { agents?: Array<{ name?: string }> } & Record<string, unknown>;
  try {
    manifest = JSON.parse(readFileSync(manifestPath, "utf-8"));
  } catch (err) {
    return fail(1, `failed to parse ${manifestPath}: ${(err as Error).message}`);
  }
  const agents = Array.isArray(manifest.agents) ? manifest.agents : [];
  if (agents.some((a) => a.name === name)) {
    return fail(
      1,
      `agent '${name}' already declared in ${manifestPath}; edit it directly (no clobber)`,
    );
  }

  // --- 1. Canonical prompt + TD-096 mirror. ---------------------------------
  try {
    mkdirSync(dirname(sourcePath), { recursive: true });
    writeFileSync(sourcePath, agentScaffold(name), "utf-8");
  } catch (err) {
    return fail(1, `failed to write canonical agent prompt: ${(err as Error).message}`);
  }

  // --- 2. Append the manifest entry (NO runtime mirror — repo-only). --------
  agents.push(agentManifestEntry(name));
  manifest.agents = agents;
  try {
    writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf-8");
  } catch (err) {
    return fail(1, `failed to update ${manifestPath}: ${(err as Error).message}`);
  }

  // --- 3. §13 agent enumeration surfaces. -----------------------------------
  const enumErr = updateAgentEnumerationSurfaces(opts.projectRoot, name);
  if (enumErr !== null) {
    return fail(1, enumErr);
  }

  if (opts.skipMirror === true) {
    return {
      ok: true,
      code: 0,
      reason: "",
      sourcePath,
      mirrorPath,
      verifyOutput: "(mirror skipped)",
    };
  }

  // --- TD-096 mirror + verify every touched `core/` file with a runtime
  // mirror: the canonical prompt, the routing tree, and the CLAUDE template.
  // (harness-manifest.json + root CLAUDE.md have NO runtime mirror.)
  const verifyParts: string[] = [];
  const mirrors: Array<{ src: string; dst: string; label: string }> = [
    { src: sourcePath, dst: mirrorPath, label: "core/agents prompt" },
    {
      src: join(opts.projectRoot, "core", "igris_tree.json"),
      dst: join(root, "core", "igris_tree.json"),
      label: "core/igris_tree.json",
    },
    {
      src: join(opts.projectRoot, "core", "templates", "CLAUDE.md.tmpl"),
      dst: join(root, "core", "templates", "CLAUDE.md.tmpl"),
      label: "core/templates/CLAUDE.md.tmpl",
    },
  ];
  for (const m of mirrors) {
    const mv = mirrorAndVerify(m.src, m.dst, root);
    verifyParts.push(`# ${m.label}\n${mv.output}`);
    if (!mv.ok) {
      return fail(1, mv.reason, verifyParts.join("\n"));
    }
    info(`Mirror verified (${m.src} <-> ${m.dst}): MATCH`);
  }

  return {
    ok: true,
    code: 0,
    reason: "",
    sourcePath,
    mirrorPath,
    verifyOutput: verifyParts.join("\n"),
  };
}

/**
 * §13 agent enumeration: register `name` into the three agent-list surfaces
 * that live in the repo `core/` tree + the root working copy:
 *   - `core/igris_tree.json` `agents` map (add an empty-load entry — a scaffold
 *     agent preloads no context until a maintainer fills it in).
 *   - `core/templates/CLAUDE.md.tmpl` "Available Agents" CSV line.
 *   - root `CLAUDE.md` "Available Agents" CSV line.
 * Idempotent per surface. Returns null on success, or a reason string on the
 * first failure (the caller maps it to exit 1).
 */
function updateAgentEnumerationSurfaces(
  projectRoot: string,
  name: string,
): string | null {
  // (a) igris_tree.json agents map.
  const treePath = join(projectRoot, "core", "igris_tree.json");
  try {
    const tree = JSON.parse(readFileSync(treePath, "utf-8")) as {
      agents?: Record<string, unknown>;
    } & Record<string, unknown>;
    const agents = (tree.agents ?? {}) as Record<string, unknown>;
    if (!(name in agents)) {
      agents[name] = {
        load: [],
        note: "Scaffold agent (igris add --core agent) — preloads no context until configured",
      };
      tree.agents = agents;
      writeFileSync(treePath, `${JSON.stringify(tree, null, 2)}\n`, "utf-8");
    }
  } catch (err) {
    return `failed to update ${treePath}: ${(err as Error).message}`;
  }

  // (b) + (c) the two "Available Agents" CSV lines.
  const csvSurfaces = [
    join(projectRoot, "core", "templates", "CLAUDE.md.tmpl"),
    join(projectRoot, "CLAUDE.md"),
  ];
  for (const file of csvSurfaces) {
    if (!existsSync(file)) {
      // The CLAUDE.md.tmpl + root CLAUDE.md are both expected in a checkout; a
      // missing one is a structural error worth surfacing, not silently skipping.
      return `expected enumeration surface not found: ${file}`;
    }
    try {
      const lines = readFileSync(file, "utf-8").split("\n");
      let updated = false;
      for (let i = 0; i < lines.length; i++) {
        if (
          i > 0 &&
          lines[i - 1].trim() === "## Available Agents" &&
          lines[i].trim().length > 0
        ) {
          lines[i] = appendAgentToCsvLine(lines[i], name);
          updated = true;
          break;
        }
      }
      if (!updated) {
        return `could not find the "## Available Agents" line in ${file}`;
      }
      writeFileSync(file, lines.join("\n"), "utf-8");
    } catch (err) {
      return `failed to update ${file}: ${(err as Error).message}`;
    }
  }

  return null;
}
